-- ============================================================================
-- ROLLBACK MANUAL da 066_outbox_foundation.sql
-- ============================================================================
-- NAO faz parte da cadeia de migrations (nao correr via run-migrations.mjs).
-- So para usar manualmente se a 066 for aplicada e precisar de ser revertida.
-- Como domain_mutations/company_change_events estavam vazias antes e depois
-- do ensaio, esta reversao e puramente estrutural - sem perda de dados de
-- negocio em nenhum dos dois sentidos, DESDE QUE ainda estejam vazias no
-- momento da reversao (confirmar com as queries no fim antes de gravar).
--
-- TESTADO em 2026-08-04: dentro de uma unica transacao de ensaio na base
-- real, aplicou-se 066 e de seguida este rollback, e comparou-se o
-- fingerprint (colunas, constraints, grants, IDENTITY, funcoes,
-- company_sync_state) com o estado imediatamente antes da 066. Resultado:
-- identico em tudo, exceto a ORDEM FISICA de 3 colunas em
-- company_change_events (affected_range/delivered_at/created_at) - ADD
-- COLUMN recoloca sempre no fim, sem nenhum efeito funcional (ninguem no
-- codigo depende de ordem de coluna; SELECT * nunca e usado nestas
-- tabelas). Confirmado ROLLBACK dessa transacao de ensaio - nada persistido.

BEGIN;

-- Confirma que ainda esta seguro reverter (aborta se qualquer uma tiver dados)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.domain_mutations LIMIT 1) THEN
    RAISE EXCEPTION 'ROLLBACK_UNSAFE_DOMAIN_MUTATIONS_HAS_DATA' USING ERRCODE = 'P0001';
  END IF;
  IF EXISTS (SELECT 1 FROM public.company_change_events LIMIT 1) THEN
    RAISE EXCEPTION 'ROLLBACK_UNSAFE_COMPANY_CHANGE_EVENTS_HAS_DATA' USING ERRCODE = 'P0001';
  END IF;
END;
$$;

-- 1. Remove company_change_events da publicacao Realtime
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='company_change_events'
  ) THEN
    ALTER PUBLICATION supabase_realtime DROP TABLE public.company_change_events;
  END IF;
END;
$$;

-- 2. record_company_change_event: volta a assinatura antiga (tstzrange) com
--    ON CONFLICT DO UPDATE (comportamento pre-066)
DROP FUNCTION IF EXISTS public.record_company_change_event(uuid, uuid, text, text, uuid[], text[], date, date, jsonb);

CREATE OR REPLACE FUNCTION public.record_company_change_event(
  p_company_id uuid,
  p_mutation_id uuid,
  p_domain text,
  p_event_type text,
  p_entity_ids uuid[],
  p_scopes text[],
  p_affected_range tstzrange DEFAULT NULL::tstzrange,
  p_payload jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_event public.company_change_events;
BEGIN
  INSERT INTO public.company_change_events (
    company_id, mutation_id, domain, event_type, entity_ids, scopes, affected_range, payload
  )
  VALUES (
    p_company_id, p_mutation_id, p_domain, p_event_type,
    COALESCE(p_entity_ids, '{}'), COALESCE(p_scopes, '{}'),
    p_affected_range, COALESCE(p_payload, '{}'::jsonb)
  )
  ON CONFLICT (company_id, mutation_id, domain, event_type)
  DO UPDATE SET payload = EXCLUDED.payload
  RETURNING * INTO v_event;

  RETURN jsonb_build_object('event_id', v_event.id, 'sequence', v_event.sequence);
END;
$$;

-- 3. company_change_events: repõe affected_range/delivered_at, remove
--    affected_from/affected_to, repõe IDENTITY em sequence
ALTER TABLE public.company_change_events ADD COLUMN IF NOT EXISTS affected_range tstzrange;
ALTER TABLE public.company_change_events ADD COLUMN IF NOT EXISTS delivered_at timestamptz;

ALTER TABLE public.company_change_events DROP CONSTRAINT IF EXISTS company_change_events_affected_range_check;
ALTER TABLE public.company_change_events DROP COLUMN IF EXISTS affected_from;
ALTER TABLE public.company_change_events DROP COLUMN IF EXISTS affected_to;

ALTER TABLE public.company_change_events DROP CONSTRAINT IF EXISTS company_change_events_company_id_mutation_id_key;
ALTER TABLE public.company_change_events DROP CONSTRAINT IF EXISTS company_change_events_company_id_sequence_key;
DROP INDEX IF EXISTS public.idx_company_change_events_company_created;

-- Repõe IDENTITY BY DEFAULT na sequence (precisa de estar vazia)
ALTER TABLE public.company_change_events ALTER COLUMN sequence ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.company_change_events ADD CONSTRAINT company_change_events_company_id_mutation_id_domain_event_t_key
  UNIQUE (company_id, mutation_id, domain, event_type);
ALTER TABLE public.company_change_events ADD CONSTRAINT company_change_events_company_id_sequence_key
  UNIQUE (company_id, sequence);

CREATE INDEX IF NOT EXISTS idx_company_change_events_pending
  ON public.company_change_events(company_id, sequence) WHERE (delivered_at IS NULL);

-- Grants: repõe o estado pos-065 (so SELECT para authenticated, nada anon) -
-- a 066 nao alterou isto, mas garantir explicitamente
REVOKE ALL ON public.company_change_events FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.company_change_events TO authenticated;

-- 4. domain_mutations: remove colunas/constraints novas, repõe CHECK antigo
ALTER TABLE public.domain_mutations DROP CONSTRAINT IF EXISTS domain_mutations_operation_format_check;
ALTER TABLE public.domain_mutations DROP CONSTRAINT IF EXISTS domain_mutations_status_check;

ALTER TABLE public.domain_mutations DROP COLUMN IF EXISTS operation;
ALTER TABLE public.domain_mutations DROP COLUMN IF EXISTS entity_id;
ALTER TABLE public.domain_mutations DROP COLUMN IF EXISTS request_hash;
ALTER TABLE public.domain_mutations DROP COLUMN IF EXISTS completed_at;

ALTER TABLE public.domain_mutations ALTER COLUMN status DROP DEFAULT;
ALTER TABLE public.domain_mutations ADD CONSTRAINT domain_mutations_status_check
  CHECK (status = 'completed'::text);

REVOKE ALL ON public.domain_mutations FROM PUBLIC, anon, authenticated;

-- 5. Remove as 3 funções novas (nenhuma tinha chamador)
DROP FUNCTION IF EXISTS public.complete_domain_mutation(uuid, uuid, text, text, uuid, text, text, jsonb);
DROP FUNCTION IF EXISTS public.find_or_conflict_domain_mutation(uuid, uuid, text, text);
DROP FUNCTION IF EXISTS public.lock_domain_mutation(uuid, uuid);
DROP FUNCTION IF EXISTS public.next_company_sequence(uuid);

-- 6. Remove company_sync_state
DROP TABLE IF EXISTS public.company_sync_state;

COMMIT;

-- Verificacao pos-rollback esperada: schema-inventory.mjs deve devolver
-- exatamente o mesmo fingerprint capturado no T03 (2026-08-04), exceto
-- pelas correcoes de grants das migrations 064/065 (essas ficam).
