// ============================================================================
// PISTA CANÓNICA da 101c — a cadeia do repositório chega ao alvo
// ============================================================================
//
// 🔴 O defeito de prova que esta pista fecha.
//
//    A prova operacional da 101c (`status-authorization-101c.pg.test.ts`)
//    monta a forma VIVA — incluindo o drift — através de
//    `pre-101c-authorization-helpers.sql`, uma fixture que FABRICA o preestado.
//    Responde a «funciona sobre o que já lá está?», e a resposta é sim.
//
//    Não responde à outra: «as migrations do repositório constroem as
//    precondições, ou foi a fixture que as pôs lá?». Uma prova que fabrica o
//    preestado de que depende valida-se a si própria.
//
// Aqui não há fixture de drift. A cadeia é a real:
//
//        baseline canónico (forma versionada, PRÉ-drift)
//      + 101 + 101a
//      + 101b   ← já aplicada em produção; aqui tem de CONSTRUIR a identidade
//      + 101c   ← tem de fechar a autorização por estado
//
// `canonical-path-101b.pg.test.ts` e `live-noop-101b.pg.test.ts`, já no master,
// provam a 101b sozinha. Este ficheiro acrescenta o degrau seguinte e não os
// substitui — o que a 101b faz continua a ser medido onde sempre foi.
//
// ----------------------------------------------------------------------------
// Sobre não replicar 001→101a
// ----------------------------------------------------------------------------
//
// O replay completo continua bloqueado por dívida documentada
// (`docs/LEDGER-RECONCILIATION-PENDING.md`). Usa-se o baseline canónico
// validado, como as outras suites — mas sem inserir à mão nada do que as
// migrations devem criar.
// ============================================================================

import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";

const CONTAINER = `canonical-101c-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const OUTRA = "22222222-2222-4222-8222-222222222222";
const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const COLAB = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_101C = "supabase/migrations/101c_status_participa_da_autorizacao.sql";

let container: PostgresContainer;
let pool: pg.Pool;

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

async function comoUtilizador<T>(authUserId: string, fn: (c: pg.Client) => Promise<T>): Promise<T> {
  const c = new pg.Client({ ...container.connection });
  await c.connect();
  try {
    await c.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [authUserId]);
    await c.query("SET ROLE authenticated");
    return await fn(c);
  } finally {
    await c.end().catch(() => { /* já fechada */ });
  }
}

const servicosVisiveis = (authUserId: string) =>
  comoUtilizador(authUserId, async (c) => {
    const { rows } = await c.query("SELECT count(*)::int n FROM public.services");
    return rows[0].n as number;
  });


/** O palco canónico: o que o repositório sabe construir, e nada mais. */
async function baseCanonica(): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);
  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await semear();
}

async function semear(): Promise<void> {
  await pool.query("INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a'),($2,'B','b')", [EMPRESA, OUTRA]);
  await pool.query(
    "INSERT INTO auth.users (id,email) VALUES ($1,'g@a.pt'),($2,'c@a.pt')", [GESTORA, COLAB],
  );
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status) VALUES
      ($1,$2,'Gestora','gestor','ativo'),
      ($3,$2,'Colaboradora','colaborador','ativo')`,
    [GESTORA, EMPRESA, COLAB],
  );
  await pool.query(
    `INSERT INTO public.clients (id,company_id,name)
     VALUES ('c1111111-1111-4111-8111-111111111111',$1,'Cliente A')`, [EMPRESA],
  );
  await pool.query(
    `INSERT INTO public.locations (id,company_id,client_id,name,address)
     VALUES ('10cac111-1111-4111-8111-111111111111',$1,'c1111111-1111-4111-8111-111111111111','Sede','Rua')`,
    [EMPRESA],
  );
  await pool.query(
    `INSERT INTO public.services (id,company_id,location_id,reference_number,scheduled_start,scheduled_end,status)
     VALUES ('5e111111-1111-4111-8111-111111111111',$1,'10cac111-1111-4111-8111-111111111111',
             'S-1', now(), now() + interval '2 hours','agendado')`,
    [EMPRESA],
  );
}

beforeAll(async () => {
  container = await startPostgresContainer({
    name: CONTAINER, database: "canonpath", memory: "512m",
  });
  pool = new pg.Pool({ ...container.connection, max: 6 });
}, 180_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechado */ });
  container?.stop();
});

// ---------------------------------------------------------------------------
describe("101c sobre o que a 101b construiu — não sobre uma fixture", () => {
  async function cadeiaCompleta(): Promise<void> {
    await baseCanonica();
    await pool.query(lerSql(M_101B));
    await pool.query(lerSql(M_101C));
  }

  it("ativo → acesso", LENTO, async () => {
    await cadeiaCompleta();
    expect(await servicosVisiveis(GESTORA)).toBeGreaterThan(0);
  });

  it("🔴 inativo → o mesmo token deixa de ler", LENTO, async () => {
    await cadeiaCompleta();
    expect(await servicosVisiveis(GESTORA)).toBeGreaterThan(0);

    await pool.query("UPDATE public.profiles SET status='inativo' WHERE id=$1", [GESTORA]);
    expect(await servicosVisiveis(GESTORA)).toBe(0);
  });

  it("suspenso → nega", LENTO, async () => {
    await cadeiaCompleta();
    await pool.query("UPDATE public.profiles SET status='suspenso' WHERE id=$1", [GESTORA]);
    expect(await servicosVisiveis(GESTORA)).toBe(0);
  });

  it("desconhecido e nulo → negam", LENTO, async () => {
    await cadeiaCompleta();
    await pool.query("ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_status_check");
    for (const estado of [null, "", "arquivado", "ATIVO"]) {
      await pool.query("UPDATE public.profiles SET status=$2 WHERE id=$1", [GESTORA, estado]);
      expect(await servicosVisiveis(GESTORA), `status=${JSON.stringify(estado)}`).toBe(0);
    }
  });

  it("volta a ativo → devolve o acesso", LENTO, async () => {
    await cadeiaCompleta();
    await pool.query("UPDATE public.profiles SET status='inativo' WHERE id=$1", [GESTORA]);
    expect(await servicosVisiveis(GESTORA)).toBe(0);
    await pool.query("UPDATE public.profiles SET status='ativo' WHERE id=$1", [GESTORA]);
    expect(await servicosVisiveis(GESTORA)).toBeGreaterThan(0);
  });

  it("a ordem inversa não passa — 101c antes de 101b é recusada", LENTO, async () => {
    await baseCanonica();
    await expect(pool.query(lerSql(M_101C))).rejects.toThrow();
  });
});

// ---------------------------------------------------------------------------
describe("o `102` fica livre para o CRM", () => {
  it("nenhuma migration desta frente ocupa 102, 103 ou 104", LENTO, async () => {
    // O cabeçalho da 101a reserva o `102` para as visitas comerciais, e a PR
    // #179 traz 102/103/104. Esta frente usa sufixos entre `101a` e `102`.
    const { readdirSync } = await import("node:fs");
    const nomes = readdirSync(join(process.cwd(), "supabase", "migrations"))
      .filter((f) => f.endsWith(".sql"));

    for (const reservado of ["102_", "103_", "104_"]) {
      expect(
        nomes.filter((n) => n.startsWith(reservado)),
        `${reservado} está reservado ao CRM`,
      ).toEqual([]);
    }

    // E os sufixos desta frente ordenam onde têm de ordenar.
    expect(["101a", "101b", "101c", "102"].slice().sort()).toEqual(["101a", "101b", "101c", "102"]);
  });
});
