// ============================================================================
// 102 — visitas comerciais, sobre a cadeia REAL do master
// ============================================================================
//
// 🔴 O que esta prova existe para responder.
//
//    A 102 foi escrita na PR #179, contra um estado em que só a `101` existia.
//    Desde então o master ganhou a `101a` (ACL das RPC do funil) e a `101b`
//    (canonicalização da identidade, já aplicada em produção).
//
//    A `101b` mudou o que `get_my_company_id()` e `get_my_role()` fazem por
//    dentro: passaram a delegar em `get_my_profile_id()`. A 102 usa as duas nas
//    suas políticas. Reaproveitar a migration antiga sem a medir contra a
//    cadeia nova seria assumir que nada disso lhe toca.
//
//    Por isso o palco aqui é a cadeia como ela está hoje:
//
//        baseline canónico + 101 + 101a + 101b  →  102
//
//    E NÃO inclui a 101c. Provar que a 102 não depende dela é parte do
//    trabalho: o endurecimento por `status` seguiu para outra frente, e o CRM
//    não pode ficar refém disso.
// ============================================================================

import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";

const CONTAINER = `crm102-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const OUTRA = "22222222-2222-4222-8222-222222222222";
const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const GESTORA_OUTRA = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const COLAB = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
const CLIENTE_A = "c1111111-1111-4111-8111-111111111111";
const CLIENTE_B = "c2222222-2222-4222-8222-222222222222";

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_102 = "supabase/migrations/102_crm_visitas_comerciais.sql";
const ROLLBACK_102 = "supabase/migrations/rollback/102_crm_visitas_comerciais.down.sql";

let container: PostgresContainer;
let pool: pg.Pool;

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

/** Uma ligação com a identidade de quem faz o pedido, como o PostgREST a faz. */
async function comoUtilizador<T>(
  authUserId: string,
  fn: (c: pg.Client) => Promise<T>,
): Promise<T> {
  const c = new pg.Client({ ...container.connection });
  await c.connect();
  try {
    await c.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [authUserId]);
    await c.query("SET ROLE authenticated");
    return await fn(c);
  } finally {
    await c.end().catch(() => { /* já fechada */ });
  }
}

async function comoServiceRole<T>(fn: (c: pg.Client) => Promise<T>): Promise<T> {
  const c = new pg.Client({ ...container.connection });
  await c.connect();
  try {
    await c.query("SET ROLE service_role");
    return await fn(c);
  } finally {
    await c.end().catch(() => { /* já fechada */ });
  }
}

/** A cadeia do master: 101 → 101a → 101b. Sem 101c, de propósito. */
async function cadeiaDoMaster(aplicar102: boolean): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);
  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await pool.query(lerSql(M_101B));
  await semear();
  if (aplicar102) await pool.query(lerSql(M_102));
}

async function semear(): Promise<void> {
  await pool.query(
    "INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a'),($2,'B','b')",
    [EMPRESA, OUTRA],
  );
  await pool.query(
    `INSERT INTO auth.users (id,email) VALUES ($1,'g@a.pt'),($2,'g@b.pt'),($3,'c@a.pt')`,
    [GESTORA, GESTORA_OUTRA, COLAB],
  );
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id) VALUES
      ($1,$2,'Gestora A','gestor','ativo',$1),
      ($3,$4,'Gestora B','gestor','ativo',$3),
      ($5,$2,'Colaboradora','colaborador','ativo',$5)`,
    [GESTORA, EMPRESA, GESTORA_OUTRA, OUTRA, COLAB],
  );
  await pool.query(
    `INSERT INTO public.clients (id,company_id,name)
     VALUES ($1,$2,'Cliente A'), ($3,$4,'Cliente B')`,
    [CLIENTE_A, EMPRESA, CLIENTE_B, OUTRA],
  );
}

/** Cria uma visita por `service_role`, como as Server Actions fazem. */
async function novaVisita(over: Record<string, unknown> = {}): Promise<string> {
  const inicio = new Date();
  const campos: Record<string, unknown> = {
    company_id: EMPRESA,
    client_id: CLIENTE_A,
    scheduled_start: inicio.toISOString(),
    // `scheduled_end` é NOT NULL: uma visita sem fim não é agenda, é intenção.
    scheduled_end: new Date(inicio.getTime() + 60 * 60 * 1000).toISOString(),
    created_by: GESTORA,
    ...over,
  };
  const colunas = Object.keys(campos);
  const marcas = colunas.map((_, i) => `$${i + 1}`).join(", ");
  const { rows } = await pool.query(
    `INSERT INTO public.crm_visits (${colunas.join(", ")}) VALUES (${marcas}) RETURNING id`,
    Object.values(campos),
  );
  return rows[0].id as string;
}

beforeAll(async () => {
  container = await startPostgresContainer({
    name: CONTAINER, database: "crm102", memory: "512m",
  });
  pool = new pg.Pool({ ...container.connection, max: 6 });
}, 180_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechado */ });
  container?.stop();
});

// ---------------------------------------------------------------------------
describe("a 102 corre sobre a cadeia actual do master", () => {
  it("aplica sobre 101 + 101a + 101b", LENTO, async () => {
    await cadeiaDoMaster(true);
    const { rows } = await pool.query("SELECT to_regclass('public.crm_visits') AS t");
    expect(rows[0].t).toBe("crm_visits");
  });

  it("🔴 não depende da 101c — que nem sequer está aplicada aqui", LENTO, async () => {
    await cadeiaDoMaster(true);

    // A 101c muda `get_my_profile_id()` para exigir `status = 'ativo'`. Se a
    // 102 dependesse disso, este palco não a teria feito correr — e não tem.
    const { rows } = await pool.query(`
      SELECT position('status' in pg_get_functiondef(p.oid)) AS tem_status
        FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
       WHERE n.nspname='public' AND p.proname='get_my_profile_id'`);
    expect(rows[0].tem_status).toBe(0);

    // E a tabela funciona na mesma.
    const id = await novaVisita();
    expect(id).toBeTruthy();
  });

  it("as precondições recusam se a 101 não tiver corrido", LENTO, async () => {
    await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
    await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
    await pool.query(baselineCompleto());
    await expect(pool.query(lerSql(M_102))).rejects.toThrow(/PRECONDITION_FAILED|crm_leads/i);
  });
});

// ---------------------------------------------------------------------------
describe("integridade com o 101 e com profiles", () => {
  beforeEach(async () => { await cadeiaDoMaster(true); }, 120_000);

  it("uma visita pode nascer sem lead — a agenda não exige funil", LENTO, async () => {
    const id = await novaVisita();
    const { rows } = await pool.query("SELECT lead_id FROM public.crm_visits WHERE id=$1", [id]);
    expect(rows[0].lead_id).toBeNull();
  });

  it("ligada a uma lead, segue-a quando ela desaparece", LENTO, async () => {
    const { rows: l } = await pool.query(
      "INSERT INTO public.crm_leads (company_id, name) VALUES ($1,'Condomínio') RETURNING id",
      [EMPRESA],
    );
    const lead = l[0].id as string;
    // `crm_visits_um_destinatario`: uma visita é a UMA lead ou a UM cliente,
    // nunca às duas. É o que impede uma visita com dois donos.
    await novaVisita({ lead_id: lead, client_id: null });

    await pool.query("DELETE FROM public.crm_leads WHERE id=$1", [lead]);
    const { rows } = await pool.query("SELECT count(*)::int n FROM public.crm_visits");
    // `ON DELETE CASCADE`: a visita pertence à lead.
    expect(rows[0].n).toBe(0);
  });

  it("🔴 o cliente NÃO é apagado por arrasto de uma visita", LENTO, async () => {
    await novaVisita();
    // `ON DELETE RESTRICT`: um cliente com visitas não desaparece em silêncio.
    await expect(
      pool.query("DELETE FROM public.clients WHERE id=$1", [CLIENTE_A]),
    ).rejects.toThrow();
  });

  it("🔴 um perfil responsável por visitas não pode ser apagado", LENTO, async () => {
    await novaVisita({ assigned_to: COLAB });
    // `ON DELETE NO ACTION` — a autoria não se perde para caber num DELETE.
    await expect(
      pool.query("DELETE FROM public.profiles WHERE id=$1", [COLAB]),
    ).rejects.toThrow();
  });

  it("quem marcou também segura o perfil", LENTO, async () => {
    await novaVisita({ created_by: GESTORA });
    await expect(
      pool.query("DELETE FROM public.profiles WHERE id=$1", [GESTORA]),
    ).rejects.toThrow();
  });
});

// ---------------------------------------------------------------------------
describe("isolamento por empresa", () => {
  beforeEach(async () => { await cadeiaDoMaster(true); }, 120_000);

  it("🔴 a FK composta recusa um responsável de outra empresa", LENTO, async () => {
    await expect(
      novaVisita({ assigned_to: GESTORA_OUTRA }),
    ).rejects.toThrow();
  });

  it("recusa um cliente de outra empresa", LENTO, async () => {
    await expect(novaVisita({ client_id: CLIENTE_B })).rejects.toThrow();
  });

  it("recusa uma lead de outra empresa", LENTO, async () => {
    const { rows } = await pool.query(
      "INSERT INTO public.crm_leads (company_id, name) VALUES ($1,'Da B') RETURNING id",
      [OUTRA],
    );
    await expect(novaVisita({ lead_id: rows[0].id, client_id: null })).rejects.toThrow();
  });

  it("🔴 a gestora da outra empresa não vê estas visitas", LENTO, async () => {
    await novaVisita();
    const vistas = await comoUtilizador(GESTORA_OUTRA, async (c) => {
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_visits");
      return rows[0].n as number;
    });
    expect(vistas).toBe(0);
  });
});

// ---------------------------------------------------------------------------
describe("permissões", () => {
  beforeEach(async () => { await cadeiaDoMaster(true); }, 120_000);

  it("a gestora da empresa vê as suas visitas", LENTO, async () => {
    await novaVisita();
    const vistas = await comoUtilizador(GESTORA, async (c) => {
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_visits");
      return rows[0].n as number;
    });
    expect(vistas).toBe(1);
  });

  it("🔴 uma colaboradora não vê a agenda comercial", LENTO, async () => {
    await novaVisita();
    const vistas = await comoUtilizador(COLAB, async (c) => {
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_visits");
      return rows[0].n as number;
    });
    expect(vistas).toBe(0);
  });

  it("🔴 `authenticated` não escreve directamente — só lê", LENTO, async () => {
    // O modelo endurecido pós-084/085: as escritas passam todas por
    // `service_role`, nas Server Actions. Um cliente com sessão não insere.
    await comoUtilizador(GESTORA, async (c) => {
      await expect(
        c.query(
          `INSERT INTO public.crm_visits (company_id, client_id, scheduled_start, scheduled_end)
           VALUES ($1,$2,now(),now() + interval '1 hour')`,
          [EMPRESA, CLIENTE_A],
        ),
      ).rejects.toThrow(/permission denied/i);
    });
  });

  it("`anon` não chega à tabela", LENTO, async () => {
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("SET ROLE anon");
      await expect(
        c.query("SELECT count(*) FROM public.crm_visits"),
      ).rejects.toThrow(/permission denied/i);
    } finally {
      await c.end();
    }
  });

  it("`service_role` escreve — é por lá que a aplicação trabalha", LENTO, async () => {
    const escreveu = await comoServiceRole(async (c) => {
      const { rows } = await c.query(
        `INSERT INTO public.crm_visits (company_id, client_id, scheduled_start, scheduled_end, created_by)
         VALUES ($1,$2,now(),now() + interval '1 hour',$3) RETURNING id`,
        [EMPRESA, CLIENTE_A, GESTORA],
      );
      return rows[0].id as string;
    });
    expect(escreveu).toBeTruthy();
  });
});

// ---------------------------------------------------------------------------
describe("rollback", () => {
  it("desfaz a 102 e deixa a 101 de pé", LENTO, async () => {
    await cadeiaDoMaster(true);
    await novaVisita();

    await pool.query(lerSql(ROLLBACK_102));

    const { rows } = await pool.query(`
      SELECT to_regclass('public.crm_visits') AS visitas,
             to_regclass('public.crm_leads')  AS leads`);
    expect(rows[0].visitas).toBeNull();
    // 🔴 O funil não pode ir atrás: a 101 está aplicada em produção.
    expect(rows[0].leads).toBe("crm_leads");
  });

  it("e a 102 volta a aplicar-se depois do rollback", LENTO, async () => {
    await cadeiaDoMaster(true);
    await pool.query(lerSql(ROLLBACK_102));
    await pool.query(lerSql(M_102));

    const { rows } = await pool.query("SELECT to_regclass('public.crm_visits') AS t");
    expect(rows[0].t).toBe("crm_visits");
  });
});

// ---------------------------------------------------------------------------
describe("o namespace", () => {
  it("a 102 é do CRM, e a frente de colaboradores usou sufixos", LENTO, async () => {
    const { readdirSync } = await import("node:fs");
    const nomes = readdirSync(join(process.cwd(), "supabase", "migrations"))
      .filter((f) => f.endsWith(".sql"));

    expect(nomes).toContain("102_crm_visitas_comerciais.sql");
    // `101b` e `101c` existem para NÃO terem roubado este número.
    expect(nomes.filter((n) => /^102[a-z]?_/.test(n))).toEqual([
      "102_crm_visitas_comerciais.sql",
    ]);
  });
});
