// ============================================================================
// 108 — ganhar uma lead associando-a a um cliente que já existe
// ============================================================================
//
// 🔴 O palco é a cadeia como está EM PRODUÇÃO hoje:
//
//        baseline canónico + 101 + 101a + 101b + 102 + 103 + 103a + 104  →  108
//
// O que importa provar contra Postgres real:
//
//   · nenhum cliente novo nasce, e o cliente escolhido NÃO é alterado;
//   · o local é um do cliente, ou um novo com as regras de morada da 104;
//   · um local de outro cliente, um cliente de outra empresa, um local
//     inactivo — recusados, e sem vestígio nenhum;
//   · repetir é idempotente; repetir com outro cliente é recusado;
//   · duas associações simultâneas criam UM local;
//   · ACL e search_path como a 104, com o pós-estado a falhar fechado.
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";

const CONTAINER = `crm108-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const OUTRA = "22222222-2222-4222-8222-222222222222";
const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const GESTORA_OUTRA = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const CLIENTE_A = "c1111111-1111-4111-8111-111111111111";
const CLIENTE_B = "c2222222-2222-4222-8222-222222222222"; // da OUTRA empresa
const CLIENTE_A2 = "c3333333-3333-4333-8333-333333333333"; // outro cliente da mesma empresa

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_102 = "supabase/migrations/102_crm_visitas_comerciais.sql";
const M_103 = "supabase/migrations/103_crm_orcamentos.sql";
const M_103A = "supabase/migrations/103a_crm_rpc_acl_hardening.sql";
const M_104 = "supabase/migrations/104_crm_conversao_lead.sql";
const M_108 = "supabase/migrations/108_crm_associar_cliente_existente.sql";
const ROLLBACK_108 = "supabase/migrations/rollback/108_crm_associar_cliente_existente.down.sql";

const NOME_102 = "102_crm_visitas_comerciais.sql";
const NOME_103 = "103_crm_orcamentos.sql";
const NOME_103A = "103a_crm_rpc_acl_hardening.sql";
const NOME_104 = "104_crm_conversao_lead.sql";
const NOME_108 = "108_crm_associar_cliente_existente.sql";

const CADEIA = [
  "101_crm_leads.sql",
  "101a_crm_rpc_acl_hardening.sql",
  "101b_identity_reconciliation.sql",
] as const;

const ASSINATURA = "public.link_crm_lead_to_existing_client(uuid, uuid, uuid, uuid, uuid, uuid)";
const ANO = 2026;

let container: PostgresContainer;
let pool: pg.Pool;
let leadA = "";

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

const checksumLf = (ficheiro: string): string =>
  createHash("sha256")
    .update(lerSql(`supabase/migrations/${ficheiro}`).split("\r\n").join("\n").split("\r").join("\n"))
    .digest("hex");

async function registarNoLedger(nome: string): Promise<void> {
  await pool.query(
    `INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)
     ON CONFLICT (name) DO UPDATE SET checksum = EXCLUDED.checksum`,
    [nome, checksumLf(nome)],
  );
}

/** A cadeia real até à 104. `aplicar108` fecha o palco com a migration em prova. */
async function palco(aplicar108 = true): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);
  // O default privilege que obriga a revogar `anon`/`authenticated` à mão.
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);

  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await pool.query(lerSql(M_101B));

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public._migrations (
      name text PRIMARY KEY, checksum text, applied_at timestamptz NOT NULL DEFAULT now())`);
  for (const nome of CADEIA) await registarNoLedger(nome);

  await pool.query(lerSql(M_102));
  await registarNoLedger(NOME_102);

  await semear();

  await pool.query(lerSql(M_103));
  await registarNoLedger(NOME_103);
  await pool.query(lerSql(M_103A));
  await registarNoLedger(NOME_103A);
  await pool.query(lerSql(M_104));
  await registarNoLedger(NOME_104);

  if (aplicar108) {
    await pool.query(lerSql(M_108));
    await registarNoLedger(NOME_108);
  }
}

async function semear(): Promise<void> {
  await pool.query("INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a'),($2,'B','b')",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO public.company_settings (company_id) VALUES ($1),($2)",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO auth.users (id,email) VALUES ($1,'g@a.pt'),($2,'g@b.pt')",
    [GESTORA, GESTORA_OUTRA]);
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id) VALUES
      ($1,$2,'Gestora A','gestor','ativo',$1),
      ($3,$4,'Gestora B','gestor','ativo',$3)`,
    [GESTORA, EMPRESA, GESTORA_OUTRA, OUTRA],
  );
  // 🔴 O cliente A tem dados PRÓPRIOS, diferentes dos da lead — é isso que
  //    prova que a associação não os sobrescreve.
  await pool.query(
    `INSERT INTO public.clients (id,company_id,name,nif,email,phone,status) VALUES
      ($1,$2,'Cliente A','509999999','cliente@a.pt','211111111','ativo'),
      ($3,$4,'Cliente B',NULL,NULL,NULL,'ativo'),
      ($5,$2,'Cliente A2',NULL,NULL,NULL,'ativo')`,
    [CLIENTE_A, EMPRESA, CLIENTE_B, OUTRA, CLIENTE_A2],
  );
}

async function novaLead(over: Record<string, unknown> = {}): Promise<string> {
  const campos = {
    name: "Condomínio Alfa",
    lead_type: "empresa",
    email: "geral@alfa.pt",
    phone: "912345678",
    nif: "500123456",
    address: "Rua da Lead 1, Lisboa",
    lat: 38.7223,
    lng: -9.1393,
    service_type: "manutencao",
    ...over,
  };
  const { rows } = await pool.query(
    `INSERT INTO public.crm_leads
       (company_id, name, lead_type, email, phone, nif, address, lat, lng, service_type)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,
    [
      EMPRESA, campos.name, campos.lead_type, campos.email, campos.phone, campos.nif,
      campos.address, campos.lat, campos.lng, campos.service_type,
    ],
  );
  return rows[0].id as string;
}

async function novaVisita(leadId: string, address: string | null): Promise<string> {
  const { rows } = await pool.query(
    `INSERT INTO public.crm_visits (company_id, lead_id, scheduled_start, scheduled_end, address, lat, lng)
     VALUES ($1,$2, now(), now() + interval '1 hour', $3, 41.15, -8.61) RETURNING id`,
    [EMPRESA, leadId, address],
  );
  return rows[0].id as string;
}

async function novoOrcamento(leadId: string, opts: {
  visitId?: string | null; estado?: string;
} = {}): Promise<{ id: string; numero: string }> {
  const { rows } = await pool.query(
    `SELECT * FROM public.create_crm_quote_with_items(
       $1,$2,NULL,$3,'ORC',$4,CURRENT_DATE,CURRENT_DATE + 30,
       'pontual',0,true,23,NULL,NULL,NULL,NULL,NULL,$5,$6::jsonb)`,
    [
      EMPRESA, leadId, opts.visitId ?? null, ANO, GESTORA,
      JSON.stringify([{ description: "Limpeza", quantity: 1, unit: "servico", unit_price: 100 }]),
    ],
  );
  const id = rows[0].quote_id as string;
  const numero = rows[0].quote_number as string;

  const estado = opts.estado ?? "aceite";
  if (estado !== "rascunho") {
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)", [EMPRESA, id, GESTORA]);
    if (estado !== "enviado") {
      await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,$4,NULL)", [EMPRESA, id, GESTORA, estado]);
    }
  }
  return { id, numero };
}

async function novoLocal(clientId: string, over: { active?: boolean; empresa?: string } = {}) {
  const { rows } = await pool.query(
    `INSERT INTO public.locations (company_id, client_id, name, address, active)
     VALUES ($1,$2,'Sede','Avenida do Cliente 5',$3) RETURNING id`,
    [over.empresa ?? EMPRESA, clientId, over.active ?? true],
  );
  return rows[0].id as string;
}

async function associar(
  leadId: string,
  quoteId: string | null,
  clientId: string | null,
  locationId: string | null = null,
): Promise<{ client_id: string; location_id: string; ja_convertida: boolean }> {
  const { rows } = await pool.query(
    "SELECT * FROM public.link_crm_lead_to_existing_client($1,$2,$3,$4,$5,$6)",
    [EMPRESA, leadId, GESTORA, quoteId, clientId, locationId],
  );
  return rows[0];
}

/** Tudo o que uma recusa não pode ter mexido. */
async function fotografia(leadId: string, quoteId: string) {
  const { rows } = await pool.query(`
    SELECT (SELECT count(*)::int FROM public.clients) AS clients,
           (SELECT count(*)::int FROM public.locations) AS locations,
           (SELECT count(*)::int FROM public.crm_lead_interactions) AS interactions,
           (SELECT row_to_json(l) FROM (SELECT stage, won_at, converted_client_id, converted_location_id
                                          FROM public.crm_leads WHERE id = $1) l) AS lead,
           (SELECT row_to_json(q) FROM (SELECT lead_id, client_id, status
                                          FROM public.crm_quotes WHERE id = $2) q) AS quote`,
    [leadId, quoteId]);
  return rows[0];
}

async function ligacao(): Promise<pg.Client> {
  const c = new pg.Client({ ...container.connection });
  await c.connect();
  return c;
}

async function limpar(): Promise<void> {
  await pool.query("DELETE FROM public.crm_lead_interactions");
  await pool.query("DELETE FROM public.crm_quote_items");
  await pool.query("DELETE FROM public.crm_quotes");
  await pool.query("DELETE FROM public.crm_visits");
  await pool.query("DELETE FROM public.crm_leads");
  await pool.query("DELETE FROM public.locations");
  await pool.query("DELETE FROM public.clients WHERE id NOT IN ($1,$2,$3)",
    [CLIENTE_A, CLIENTE_B, CLIENTE_A2]);
}

beforeAll(async () => {
  container = await startPostgresContainer({ name: CONTAINER, database: "crm108", memory: "512m" });
  pool = new pg.Pool({ ...container.connection, max: 8 });
  await palco();
}, 240_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechado */ });
  container?.stop();
});

beforeEach(async () => {
  await limpar();
  leadA = await novaLead();
});

// ───────────────────────────────────────────────────────────────────────────
describe("1. associação nominal — local novo", () => {
  it("🔴 não cria cliente, cria UM local do cliente escolhido e fecha a lead", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const antes = await fotografia(leadA, q.id);

    const r = await associar(leadA, q.id, CLIENTE_A);

    expect(r).toMatchObject({ client_id: CLIENTE_A, ja_convertida: false });
    const depois = await fotografia(leadA, q.id);
    expect(depois.clients).toBe(antes.clients);
    expect(depois.locations).toBe(antes.locations + 1);
    expect(depois.interactions).toBe(antes.interactions + 1);

    const { rows: local } = await pool.query(
      "SELECT client_id, company_id, address, service_type, active, hourly_rate, name FROM public.locations WHERE id = $1",
      [r.location_id]);
    expect(local[0]).toMatchObject({
      client_id: CLIENTE_A,
      company_id: EMPRESA,
      address: "Rua da Lead 1, Lisboa",
      service_type: "manutencao",
      active: true,
      hourly_rate: null,
      name: "Condomínio Alfa",
    });

    expect(depois.lead).toMatchObject({
      stage: "ganho",
      converted_client_id: CLIENTE_A,
      converted_location_id: r.location_id,
    });
    expect(depois.lead.won_at).not.toBeNull();
    expect(depois.quote).toMatchObject({ lead_id: null, client_id: CLIENTE_A, status: "aceite" });
  });

  it("🔴 o cliente escolhido NÃO é alterado pelos dados da lead", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await associar(leadA, q.id, CLIENTE_A);

    const { rows } = await pool.query(
      "SELECT name, nif, email, phone, status FROM public.clients WHERE id = $1", [CLIENTE_A]);
    expect(rows[0]).toEqual({
      name: "Cliente A", nif: "509999999", email: "cliente@a.pt", phone: "211111111", status: "ativo",
    });
  });

  it("a timeline diz a que cliente foi associada e de que orçamento", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await associar(leadA, q.id, CLIENTE_A);

    const { rows } = await pool.query(
      "SELECT kind, summary, author_id FROM public.crm_lead_interactions WHERE lead_id = $1", [leadA]);
    expect(rows).toHaveLength(1);
    expect(rows[0].kind).toBe("sistema");
    expect(rows[0].summary).toBe(`Lead associada ao cliente existente «Cliente A» a partir do orçamento ${q.numero}.`);
    expect(rows[0].author_id).toBe(GESTORA);
  });

  it("a morada da visita ganha à da lead, como na 104", LENTO, async () => {
    const visita = await novaVisita(leadA, "Rua da Visita 99, Porto");
    const q = await novoOrcamento(leadA, { visitId: visita });
    const r = await associar(leadA, q.id, CLIENTE_A);

    const { rows } = await pool.query(
      "SELECT address, lat, lng FROM public.locations WHERE id = $1", [r.location_id]);
    expect(rows[0].address).toBe("Rua da Visita 99, Porto");
    expect(Number(rows[0].lat)).toBeCloseTo(41.15, 4);
  });

  it("uma lead perdida fica coerente ao ganhar", LENTO, async () => {
    await pool.query(
      `UPDATE public.crm_leads SET stage = 'perdido', lost_at = now(), lost_reason = 'preco'
        WHERE id = $1`, [leadA]);
    const q = await novoOrcamento(leadA);
    await associar(leadA, q.id, CLIENTE_A);

    const { rows } = await pool.query(
      "SELECT stage, lost_at, lost_reason FROM public.crm_leads WHERE id = $1", [leadA]);
    expect(rows[0]).toEqual({ stage: "ganho", lost_at: null, lost_reason: null });
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("2. associação a um local que o cliente já tem", () => {
  it("🔴 reaproveita o local: zero clientes e zero locais novos", LENTO, async () => {
    const sede = await novoLocal(CLIENTE_A);
    const q = await novoOrcamento(leadA);
    const antes = await fotografia(leadA, q.id);

    const r = await associar(leadA, q.id, CLIENTE_A, sede);

    expect(r).toMatchObject({ client_id: CLIENTE_A, location_id: sede, ja_convertida: false });
    const depois = await fotografia(leadA, q.id);
    expect(depois.clients).toBe(antes.clients);
    expect(depois.locations).toBe(antes.locations);
    expect(depois.lead.converted_location_id).toBe(sede);

    // O local também não é alterado.
    const { rows } = await pool.query(
      "SELECT name, address FROM public.locations WHERE id = $1", [sede]);
    expect(rows[0]).toEqual({ name: "Sede", address: "Avenida do Cliente 5" });
  });

  it("com local escolhido, a lead pode não ter morada", LENTO, async () => {
    const semMorada = await novaLead({ address: null, lat: null, lng: null });
    const sede = await novoLocal(CLIENTE_A);
    const q = await novoOrcamento(semMorada);

    const r = await associar(semMorada, q.id, CLIENTE_A, sede);
    expect(r.location_id).toBe(sede);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("3. o que a RPC recusa — sempre sem vestígios", () => {
  async function recusa(
    erro: RegExp,
    preparar: () => Promise<{ lead: string; quote: string; cliente: string | null; local?: string | null }>,
  ) {
    const p = await preparar();
    const antes = await fotografia(p.lead, p.quote);
    await expect(associar(p.lead, p.quote, p.cliente, p.local ?? null)).rejects.toThrow(erro);
    expect(await fotografia(p.lead, p.quote)).toEqual(antes);
  }

  it("🔴 cliente de OUTRA empresa → LINK_CLIENT_NOT_FOUND", LENTO, () =>
    recusa(/LINK_CLIENT_NOT_FOUND/, async () => {
      const q = await novoOrcamento(leadA);
      return { lead: leadA, quote: q.id, cliente: CLIENTE_B };
    }));

  it("cliente que não existe → LINK_CLIENT_NOT_FOUND", LENTO, () =>
    recusa(/LINK_CLIENT_NOT_FOUND/, async () => {
      const q = await novoOrcamento(leadA);
      return { lead: leadA, quote: q.id, cliente: "c9999999-9999-4999-8999-999999999999" };
    }));

  it("sem cliente → LINK_CLIENT_REQUIRED", LENTO, () =>
    recusa(/LINK_CLIENT_REQUIRED/, async () => {
      const q = await novoOrcamento(leadA);
      return { lead: leadA, quote: q.id, cliente: null };
    }));

  it("🔴 local de OUTRO cliente → LINK_LOCATION_CLIENT_MISMATCH", LENTO, () =>
    recusa(/LINK_LOCATION_CLIENT_MISMATCH/, async () => {
      const deOutro = await novoLocal(CLIENTE_A2);
      const q = await novoOrcamento(leadA);
      return { lead: leadA, quote: q.id, cliente: CLIENTE_A, local: deOutro };
    }));

  it("🔴 local de outra empresa → LINK_LOCATION_NOT_FOUND", LENTO, () =>
    recusa(/LINK_LOCATION_NOT_FOUND/, async () => {
      const alheio = await novoLocal(CLIENTE_B, { empresa: OUTRA });
      const q = await novoOrcamento(leadA);
      return { lead: leadA, quote: q.id, cliente: CLIENTE_A, local: alheio };
    }));

  it("local desactivado → LINK_LOCATION_INACTIVE", LENTO, () =>
    recusa(/LINK_LOCATION_INACTIVE/, async () => {
      const inactivo = await novoLocal(CLIENTE_A, { active: false });
      const q = await novoOrcamento(leadA);
      return { lead: leadA, quote: q.id, cliente: CLIENTE_A, local: inactivo };
    }));

  it("orçamento só enviado → QUOTE_NOT_ACCEPTED", LENTO, () =>
    recusa(/QUOTE_NOT_ACCEPTED/, async () => {
      const q = await novoOrcamento(leadA, { estado: "enviado" });
      return { lead: leadA, quote: q.id, cliente: CLIENTE_A };
    }));

  it("orçamento de outra lead → QUOTE_LEAD_MISMATCH", LENTO, () =>
    recusa(/QUOTE_LEAD_MISMATCH/, async () => {
      const outra = await novaLead({ name: "Outra" });
      const q = await novoOrcamento(outra);
      return { lead: leadA, quote: q.id, cliente: CLIENTE_A };
    }));

  it("sem morada e sem local escolhido → CONVERSION_ADDRESS_REQUIRED", LENTO, () =>
    recusa(/CONVERSION_ADDRESS_REQUIRED/, async () => {
      const semMorada = await novaLead({ address: null, lat: null, lng: null });
      const q = await novoOrcamento(semMorada);
      return { lead: semMorada, quote: q.id, cliente: CLIENTE_A };
    }));

  it("actor de outra empresa → ACTOR_NOT_IN_COMPANY", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const antes = await fotografia(leadA, q.id);
    await expect(pool.query(
      "SELECT * FROM public.link_crm_lead_to_existing_client($1,$2,$3,$4,$5,NULL)",
      [EMPRESA, leadA, GESTORA_OUTRA, q.id, CLIENTE_A],
    )).rejects.toThrow(/ACTOR_NOT_IN_COMPANY/);
    expect(await fotografia(leadA, q.id)).toEqual(antes);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("4. idempotência e decisões já tomadas", () => {
  it("repetir devolve os mesmos ids e não cria nada", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const primeira = await associar(leadA, q.id, CLIENTE_A);
    const antes = await fotografia(leadA, q.id);

    const segunda = await associar(leadA, q.id, CLIENTE_A);
    expect(segunda).toEqual({ ...primeira, ja_convertida: true });
    expect(await fotografia(leadA, q.id)).toEqual(antes);
  });

  it("🔴 repetir com OUTRO cliente → LEAD_ALREADY_CONVERTED, nada muda", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await associar(leadA, q.id, CLIENTE_A);
    const antes = await fotografia(leadA, q.id);

    await expect(associar(leadA, q.id, CLIENTE_A2)).rejects.toThrow(/LEAD_ALREADY_CONVERTED/);
    expect(await fotografia(leadA, q.id)).toEqual(antes);
  });

  it("🔴 lead já convertida pela 104 (cliente novo) → LEAD_ALREADY_CONVERTED", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await pool.query("SELECT * FROM public.convert_crm_lead_atomic($1,$2,$3,$4)",
      [EMPRESA, leadA, GESTORA, q.id]);
    const antes = await fotografia(leadA, q.id);

    await expect(associar(leadA, q.id, CLIENTE_A)).rejects.toThrow(/LEAD_ALREADY_CONVERTED/);
    expect(await fotografia(leadA, q.id)).toEqual(antes);
  });

  it("a 104 repetida depois da 108 responde idempotente com o cliente existente", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const r = await associar(leadA, q.id, CLIENTE_A);

    const { rows } = await pool.query("SELECT * FROM public.convert_crm_lead_atomic($1,$2,$3,$4)",
      [EMPRESA, leadA, GESTORA, q.id]);
    expect(rows[0]).toEqual({ client_id: CLIENTE_A, location_id: r.location_id, ja_convertida: true });
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("5. concorrência", () => {
  it("🔴 duas associações simultâneas: UM local, e a segunda é idempotente", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const c1 = await ligacao();
    const c2 = await ligacao();

    try {
      await c1.query("BEGIN");
      await c2.query("BEGIN");

      const sql = "SELECT * FROM public.link_crm_lead_to_existing_client($1,$2,$3,$4,$5,NULL)";
      const args = [EMPRESA, leadA, GESTORA, q.id, CLIENTE_A];

      // 🔴 A sobreposição é FORÇADA, não esperada por um `setTimeout`.
      //
      //    Uma primeira versão lançava a segunda chamada 120 ms depois da
      //    primeira. A primeira acabava em milissegundos e fazia commit logo
      //    a seguir — a segunda já lia a lead convertida e o ensaio passava
      //    mesmo com o `FOR UPDATE` da lead removido (provado por mutação).
      //    Um ensaio de concorrência que passa sem o lock não prova o lock.
      //
      //    Agora: c1 corre tudo e fica com a transação ABERTA; c2 arranca e só
      //    se faz o commit de c1 quando o Postgres confirma que c2 está parada
      //    à espera de um lock. Sem o lock da lead, c2 leria a lead ainda por
      //    converter, pararia no orçamento, e acabaria em erro.
      const r1 = await c1.query(sql, args);
      const { rows: pid } = await c2.query("SELECT pg_backend_pid() AS pid");
      const p2 = c2.query(sql, args);

      let bloqueada = false;
      for (let i = 0; i < 200 && !bloqueada; i++) {
        const { rows } = await pool.query(
          "SELECT wait_event_type FROM pg_stat_activity WHERE pid = $1", [pid[0].pid]);
        bloqueada = rows[0]?.wait_event_type === "Lock";
        if (!bloqueada) await new Promise((r) => setTimeout(r, 10));
      }
      expect(bloqueada, "c2 nunca ficou à espera de um lock").toBe(true);

      await c1.query("COMMIT");
      const r2 = await p2;
      await c2.query("COMMIT");

      expect(r1.rows[0].ja_convertida).toBe(false);
      expect(r2.rows[0]).toEqual({ ...r1.rows[0], ja_convertida: true });

      const { rows } = await pool.query("SELECT count(*)::int AS n FROM public.locations");
      expect(rows[0].n).toBe(1);
    } finally {
      await c1.end().catch(() => {});
      await c2.end().catch(() => {});
    }
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("6. segurança da RPC", () => {
  it("🔴 ACL: só o owner e service_role, sem WITH GRANT OPTION", LENTO, async () => {
    const { rows } = await pool.query(`
      SELECT
        (SELECT array_agg(DISTINCT acl.grantee::regrole::text ORDER BY acl.grantee::regrole::text)
           FROM aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) AS acl
          WHERE acl.privilege_type = 'EXECUTE') AS grantees,
        (SELECT bool_or(acl.is_grantable)
           FROM aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) AS acl
          WHERE acl.privilege_type = 'EXECUTE') AS grantable,
        p.proowner::regrole::text AS owner,
        p.prosecdef, p.proconfig
        FROM pg_proc p
       WHERE p.oid = '${ASSINATURA}'::regprocedure`);

    const { grantees, grantable, owner, prosecdef, proconfig } = rows[0];
    expect([...grantees].sort()).toEqual([owner, "service_role"].sort());
    expect(grantable ?? false).toBe(false);
    expect(prosecdef).toBe(false);
    expect(proconfig).toContain("search_path=pg_catalog, public");
  });

  it("🔴 anon e authenticated NÃO executam", LENTO, async () => {
    const { rows } = await pool.query(`
      SELECT has_function_privilege('anon', '${ASSINATURA}', 'EXECUTE') AS anon,
             has_function_privilege('authenticated', '${ASSINATURA}', 'EXECUTE') AS auth,
             has_function_privilege('service_role', '${ASSINATURA}', 'EXECUTE') AS srv`);
    expect(rows[0]).toEqual({ anon: false, auth: false, srv: true });
  });

  const sabotagens: Array<{ nome: string; de: string; para: string }> = [
    { nome: "REVOKE só de PUBLIC", de: "  FROM PUBLIC, anon, authenticated, service_role;", para: "  FROM PUBLIC;" },
    { nome: "sem search_path fixo", de: "SET search_path = pg_catalog, public\nAS $$", para: "AS $$" },
    { nome: "SECURITY DEFINER", de: "SECURITY INVOKER", para: "SECURITY DEFINER" },
    { nome: "GRANT a mais", de: "  TO service_role;", para: "  TO service_role, authenticated;" },
  ];

  for (const s of sabotagens) {
    it(`🔴 ${s.nome}: a migration FALHA FECHADA`, LENTO, async () => {
      await palco(false);
      const sql = lerSql(M_108).split("\r\n").join("\n");
      expect(sql, `a âncora «${s.de.trim()}» já não existe no SQL`).toContain(s.de);

      await expect(pool.query(sql.replace(s.de, () => s.para)))
        .rejects.toThrow(/CRM_LINK_108_POSTSTATE_FAILED/);

      await palco();
      leadA = await novaLead();
    });
  }
});

// ───────────────────────────────────────────────────────────────────────────
describe("7. proveniência e rollback", () => {
  it("🔴 JA_APLICADA: não corre duas vezes", LENTO, async () => {
    await expect(pool.query(lerSql(M_108))).rejects.toThrow(/CRM_LINK_108_JA_APLICADA/);
  });

  it("🔴 EFFECT_WITHOUT_LEDGER: efeito sem linha de ledger", LENTO, async () => {
    await pool.query("DELETE FROM public._migrations WHERE name = $1", [NOME_108]);
    try {
      await expect(pool.query(lerSql(M_108))).rejects.toThrow(/CRM_LINK_108_EFFECT_WITHOUT_LEDGER/);
    } finally {
      await registarNoLedger(NOME_108);
    }
  });

  it("🔴 sem a 104 no ledger → DEPENDENCY_LEDGER_MISSING, nada criado", LENTO, async () => {
    await palco(false);
    await pool.query("DELETE FROM public._migrations WHERE name = $1", [NOME_104]);

    await expect(pool.query(lerSql(M_108))).rejects.toThrow(/CRM_LINK_108_DEPENDENCY_LEDGER_MISSING/);
    const { rows } = await pool.query(`SELECT to_regprocedure('${ASSINATURA}') IS NULL AS ausente`);
    expect(rows[0].ausente).toBe(true);

    await palco();
    leadA = await novaLead();
  });

  it("🔴 sem `SELECT ... INTO`: o SQL Editor do Supabase parte-o (lição da 107)", () => {
    // O editor lê-o como «criar a tabela» e injecta `ALTER TABLE ... ENABLE
    // ROW LEVEL SECURITY` a meio do corpo. `INSERT INTO` e `RETURNING ... INTO`
    // passam; só a forma SELECT é o problema.
    const sql = lerSql(M_108).replace(/--.*$/gm, "");
    const instrucoes = sql.split(";");
    const comSelectInto = instrucoes.filter((i) =>
      /\bSELECT\b/i.test(i) && /\bINTO\b/i.test(i)
      && !/\bINSERT\s+INTO\b/i.test(i) && !/\bRETURNING\b[^;]*\bINTO\b/i.test(i));
    expect(comSelectInto).toEqual([]);
  });

  it("🔴 o checksum do rollback é o do ficheiro da 108", () => {
    expect(lerSql(ROLLBACK_108)).toContain(`'${checksumLf(NOME_108)}'`);
  });

  it("🔴 os checksums das dependências são os dos ficheiros", () => {
    // As duas listas são paralelas: o i-ésimo checksum é o do i-ésimo nome.
    const sql = lerSql(M_108);
    const lista = (nome: string) => {
      const m = sql.match(new RegExp(`${nome} CONSTANT text\\[\\] := ARRAY\\[([\\s\\S]*?)\\];`));
      if (!m) throw new Error(`${nome} não encontrado na 108`);
      return [...m[1].matchAll(/'([^']+)'/g)].map((x) => x[1]);
    };
    const nomes = lista("v_nomes");
    const checksums = lista("v_checksums");

    expect(nomes).toEqual([...CADEIA, NOME_102, NOME_103, NOME_103A, NOME_104]);
    expect(checksums).toEqual(nomes.map((n) => checksumLf(n)));
  });

  it("rollback remove a RPC e a linha, mantém as associações, e a 108 volta a aplicar-se", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const r = await associar(leadA, q.id, CLIENTE_A);

    await pool.query(lerSql(ROLLBACK_108));

    const { rows } = await pool.query(`
      SELECT to_regprocedure('${ASSINATURA}') IS NULL AS sem_rpc,
             NOT EXISTS (SELECT 1 FROM public._migrations WHERE name = '${NOME_108}') AS sem_ledger,
             (SELECT converted_client_id FROM public.crm_leads WHERE id = '${leadA}') AS cliente`);
    expect(rows[0]).toEqual({ sem_rpc: true, sem_ledger: true, cliente: CLIENTE_A });
    expect(r.client_id).toBe(CLIENTE_A);

    // Rollback repetido é no-op.
    await pool.query(lerSql(ROLLBACK_108));

    await pool.query(lerSql(M_108));
    await registarNoLedger(NOME_108);
  });
});
