// ============================================================================
// Orçamentos — o runtime contra a base a sério
// ============================================================================
//
// 🔴 O que só Postgres real responde, e nenhum mock responde.
//
//    1. os TOTAIS. `totaisDoOrcamento` existe para antecipar no ecrã o que a
//       RPC vai gravar. Se divergir num cêntimo, o formulário promete um valor
//       e o documento diz outro — e quem recebe o PDF não sabe qual é o certo.
//       Um mock da RPC compararia a função consigo mesma.
//
//    2. a MATRIZ DE ESTADOS. `QUOTE_TRANSITIONS` é espelho de
//       `set_crm_quote_status`. `crm-quotes-vocabulary.test.ts` compara-a com o
//       TEXTO do SQL; aqui compara-se com o COMPORTAMENTO: os 36 pares
//       possíveis, um a um, contra a base. Um `IF` que o regexp leu bem mas
//       que a base avalia de outra maneira passaria pelo primeiro e cai aqui.
//
//    3. o FLUXO DE REVISÃO. Que uma R1 nasce em rascunho e a R0 fica marcada
//       como substituída, na mesma transação, é propriedade da RPC — não se
//       demonstra com texto no ecrã a dizer que acontece.
//
// O palco é a cadeia como está em produção HOJE: baseline + 101 + 101a + 101b
// + 102 → 103.
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";
import {
  canTransitionQuote,
  hasMaxDecimalPlaces,
  QUOTE_STATUSES,
  totaisDoOrcamento,
  type QuoteStatus,
} from "@/lib/crm/quotes";

const CONTAINER = `crmorc-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const OUTRA = "22222222-2222-4222-8222-222222222222";
const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const GESTORA_OUTRA = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const CLIENTE_A = "c1111111-1111-4111-8111-111111111111";
const CLIENTE_B = "c2222222-2222-4222-8222-222222222222";

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_102 = "supabase/migrations/102_crm_visitas_comerciais.sql";
const M_103 = "supabase/migrations/103_crm_orcamentos.sql";

const NOME_102 = "102_crm_visitas_comerciais.sql";
const NOME_103 = "103_crm_orcamentos.sql";

/** A cadeia que o portão de proveniência da 103 exige ver no ledger. */
const CADEIA = [
  "101_crm_leads.sql",
  "101a_crm_rpc_acl_hardening.sql",
  "101b_identity_reconciliation.sql",
] as const;

const ANO = 2026;

let container: PostgresContainer;
let pool: pg.Pool;
let leadA = "";

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

/** O mesmo cálculo de `checksumForNewMigration`: SHA-256 sobre LF normalizado. */
const checksumLf = (ficheiro: string): string =>
  createHash("sha256")
    .update(lerSql(`supabase/migrations/${ficheiro}`).split("\r\n").join("\n").split("\r").join("\n"))
    .digest("hex");

async function registarNoLedger(nome: string): Promise<void> {
  await pool.query(
    `INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)
     ON CONFLICT (name) DO UPDATE SET checksum = EXCLUDED.checksum`,
    [nome, checksumLf(nome)],
  );
}

/** A cadeia real até à 103, aplicada como o runner a aplicaria. */
async function palco(): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);
  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await pool.query(lerSql(M_101B));

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public._migrations (
      name text PRIMARY KEY, checksum text, applied_at timestamptz NOT NULL DEFAULT now())`);
  for (const nome of CADEIA) await registarNoLedger(nome);

  // 🔴 A linha de uma migration entra DEPOIS de ela correr — é o que o runner
  //    faz, e escrever antes daria `LEDGER_WITHOUT_EFFECT` ao portão seguinte.
  await pool.query(lerSql(M_102));
  await registarNoLedger(NOME_102);

  await semear();

  await pool.query(lerSql(M_103));
  await registarNoLedger(NOME_103);
}

async function semear(): Promise<void> {
  await pool.query("INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a'),($2,'B','b')",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO public.company_settings (company_id) VALUES ($1),($2)",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO auth.users (id,email) VALUES ($1,'g@a.pt'),($2,'g@b.pt')",
    [GESTORA, GESTORA_OUTRA]);
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id) VALUES
      ($1,$2,'Gestora A','gestor','ativo',$1),
      ($3,$4,'Gestora B','gestor','ativo',$3)`,
    [GESTORA, EMPRESA, GESTORA_OUTRA, OUTRA],
  );
  await pool.query(
    "INSERT INTO public.clients (id,company_id,name) VALUES ($1,$2,'Cliente A'), ($3,$4,'Cliente B')",
    [CLIENTE_A, EMPRESA, CLIENTE_B, OUTRA],
  );
}

interface LinhaItem {
  description: string;
  quantity: number;
  unit: string;
  unit_price: number;
}

/**
 * `create_crm_quote_with_items` com os 19 argumentos, pela ordem da assinatura.
 *
 * 🔴 `p_prefix`, `p_year` e `p_vat_rate` são os mesmos que a Server Action
 *    passa: prefixo das definições, ano da data de emissão, taxa das
 *    definições. Um ensaio que passasse outros valores mediria outra coisa.
 */
async function criar(opts: {
  itens: LinhaItem[];
  desconto?: number;
  aplicaIva?: boolean;
  taxaIva?: number;
  validadeDias?: number;
}): Promise<{ id: string; numero: string }> {
  const { rows } = await pool.query(
    `SELECT * FROM public.create_crm_quote_with_items(
       $1,$2,NULL,NULL,'ORC',$3,CURRENT_DATE,CURRENT_DATE + $4::int,
       'pontual',$5,$6,$7,NULL,NULL,NULL,NULL,NULL,$8,$9::jsonb)`,
    [
      EMPRESA,
      leadA,
      ANO,
      opts.validadeDias ?? 30,
      opts.desconto ?? 0,
      opts.aplicaIva ?? true,
      opts.taxaIva ?? 23,
      GESTORA,
      JSON.stringify(opts.itens),
    ],
  );
  return { id: rows[0].quote_id as string, numero: rows[0].quote_number as string };
}

async function estado(id: string): Promise<string> {
  const { rows } = await pool.query("SELECT status FROM public.crm_quotes WHERE id = $1", [id]);
  return rows[0].status as string;
}

/** `set_crm_quote_status`, devolvendo se a base aceitou ou porque recusou. */
async function mudar(
  id: string,
  destino: string,
): Promise<{ ok: true } | { ok: false; erro: string }> {
  try {
    await pool.query(
      "SELECT * FROM public.set_crm_quote_status($1,$2,$3,$4,NULL)",
      [EMPRESA, id, GESTORA, destino],
    );
    return { ok: true };
  } catch (err) {
    return { ok: false, erro: String((err as Error).message) };
  }
}

/** Põe um orçamento novo no estado pedido, pelo caminho que a base permite. */
async function orcamentoEm(destino: QuoteStatus): Promise<string> {
  const { id } = await criar({ itens: [{ description: "Base", quantity: 1, unit: "servico", unit_price: 100 }] });
  if (destino === "rascunho") return id;
  if (destino === "anulado") {
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'anulado',NULL)", [EMPRESA, id, GESTORA]);
    return id;
  }
  // Tudo o resto passa por `enviado`.
  await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)", [EMPRESA, id, GESTORA]);
  if (destino === "enviado") return id;
  await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,$4,NULL)", [EMPRESA, id, GESTORA, destino]);
  return id;
}

beforeAll(async () => {
  container = await startPostgresContainer({ name: CONTAINER, database: "crmorc", memory: "512m" });
  pool = new pg.Pool({ ...container.connection, max: 4 });
  await palco();
}, 240_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechado */ });
  container?.stop();
});

beforeEach(async () => {
  // Cada ensaio começa com as tabelas de orçamentos vazias e uma lead nova, sem
  // reconstruir o palco: a 103 já está aplicada e não se reaplica.
  await pool.query("DELETE FROM public.crm_quote_items");
  await pool.query("DELETE FROM public.crm_quotes");
  await pool.query("DELETE FROM public.crm_leads");
  const { rows } = await pool.query(
    "INSERT INTO public.crm_leads (company_id, name) VALUES ($1,'Condomínio Alfa') RETURNING id",
    [EMPRESA],
  );
  leadA = rows[0].id as string;
});

// ───────────────────────────────────────────────────────────────────────────
describe("🔴 paridade de totais — a pré-visualização e o que a base grava", () => {
  /**
   * Cenários escolhidos pelos sítios onde o arredondamento decide.
   *
   * Os casos de MEIO (0,495 · 8,615 · 0,335) são o coração disto: é ali que
   * `Math.round` em binário e `round()` em `numeric` discordam.
   */
  const CENARIOS: Array<{
    nome: string;
    itens: LinhaItem[];
    desconto?: number;
    aplicaIva?: boolean;
    taxaIva?: number;
  }> = [
    {
      nome: "uma linha redonda, IVA 23%",
      itens: [{ description: "Limpeza", quantity: 1, unit: "servico", unit_price: 100 }],
    },
    {
      nome: "meio a arredondar por linha (1,5 × 0,33)",
      itens: [
        { description: "A", quantity: 1.5, unit: "hora", unit_price: 0.33 },
        { description: "B", quantity: 1.5, unit: "hora", unit_price: 0.33 },
      ],
    },
    {
      nome: "meio no preço (8,615 quantizado pela coluna)",
      itens: [{ description: "A", quantity: 1, unit: "m2", unit_price: 8.615 }],
    },
    {
      nome: "meio no preço pequeno (0,335 × 3)",
      itens: [{ description: "A", quantity: 3, unit: "unidade", unit_price: 0.335 }],
    },
    {
      nome: "desconto de 10% com IVA sobre a base",
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 100 }],
      desconto: 10,
    },
    {
      nome: "desconto fraccionário (7,5%)",
      itens: [{ description: "A", quantity: 3, unit: "hora", unit_price: 17.35 }],
      desconto: 7.5,
    },
    {
      nome: "desconto de 100%",
      itens: [{ description: "A", quantity: 2, unit: "servico", unit_price: 75 }],
      desconto: 100,
    },
    {
      nome: "isento de IVA",
      itens: [{ description: "A", quantity: 4, unit: "mes", unit_price: 249.99 }],
      aplicaIva: false,
    },
    {
      nome: "taxa de IVA a zero",
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 33.33 }],
      taxaIva: 0,
    },
    {
      nome: "IVA 6% sobre base com desconto",
      itens: [{ description: "A", quantity: 7, unit: "hora", unit_price: 12.45 }],
      desconto: 3.33,
      taxaIva: 6,
    },
    {
      nome: "seis casas no preço — o limite do domínio",
      itens: [{ description: "A", quantity: 3, unit: "unidade", unit_price: 0.000001 }],
    },
    {
      nome: "seis casas na quantidade",
      itens: [{ description: "A", quantity: 1.000001, unit: "hora", unit_price: 99.99 }],
    },
    {
      nome: "seis casas dos dois lados, com desconto de seis casas",
      itens: [{ description: "A", quantity: 12.345678, unit: "m2", unit_price: 1.234567 }],
      desconto: 3.141592,
    },
    {
      nome: "muitas linhas irregulares",
      itens: [
        { description: "A", quantity: 2.25, unit: "hora", unit_price: 11.11 },
        { description: "B", quantity: 0.5, unit: "hora", unit_price: 9.99 },
        { description: "C", quantity: 13, unit: "m2", unit_price: 1.07 },
        { description: "D", quantity: 1, unit: "servico", unit_price: 0.01 },
      ],
      desconto: 12.5,
    },
  ];

  for (const c of CENARIOS) {
    it(`${c.nome}`, LENTO, async () => {
      const { id } = await criar(c);

      const { rows } = await pool.query(
        "SELECT subtotal, vat_amount, total FROM public.crm_quotes WHERE id = $1",
        [id],
      );
      const base = {
        subtotal: Number(rows[0].subtotal),
        vatAmount: Number(rows[0].vat_amount),
        total: Number(rows[0].total),
      };

      const previsto = totaisDoOrcamento(
        c.itens.map((i) => ({ quantity: i.quantity, unit_price: i.unit_price })),
        { discountPct: c.desconto ?? 0, applyVat: c.aplicaIva ?? true, vatRate: c.taxaIva ?? 23 },
      );

      expect(previsto.subtotal, "subtotal").toBe(base.subtotal);
      expect(previsto.vatAmount, "IVA").toBe(base.vatAmount);
      expect(previsto.total, "total").toBe(base.total);
    });
  }

  it("🔴 fora do domínio, a base e o runtime DIVERGEM — é por isso que se recusa", LENTO, async () => {
    // Os dois casos que a direcção nomeou. Aqui mede-se a divergência contra o
    // Postgres a sério: é a justificação do limite de seis casas, e não uma
    // restrição arbitrária. A action recusa estes valores antes da RPC
    // (`crm-quote-actions.test.ts`); este ensaio explica porquê.
    const casos: Array<{ preco: number; base: number }> = [
      { preco: 0.000000051, base: 0.01 },
      { preco: 0.000001051, base: 0.11 },
    ];

    for (const { preco, base } of casos) {
      const { rows } = await pool.query(
        "SELECT round(100000::numeric * $1::numeric, 2) AS total", [preco]);
      expect(Number(rows[0].total), `Postgres para ${preco}`).toBe(base);

      const previsto = totaisDoOrcamento(
        [{ quantity: 100_000, unit_price: preco }],
        { discountPct: 0, applyVat: false, vatRate: 0 },
      );
      expect(previsto.subtotal, `runtime para ${preco}`).not.toBe(base);

      // E é exactamente por isto que o valor não é aceite.
      expect(hasMaxDecimalPlaces(preco)).toBe(false);
    }
  });

  it("🔴 line_total é o da base, e não quantidade × preço no cliente", LENTO, async () => {
    // A coluna é `numeric(10,2)`: 1,5 × 0,33 = 0,495 é gravado como 0,50. Um
    // PDF que multiplicasse os dois campos mostraria 0,49 ou 0,50 dependendo
    // do arredondamento, e a soma deixaria de bater com o subtotal gravado.
    const { id } = await criar({
      itens: [{ description: "A", quantity: 1.5, unit: "hora", unit_price: 0.33 }],
    });
    const { rows } = await pool.query(
      "SELECT quantity, unit_price, line_total FROM public.crm_quote_items WHERE quote_id = $1",
      [id],
    );
    expect(Number(rows[0].line_total)).toBe(0.5);
    expect(Number(rows[0].quantity) * Number(rows[0].unit_price)).not.toBe(0.5);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("🔴 paridade de estados — os 36 pares, um a um", () => {
  for (const origem of QUOTE_STATUSES) {
    for (const destino of QUOTE_STATUSES) {
      if (origem === destino) continue; // idempotente por desenho da RPC

      const permitido = canTransitionQuote(origem, destino);

      it(`${origem} → ${destino}: ${permitido ? "aceite" : "recusado"}`, LENTO, async () => {
        const id = await orcamentoEm(origem);
        expect(await estado(id), `o palco não pôs o orçamento em ${origem}`).toBe(origem);

        const r = await mudar(id, destino);

        expect(r.ok, `runtime diz ${permitido}, base diz ${r.ok}`).toBe(permitido);
        if (permitido) {
          expect(await estado(id)).toBe(destino);
        } else {
          // Recusada é recusada: o estado não se move nem um pouco.
          expect(await estado(id)).toBe(origem);
          expect(
            r.ok === false && /QUOTE_(TRANSITION_NOT_ALLOWED|ACCEPTED|VOIDED|EXPIRED)/.test(r.erro),
          ).toBe(true);
        }
      });
    }
  }

  it("o mesmo estado outra vez é aceite sem mudar nada", LENTO, async () => {
    const id = await orcamentoEm("enviado");
    const { rows: antes } = await pool.query(
      "SELECT sent_at FROM public.crm_quotes WHERE id = $1", [id]);
    expect((await mudar(id, "enviado")).ok).toBe(true);
    const { rows: depois } = await pool.query(
      "SELECT sent_at FROM public.crm_quotes WHERE id = $1", [id]);
    expect(depois[0].sent_at).toEqual(antes[0].sent_at);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("🔴 rascunho → enviado, MANUALMENTE", () => {
  it("o estado muda e a data de envio é carimbada pela base", LENTO, async () => {
    // O envio automático é a 103-B2. Sem esta transição, um orçamento
    // entregue por PDF ficaria eternamente «rascunho».
    const { id } = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 80 }],
    });
    expect(await estado(id)).toBe("rascunho");

    expect((await mudar(id, "enviado")).ok).toBe(true);

    const { rows } = await pool.query(
      "SELECT status, sent_at FROM public.crm_quotes WHERE id = $1", [id]);
    expect(rows[0].status).toBe("enviado");
    // O CHECK `crm_quotes_enviado_tem_data` não deixaria passar sem data.
    expect(rows[0].sent_at).not.toBeNull();
  });

  it("um enviado que expirou não se aceita", LENTO, async () => {
    const { id } = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 80 }],
      validadeDias: 0,
    });
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)", [EMPRESA, id, GESTORA]);
    // 🔴 As DUAS datas recuam. `crm_quotes_validade_coerente` exige
    //    `valid_until >= issue_date`, e mexer só na validade viola o CHECK —
    //    o ensaio rebentava antes de chegar à regra que quer medir.
    await pool.query(
      `UPDATE public.crm_quotes
          SET issue_date = CURRENT_DATE - 10, valid_until = CURRENT_DATE - 1
        WHERE id = $1`, [id]);

    const r = await mudar(id, "aceite");
    expect(r.ok).toBe(false);
    expect(r.ok === false && r.erro).toContain("QUOTE_EXPIRED_CANNOT_ACCEPT");
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("🔴 revisão — R0 enviada → R1 rascunho, R0 histórica", () => {
  it("o fluxo completo, como a direcção o quer ver", LENTO, async () => {
    const r0 = await criar({
      itens: [{ description: "Escadas", quantity: 1, unit: "servico", unit_price: 100 }],
    });
    expect(r0.numero).toBe("ORC2026/001");

    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)", [EMPRESA, r0.id, GESTORA]);

    const { rows: rev } = await pool.query(
      `SELECT * FROM public.revise_crm_quote(
         $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,'Preço revisto',$4::jsonb)`,
      [
        EMPRESA,
        r0.id,
        GESTORA,
        JSON.stringify([{ description: "Escadas", quantity: 1, unit: "servico", unit_price: 90 }]),
      ],
    );

    const r1Id = rev[0].quote_id as string;
    expect(rev[0].quote_number).toBe("ORC2026/001-R1");

    const { rows } = await pool.query(
      `SELECT id, revision, status, superseded_by_id, root_quote_id, quote_seq, source_lead_id, total
         FROM public.crm_quotes ORDER BY revision`,
    );
    expect(rows).toHaveLength(2);

    const [antiga, nova] = rows;

    // R0: fica com o estado que tinha e passa a apontar para a substituta.
    expect(antiga.status).toBe("enviado");
    expect(antiga.superseded_by_id).toBe(r1Id);

    // R1: nasce em rascunho — ainda não foi enviada a ninguém.
    expect(nova.revision).toBe(1);
    expect(nova.status).toBe("rascunho");
    expect(nova.superseded_by_id).toBeNull();

    // Mesma cadeia, mesmo sequencial: uma revisão não consome um número novo.
    expect(nova.root_quote_id).toBe(antiga.root_quote_id);
    expect(nova.quote_seq).toBe(antiga.quote_seq);

    // A proveniência viaja, e é a mesma lead.
    expect(nova.source_lead_id).toBe(leadA);
    expect(antiga.source_lead_id).toBe(leadA);

    // E os totais novos são os da revisão.
    expect(Number(nova.total)).toBe(110.7);
  });

  it("🔴 COALESCE(p_notes, …): NULL herda, string vazia APAGA", LENTO, async () => {
    // É o comportamento da RPC que obriga o formulário a enviar sempre o
    // conteúdo do campo numa revisão. Com `null`, a base repunha exactamente
    // o texto que a pessoa acabara de apagar — e não havia forma nenhuma de
    // remover as observações numa revisão.
    const r0 = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 50 }],
    });
    await pool.query(
      "UPDATE public.crm_quotes SET notes = 'Inclui produtos.' WHERE id = $1", [r0.id]);
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, r0.id, GESTORA]);

    const itens = JSON.stringify([
      { description: "A", quantity: 1, unit: "servico", unit_price: 60 },
    ]);

    // NULL: herda.
    const { rows: comNull } = await pool.query(
      `SELECT * FROM public.revise_crm_quote(
         $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, r0.id, GESTORA, itens],
    );
    const { rows: herdada } = await pool.query(
      "SELECT notes FROM public.crm_quotes WHERE id = $1", [comNull[0].quote_id]);
    expect(herdada[0].notes).toBe("Inclui produtos.");

    // String vazia: apaga.
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, comNull[0].quote_id, GESTORA]);
    const { rows: comVazio } = await pool.query(
      `SELECT * FROM public.revise_crm_quote(
         $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,'',$4::jsonb)`,
      [EMPRESA, comNull[0].quote_id, GESTORA, itens],
    );
    const { rows: limpa } = await pool.query(
      "SELECT notes FROM public.crm_quotes WHERE id = $1", [comVazio[0].quote_id]);
    expect(limpa[0].notes).toBe("");
  });

  it("🔴 uma revisão com datas de hoje não nasce expirada", LENTO, async () => {
    // O formulário abre em `todayInLisbon()` justamente por isto: herdar a
    // `issue_date` da R0 trazia com ela uma validade no passado, e a R1
    // nascia inaceitável — só falhava mais tarde, ao ser aceite.
    const r0 = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 50 }],
    });
    await pool.query(
      `UPDATE public.crm_quotes
          SET issue_date = CURRENT_DATE - 100, valid_until = CURRENT_DATE - 70
        WHERE id = $1`, [r0.id]);
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, r0.id, GESTORA]);

    const { rows } = await pool.query(
      `SELECT * FROM public.revise_crm_quote(
         $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, r0.id, GESTORA,
        JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 60 }])],
    );

    // A R1 é aceitável: enviada e aceite, sem QUOTE_EXPIRED_CANNOT_ACCEPT.
    const r1 = rows[0].quote_id as string;
    expect((await mudar(r1, "enviado")).ok).toBe(true);
    expect((await mudar(r1, "aceite")).ok).toBe(true);
  });

  it("🔴 uma revisão que herdasse a validade da R0 seria inaceitável", LENTO, async () => {
    // O reverso do ensaio anterior, contra a base: é o estrago concreto que a
    // correcção evita.
    const r0 = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 50 }],
    });
    await pool.query(
      `UPDATE public.crm_quotes
          SET issue_date = CURRENT_DATE - 100, valid_until = CURRENT_DATE - 70
        WHERE id = $1`, [r0.id]);
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, r0.id, GESTORA]);

    // As datas herdadas: emissão e validade da R0, ambas no passado.
    const { rows } = await pool.query(
      `SELECT * FROM public.revise_crm_quote(
         $1,$2,$3,CURRENT_DATE - 100,CURRENT_DATE - 70,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, r0.id, GESTORA,
        JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 60 }])],
    );

    const r1 = rows[0].quote_id as string;
    // A base ACEITA criá-la — o CHECK só exige valid_until >= issue_date.
    expect((await mudar(r1, "enviado")).ok).toBe(true);
    // E só aqui rebenta, muito depois de o cliente ter aprovado o preço.
    const r = await mudar(r1, "aceite");
    expect(r.ok).toBe(false);
    expect(r.ok === false && r.erro).toContain("QUOTE_EXPIRED_CANNOT_ACCEPT");
  });

  it("🔴 um substituído já não muda de estado", LENTO, async () => {
    const r0 = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 50 }],
    });
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)", [EMPRESA, r0.id, GESTORA]);
    await pool.query(
      `SELECT public.revise_crm_quote($1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, r0.id, GESTORA, JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 60 }])],
    );

    const r = await mudar(r0.id, "aceite");
    expect(r.ok).toBe(false);
    expect(r.ok === false && r.erro).toContain("QUOTE_ALREADY_SUPERSEDED");
  });

  it("🔴 um RASCUNHO não se revê — é por isso que a edição in-place falta", LENTO, async () => {
    // `DRAFT_EDIT_REQUIRES_ATOMIC_RPC = YES`. Corrigir um rascunho exigiria
    // UPDATE + DELETE + INSERT numa só transação, e a 103 não tem essa RPC.
    // Em chamadas separadas, uma falha depois do DELETE deixaria o rascunho
    // sem linhas nenhumas. Até haver a RPC: anula-se e faz-se outro.
    const { id } = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 50 }],
    });

    await expect(
      pool.query(
        `SELECT public.revise_crm_quote($1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
        [EMPRESA, id, GESTORA, JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 60 }])],
      ),
    ).rejects.toThrow(/QUOTE_DRAFT_EDIT_IN_PLACE/);

    // E o caminho que fica aberto funciona.
    expect((await mudar(id, "anulado")).ok).toBe(true);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("🔴 a lista operacional só vê a revisão viva", () => {
  /**
   * A consulta que `getQuotes()` faz por omissão.
   *
   * 🔴 O predicado é escrito aqui à mão de propósito: o que se quer medir é o
   *    COMPORTAMENTO do filtro contra a base, e não que o query builder do
   *    Supabase o traduza. A tradução é o que o guard estrutural verifica.
   */
  const OPERACIONAL = `
    SELECT quote_number, status FROM public.crm_quotes
     WHERE company_id = $1 AND superseded_by_id IS NULL
     ORDER BY quote_seq DESC, revision DESC`;

  const HISTORICO = `
    SELECT quote_number, status FROM public.crm_quotes
     WHERE company_id = $1
     ORDER BY quote_seq DESC, revision DESC`;

  /** R0 enviada, revista para R1. É o caso que a direcção nomeou. */
  async function cadeiaRevista(): Promise<{ r0: string; r1: string }> {
    const r0 = await criar({
      itens: [{ description: "Escadas", quantity: 1, unit: "servico", unit_price: 100 }],
    });
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, r0.id, GESTORA]);
    const { rows } = await pool.query(
      `SELECT * FROM public.revise_crm_quote(
         $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, r0.id, GESTORA,
        JSON.stringify([{ description: "Escadas", quantity: 1, unit: "servico", unit_price: 90 }])],
    );
    return { r0: r0.numero, r1: rows[0].quote_number as string };
  }

  it("🔴 R0 enviado → R1: a lista só devolve a R1", LENTO, async () => {
    const { r0, r1 } = await cadeiaRevista();

    const { rows } = await pool.query(OPERACIONAL, [EMPRESA]);
    expect(rows.map((r) => r.quote_number)).toEqual([r1]);
    expect(rows.map((r) => r.quote_number)).not.toContain(r0);
  });

  it("🔴 o filtro «Enviado» deixa de contar a R0 substituída", LENTO, async () => {
    // Era o defeito operacional: R0 `enviado` continuava a somar às propostas
    // por responder, apesar de já não estar em vigor.
    await cadeiaRevista();

    const { rows } = await pool.query(
      `${OPERACIONAL.replace("superseded_by_id IS NULL", "superseded_by_id IS NULL AND status = 'enviado'")}`,
      [EMPRESA],
    );
    expect(rows).toHaveLength(0);
  });

  it("nada se apaga: a cadeia completa continua lá", LENTO, async () => {
    // É uma decisão de LEITURA, não de retenção.
    const { r0, r1 } = await cadeiaRevista();

    const { rows } = await pool.query(HISTORICO, [EMPRESA]);
    expect(rows.map((r) => r.quote_number).sort()).toEqual([r0, r1].sort());

    // E a R0 mantém o estado com que foi enviada ao cliente.
    expect(rows.find((r) => r.quote_number === r0).status).toBe("enviado");
  });

  it("uma cadeia sem revisões aparece na mesma", LENTO, async () => {
    // O filtro não pode esconder o caso normal: `superseded_by_id` é NULL num
    // orçamento que nunca foi revisto.
    const q = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 10 }],
    });
    const { rows } = await pool.query(OPERACIONAL, [EMPRESA]);
    expect(rows.map((r) => r.quote_number)).toEqual([q.numero]);
  });

  it("🔴 duas revisões seguidas: só a última sobrevive à lista", LENTO, async () => {
    const { r0 } = await cadeiaRevista();

    // A R1 está em rascunho; envia-se e revê-se outra vez.
    const { rows: viva } = await pool.query(
      "SELECT id FROM public.crm_quotes WHERE superseded_by_id IS NULL");
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, viva[0].id, GESTORA]);
    const { rows: r2 } = await pool.query(
      `SELECT * FROM public.revise_crm_quote(
         $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, viva[0].id, GESTORA,
        JSON.stringify([{ description: "Escadas", quantity: 1, unit: "servico", unit_price: 80 }])],
    );

    const { rows } = await pool.query(OPERACIONAL, [EMPRESA]);
    expect(rows.map((r) => r.quote_number)).toEqual([r2[0].quote_number]);
    expect(rows.map((r) => r.quote_number)).not.toContain(r0);

    // As três continuam gravadas.
    const { rows: todas } = await pool.query(HISTORICO, [EMPRESA]);
    expect(todas).toHaveLength(3);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("🔴 proveniência — source_lead_id nasce certa e não se reescreve", () => {
  it("nasce igual à lead de origem", LENTO, async () => {
    const { id } = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 10 }],
    });
    const { rows } = await pool.query(
      "SELECT lead_id, source_lead_id FROM public.crm_quotes WHERE id = $1", [id]);
    expect(rows[0].source_lead_id).toBe(leadA);
    expect(rows[0].lead_id).toBe(leadA);
  });

  it("qualquer alteração é recusada pelo trigger", LENTO, async () => {
    const { id } = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 10 }],
    });
    await expect(
      pool.query("UPDATE public.crm_quotes SET source_lead_id = NULL WHERE id = $1", [id]),
    ).rejects.toThrow(/QUOTE_SOURCE_LEAD_IMMUTABLE/);
  });

  it("a leitura por proveniência encontra o orçamento", LENTO, async () => {
    // É a consulta que `getQuotes({ leadId })` faz. Por `lead_id` deixaria de
    // funcionar depois da conversão (104), que põe `lead_id` a NULL.
    const { id } = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 10 }],
    });
    const { rows } = await pool.query(
      "SELECT id FROM public.crm_quotes WHERE company_id = $1 AND source_lead_id = $2",
      [EMPRESA, leadA],
    );
    expect(rows.map((r) => r.id)).toEqual([id]);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("a base recusa o que o formulário também recusa", () => {
  it("um orçamento sem linhas", LENTO, async () => {
    await expect(criar({ itens: [] })).rejects.toThrow();
  });

  it("uma visita que não é deste destinatário", LENTO, async () => {
    const { rows: v } = await pool.query(
      `INSERT INTO public.crm_visits (company_id, client_id, scheduled_start, scheduled_end)
       VALUES ($1,$2, now(), now() + interval '1 hour') RETURNING id`,
      [EMPRESA, CLIENTE_A],
    );
    await expect(
      pool.query(
        `SELECT public.create_crm_quote_with_items(
           $1,$2,NULL,$3,'ORC',$4,CURRENT_DATE,CURRENT_DATE + 30,
           'pontual',0,true,23,NULL,NULL,NULL,NULL,NULL,$5,$6::jsonb)`,
        [
          EMPRESA,
          leadA,
          v[0].id,
          ANO,
          GESTORA,
          JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 10 }]),
        ],
      ),
    ).rejects.toThrow(/QUOTE_VISIT_MISMATCH/);
  });

  it("um destinatário que é lead E cliente ao mesmo tempo", LENTO, async () => {
    await expect(
      pool.query(
        `SELECT public.create_crm_quote_with_items(
           $1,$2,$3,NULL,'ORC',$4,CURRENT_DATE,CURRENT_DATE + 30,
           'pontual',0,true,23,NULL,NULL,NULL,NULL,NULL,$5,$6::jsonb)`,
        [
          EMPRESA,
          leadA,
          CLIENTE_A,
          ANO,
          GESTORA,
          JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 10 }]),
        ],
      ),
    ).rejects.toThrow();
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("orçamentar não toca na operação nem no dinheiro", () => {
  it("🔴 criar, enviar, revir e aceitar não cria serviço, contrato nem factura", LENTO, async () => {
    const r0 = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 100 }],
    });
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)", [EMPRESA, r0.id, GESTORA]);
    const { rows: rev } = await pool.query(
      `SELECT * FROM public.revise_crm_quote($1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, r0.id, GESTORA, JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 90 }])],
    );
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, rev[0].quote_id, GESTORA]);
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'aceite',NULL)",
      [EMPRESA, rev[0].quote_id, GESTORA]);

    for (const tabela of ["services", "contracts", "invoices", "invoice_items", "cash_flow_entries", "locations"]) {
      const { rows } = await pool.query(`SELECT count(*)::int AS n FROM public.${tabela}`);
      expect(rows[0].n, `${tabela} devia continuar vazia`).toBe(0);
    }
  });

  it("a conversão fica para a 104: as colunas existem e continuam vazias", LENTO, async () => {
    const { id } = await criar({
      itens: [{ description: "A", quantity: 1, unit: "servico", unit_price: 100 }],
    });
    const { rows } = await pool.query(
      "SELECT converted_contract_id, converted_service_id FROM public.crm_quotes WHERE id = $1",
      [id],
    );
    expect(rows[0].converted_contract_id).toBeNull();
    expect(rows[0].converted_service_id).toBeNull();
  });
});
