// ============================================================================
// 103 — orçamentos: numeração, revisões e proveniência, contra Postgres real
// ============================================================================
//
// 🔴 O palco é a cadeia como ela está EM PRODUÇÃO hoje:
//
//        baseline canónico + 101 + 101a + 101b + 102  →  103
//
//    A 102 entrou no ledger a 19/09. A 103 depende dela — `crm_quotes.visit_id`
//    aponta para `crm_visits` — e o portão de proveniência exige as quatro.
//
// ---------------------------------------------------------------------------
// O que só Postgres real responde
// ---------------------------------------------------------------------------
//
//   · duas criações em simultâneo atribuem números diferentes e consecutivos;
//   · duas revisões da mesma revisão viva: só uma ganha;
//   · a proveniência não se reescreve, nem sequer de NULL para um valor.
//
// Nenhuma destas três se prova com mocks: são todas sobre o que acontece
// quando duas ligações fazem a mesma coisa ao mesmo tempo.
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";

const CONTAINER = `crm103-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const OUTRA = "22222222-2222-4222-8222-222222222222";
const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const GESTORA_OUTRA = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const COLAB = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
const CLIENTE_A = "c1111111-1111-4111-8111-111111111111";
const CLIENTE_B = "c2222222-2222-4222-8222-222222222222";

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_102 = "supabase/migrations/102_crm_visitas_comerciais.sql";
const M_103 = "supabase/migrations/103_crm_orcamentos.sql";
const ROLLBACK_103 = "supabase/migrations/rollback/103_crm_orcamentos.down.sql";

const NOME_102 = "102_crm_visitas_comerciais.sql";
const NOME_103 = "103_crm_orcamentos.sql";

/** A cadeia que o portão da 103 exige ver no ledger. */
const CADEIA = [
  "101_crm_leads.sql",
  "101a_crm_rpc_acl_hardening.sql",
  "101b_identity_reconciliation.sql",
  NOME_102,
] as const;

const ANO = 2026;

let container: PostgresContainer;
let pool: pg.Pool;
let leadA = "";

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

/** O mesmo cálculo de `checksumForNewMigration`: SHA-256 sobre LF normalizado. */
const checksumLf = (ficheiro: string): string =>
  createHash("sha256")
    .update(lerSql(`supabase/migrations/${ficheiro}`).split("\r\n").join("\n").split("\r").join("\n"))
    .digest("hex");

/**
 * Escreve uma linha de ledger.
 *
 * 🔴 A ordem importa, e custou um vermelho a descobrir: a linha de uma
 *    migration só entra DEPOIS de ela correr. Escrever a da 102 antes de a
 *    aplicar dava `ledger=1 / tabela=0`, e o portão da própria 102 respondia
 *    `LEDGER_WITHOUT_EFFECT` — correctamente. O palco é que estava a encenar
 *    um estado que o runner nunca produz.
 */
async function registarNoLedger(nome: string, checksum?: string | null): Promise<void> {
  if (checksum === null) return; // linha deliberadamente em falta
  await pool.query(
    `INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)
     ON CONFLICT (name) DO UPDATE SET checksum = EXCLUDED.checksum`,
    [nome, checksum ?? checksumLf(nome)],
  );
}

/** Cadeia real até à 102. `aplicar103` fecha o palco com a migration em prova. */
async function palco(aplicar103: boolean, ledger: Readonly<Record<string, string | null>> = {}): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);
  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await pool.query(lerSql(M_101B));

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public._migrations (
      name text PRIMARY KEY, checksum text, applied_at timestamptz NOT NULL DEFAULT now())`);
  for (const nome of CADEIA.filter((n) => n !== NOME_102)) {
    await registarNoLedger(nome, ledger[nome]);
  }

  // A 102 corre primeiro, e só depois ganha linha — como o runner faz.
  await pool.query(lerSql(M_102));
  await registarNoLedger(NOME_102, ledger[NOME_102]);

  await semear();

  if (aplicar103) {
    await pool.query(lerSql(M_103));
    await registarNoLedger(NOME_103, checksumLf(NOME_103));
  }
}

async function semear(): Promise<void> {
  await pool.query("INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a'),($2,'B','b')",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO public.company_settings (company_id) VALUES ($1),($2)",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO auth.users (id,email) VALUES ($1,'g@a.pt'),($2,'g@b.pt'),($3,'c@a.pt')",
    [GESTORA, GESTORA_OUTRA, COLAB]);
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id) VALUES
      ($1,$2,'Gestora A','gestor','ativo',$1),
      ($3,$4,'Gestora B','gestor','ativo',$3),
      ($5,$2,'Colaboradora','colaborador','ativo',$5)`,
    [GESTORA, EMPRESA, GESTORA_OUTRA, OUTRA, COLAB],
  );
  await pool.query(
    "INSERT INTO public.clients (id,company_id,name) VALUES ($1,$2,'Cliente A'), ($3,$4,'Cliente B')",
    [CLIENTE_A, EMPRESA, CLIENTE_B, OUTRA],
  );
  const { rows } = await pool.query(
    "INSERT INTO public.crm_leads (company_id, name) VALUES ($1,'Condomínio Alfa') RETURNING id",
    [EMPRESA],
  );
  leadA = rows[0].id as string;
}

const ITENS = JSON.stringify([
  { description: "Limpeza de escadas", quantity: 1, unit: "servico", unit_price: 100 },
]);

/** `create_crm_quote_with_items` com os 19 argumentos, pela ordem da assinatura. */
async function criar(
  c: pg.Pool | pg.Client,
  over: { leadId?: string | null; clientId?: string | null; empresa?: string; ano?: number } = {},
): Promise<{ id: string; numero: string }> {
  const { rows } = await c.query(
    `SELECT * FROM public.create_crm_quote_with_items(
       $1,$2,$3,NULL,'ORC',$4,CURRENT_DATE,CURRENT_DATE + 30,
       'pontual',0,true,23,NULL,NULL,NULL,NULL,NULL,$5,$6::jsonb)`,
    [
      over.empresa ?? EMPRESA,
      over.leadId === undefined ? leadA : over.leadId,
      over.clientId ?? null,
      over.ano ?? ANO,
      GESTORA,
      ITENS,
    ],
  );
  return { id: rows[0].quote_id as string, numero: rows[0].quote_number as string };
}

async function ligacao(): Promise<pg.Client> {
  const c = new pg.Client({ ...container.connection });
  await c.connect();
  return c;
}

beforeAll(async () => {
  container = await startPostgresContainer({ name: CONTAINER, database: "crm103", memory: "512m" });
  pool = new pg.Pool({ ...container.connection, max: 8 });
}, 180_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechado */ });
  container?.stop();
});

// ---------------------------------------------------------------------------
describe("clean install sobre a cadeia real", () => {
  it("aplica sobre 101 + 101a + 101b + 102", LENTO, async () => {
    await palco(true);
    const { rows } = await pool.query(`
      SELECT to_regclass('public.crm_quotes') AS q,
             to_regclass('public.crm_quote_items') AS i`);
    expect(rows[0].q).toBe("crm_quotes");
    expect(rows[0].i).toBe("crm_quote_items");
  });

  it("cria um orçamento numerado", LENTO, async () => {
    await palco(true);
    const q = await criar(pool);
    expect(q.numero).toBe("ORC2026/001");
  });
});

// ---------------------------------------------------------------------------
describe("proveniência — a 103 não adopta o que não criou", () => {
  it("🔴 EFFECT_WITHOUT_LEDGER: crm_quotes existe sem a 103 no ledger", LENTO, async () => {
    await palco(false);
    await pool.query("CREATE TABLE public.crm_quotes (id uuid PRIMARY KEY, alheia text)");

    await expect(pool.query(lerSql(M_103))).rejects.toThrow(/EFFECT_WITHOUT_LEDGER/);

    const { rows } = await pool.query(`
      SELECT (SELECT coalesce(array_agg(column_name::text ORDER BY column_name), '{}')
                FROM information_schema.columns
               WHERE table_schema='public' AND table_name='crm_quotes') AS colunas,
             (SELECT count(*)::int FROM pg_policies
               WHERE schemaname='public' AND tablename='crm_quotes') AS politicas`);
    expect(rows[0].colunas).toEqual(["alheia", "id"]);
    expect(rows[0].politicas).toBe(0);
  });

  it("🔴 LEDGER_WITHOUT_EFFECT tem nome próprio", LENTO, async () => {
    await palco(true);
    await pool.query("DROP TABLE public.crm_quote_items; DROP TABLE public.crm_quotes;");
    await expect(pool.query(lerSql(M_103))).rejects.toThrow(/LEDGER_WITHOUT_EFFECT/);
  });

  it("🔴 JA_APLICADA: não corre duas vezes", LENTO, async () => {
    await palco(true);
    await expect(pool.query(lerSql(M_103))).rejects.toThrow(/JA_APLICADA/);
  });

  it("🔴 MISSING_PREREQUISITE_LEDGER: sem a linha da 102", LENTO, async () => {
    await palco(false);
    await pool.query("DELETE FROM public._migrations WHERE name=$1", [NOME_102]);
    await expect(pool.query(lerSql(M_103))).rejects.toThrow(/MISSING_PREREQUISITE_LEDGER/);
  });

  it("🔴 CHECKSUM_MISMATCH: a 102 com outro conteúdo", LENTO, async () => {
    await palco(false);
    await pool.query("UPDATE public._migrations SET checksum=$1 WHERE name=$2",
      ["0".repeat(64), NOME_102]);
    await expect(pool.query(lerSql(M_103))).rejects.toThrow(/CHECKSUM_MISMATCH_PREREQUISITE/);
  });

  it("🔴 checksum NULL conta como errado", LENTO, async () => {
    await palco(false);
    await pool.query("UPDATE public._migrations SET checksum=NULL WHERE name=$1", [NOME_102]);
    await expect(pool.query(lerSql(M_103))).rejects.toThrow(/CHECKSUM_MISMATCH_PREREQUISITE/);
  });

  it("sem tabela de ledger, não corre", LENTO, async () => {
    await palco(false);
    await pool.query("DROP TABLE public._migrations");
    await expect(pool.query(lerSql(M_103))).rejects.toThrow(/LEDGER_AUSENTE/);
  });
});

// ---------------------------------------------------------------------------
// 🔴 EFEITO PARCIAL. Uma aplicação interrompida a meio, ou um rollback manual
//    que apagou a tabela e esqueceu as RPC, deixa metade da 103 de pé. Um
//    portão que só perguntasse por `crm_quotes` adoptava esse meio-estado — e
//    um `CREATE OR REPLACE FUNCTION` por cima de uma RPC de outra versão não
//    dá erro nenhum, fica só errado.
// ---------------------------------------------------------------------------
describe("efeito parcial também é efeito", () => {
  /** Cada vestígio exclusivo da 103, sozinho, tem de travar a migration. */
  const VESTIGIOS: ReadonlyArray<readonly [string, string]> = [
    ["só a tabela de linhas", `
      CREATE TABLE public.crm_quote_items (id uuid PRIMARY KEY)`],
    ["só um índice exclusivo", `
      CREATE TABLE public.sobra_103 (id uuid, company_id uuid);
      CREATE UNIQUE INDEX uq_crm_quotes_numero ON public.sobra_103 (id)`],
    ["só a RPC de criação", `
      CREATE FUNCTION public.create_crm_quote_with_items(
        p_company_id uuid, p_lead_id uuid, p_client_id uuid, p_visit_id uuid,
        p_prefix text, p_year integer, p_issue_date date, p_valid_until date,
        p_pricing_kind text, p_discount_pct numeric, p_apply_vat boolean,
        p_vat_rate numeric, p_proposed_frequency text, p_proposed_weekdays jsonb,
        p_payment_terms text, p_notes text, p_internal_notes text, p_actor uuid,
        p_items jsonb)
      RETURNS TABLE (quote_id uuid, quote_number text)
      LANGUAGE sql AS $f$ SELECT NULL::uuid, NULL::text $f$`],
    ["só o trigger de proveniência", `
      CREATE FUNCTION public.crm_quotes_proveniencia_imutavel()
      RETURNS trigger LANGUAGE plpgsql AS $f$ BEGIN RETURN NEW; END; $f$`],
  ];

  for (const [nome, ddl] of VESTIGIOS) {
    it(`🔴 ${nome}: REJEITADO, e o vestígio fica intacto`, LENTO, async () => {
      await palco(false);
      await pool.query(ddl);

      await expect(pool.query(lerSql(M_103)))
        .rejects.toThrow(/EFFECT_WITHOUT_LEDGER/);

      // Zero mutações: a tabela principal não chegou a nascer.
      const { rows } = await pool.query(`
        SELECT to_regclass('public.crm_quotes') AS q,
               (SELECT count(*)::int FROM public._migrations
                 WHERE name=$1) AS ledger`, [NOME_103]);
      expect(rows[0].q).toBeNull();
      expect(rows[0].ledger).toBe(0);
    });
  }

  // 🔴 A ÚNICA excepção, e tem de ser provada como excepção.
  //
  //    O rollback deixa `company_settings.quote_prefix` de propósito. Se essa
  //    coluna contasse como efeito parcial, o estado normal depois de um
  //    rollback limpo seria lido como meio-aplicado e a 103 nunca mais poderia
  //    ser reaplicada — um portão que se tranca a si próprio.
  it("quote_prefix sozinho NÃO conta como efeito — é a excepção documentada", LENTO, async () => {
    await palco(false);
    await pool.query(
      "ALTER TABLE public.company_settings ADD COLUMN IF NOT EXISTS quote_prefix text NOT NULL DEFAULT 'ORC'");

    await pool.query(lerSql(M_103));
    const { rows } = await pool.query("SELECT to_regclass('public.crm_quotes') AS q");
    expect(rows[0].q).toBe("crm_quotes");
  });
});

// ---------------------------------------------------------------------------
// 🔴 SOURCE_LEAD_IMMUTABILITY. A versão da branch ampla só protegia quando
//    `OLD.source_lead_id IS NOT NULL`, para deixar passar um backfill. Isso
//    abria `NULL → valor`: um caminho de escrita futuro podia atribuir a um
//    orçamento uma lead de origem que ele nunca teve, meses depois, sem rasto.
// ---------------------------------------------------------------------------
describe("proveniência do orçamento não se reescreve", () => {
  beforeEach(async () => { await palco(true); }, 120_000);

  it("nasce igual à lead de origem", LENTO, async () => {
    const q = await criar(pool);
    const { rows } = await pool.query(
      "SELECT source_lead_id FROM public.crm_quotes WHERE id=$1", [q.id]);
    expect(rows[0].source_lead_id).toBe(leadA);
  });

  it("🔴 valor → outro: REJECT", LENTO, async () => {
    const q = await criar(pool);
    const { rows } = await pool.query(
      "INSERT INTO public.crm_leads (company_id,name) VALUES ($1,'Outra') RETURNING id", [EMPRESA]);
    await expect(
      pool.query("UPDATE public.crm_quotes SET source_lead_id=$1 WHERE id=$2", [rows[0].id, q.id]),
    ).rejects.toThrow(/QUOTE_SOURCE_LEAD_IMMUTABLE/);
  });

  it("🔴 valor → NULL: REJECT", LENTO, async () => {
    const q = await criar(pool);
    await expect(
      pool.query("UPDATE public.crm_quotes SET source_lead_id=NULL WHERE id=$1", [q.id]),
    ).rejects.toThrow(/QUOTE_SOURCE_LEAD_IMMUTABLE/);
  });

  it("🔴 NULL → valor: REJECT — era a brecha do backfill", LENTO, async () => {
    // Um orçamento a um cliente nasce sem lead de origem.
    const q = await criar(pool, { leadId: null, clientId: CLIENTE_A });
    const { rows: antes } = await pool.query(
      "SELECT source_lead_id FROM public.crm_quotes WHERE id=$1", [q.id]);
    expect(antes[0].source_lead_id).toBeNull();

    await expect(
      pool.query("UPDATE public.crm_quotes SET source_lead_id=$1 WHERE id=$2", [leadA, q.id]),
    ).rejects.toThrow(/QUOTE_SOURCE_LEAD_IMMUTABLE/);
  });

  it("NULL → NULL: passa (não é mudança)", LENTO, async () => {
    const q = await criar(pool, { leadId: null, clientId: CLIENTE_A });
    await pool.query("UPDATE public.crm_quotes SET notes='sem tocar na origem' WHERE id=$1", [q.id]);
    const { rows } = await pool.query(
      "SELECT source_lead_id, notes FROM public.crm_quotes WHERE id=$1", [q.id]);
    expect(rows[0].source_lead_id).toBeNull();
    expect(rows[0].notes).toBe("sem tocar na origem");
  });
});

// ---------------------------------------------------------------------------
// 🔴 NUMERAÇÃO CONCORRENTE. Sem o `pg_advisory_xact_lock`, duas criações
//    simultâneas leem o mesmo MAX e pedem o mesmo `quote_seq`. O índice único
//    apanharia a colisão — mas como erro incompreensível ao utilizador, e
//    repetível a cada tentativa.
// ---------------------------------------------------------------------------
describe("numeração concorrente", () => {
  beforeEach(async () => { await palco(true); }, 120_000);

  it("🔴 duas criações simultâneas: números diferentes e consecutivos", LENTO, async () => {
    const a = await ligacao();
    const b = await ligacao();
    try {
      await a.query("BEGIN");
      await b.query("BEGIN");

      // A pega no lock da empresa+ano e segura-o até ao commit.
      const qa = await criar(a);

      // B arranca e fica pendurado no advisory lock.
      const pendenteB = criar(b);
      await new Promise((r) => setTimeout(r, 600));
      await a.query("COMMIT");

      const qb = await pendenteB;
      await b.query("COMMIT");

      expect(qa.numero).not.toBe(qb.numero);
      expect([qa.numero, qb.numero].sort()).toEqual(["ORC2026/001", "ORC2026/002"]);
    } finally {
      await a.end().catch(() => { /* já fechada */ });
      await b.end().catch(() => { /* já fechada */ });
    }

    const { rows } = await pool.query(
      "SELECT array_agg(DISTINCT quote_seq ORDER BY quote_seq) AS seqs FROM public.crm_quotes");
    expect(rows[0].seqs.map(Number)).toEqual([1, 2]);
  });

  it("🔴 uma revisão NÃO consome sequencial", LENTO, async () => {
    const q1 = await criar(pool);
    expect(q1.numero).toBe("ORC2026/001");

    await pool.query(
      "SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, q1.id, GESTORA]);

    const { rows: rev } = await pool.query(
      `SELECT * FROM public.revise_crm_quote(
         $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, q1.id, GESTORA, ITENS]);
    expect(rev[0].quote_number).toBe("ORC2026/001-R1");

    const q2 = await criar(pool);
    expect(q2.numero).toBe("ORC2026/002");
  });
});

// ---------------------------------------------------------------------------
// 🔴 REVISÕES CONCORRENTES. Duas pessoas a rever a mesma revisão viva: se as
//    duas ganhassem, a raiz ficava com dois ramos vivos e ninguém saberia qual
//    é o orçamento em vigor.
// ---------------------------------------------------------------------------
describe("revisões concorrentes", () => {
  beforeEach(async () => { await palco(true); }, 120_000);

  it("🔴 duas revisões da mesma revisão viva: só uma ganha", LENTO, async () => {
    const q1 = await criar(pool);
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
      [EMPRESA, q1.id, GESTORA]);

    const a = await ligacao();
    const b = await ligacao();
    let resultadoB: string | null = null;

    try {
      await a.query("BEGIN");
      await b.query("BEGIN");

      const revA = await a.query(
        `SELECT * FROM public.revise_crm_quote(
           $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
        [EMPRESA, q1.id, GESTORA, ITENS]);
      expect(revA.rows[0].quote_number).toBe("ORC2026/001-R1");

      const pendenteB = b.query(
        `SELECT * FROM public.revise_crm_quote(
           $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
        [EMPRESA, q1.id, GESTORA, ITENS],
      ).then(() => "passou").catch((e: Error) => e.message);

      await new Promise((r) => setTimeout(r, 600));
      await a.query("COMMIT");

      resultadoB = await pendenteB;
      await b.query("COMMIT").catch(() => b.query("ROLLBACK"));
    } finally {
      await a.end().catch(() => { /* já fechada */ });
      await b.end().catch(() => { /* já fechada */ });
    }

    // B não pode ter criado um segundo ramo vivo.
    expect(resultadoB).not.toBe("passou");

    const { rows } = await pool.query(
      `SELECT count(*)::int n FROM public.crm_quotes
        WHERE quote_seq = 1 AND superseded_by_id IS NULL`);
    expect(rows[0].n, "mais do que uma revisão viva na mesma raiz").toBe(1);
  });

  it("o índice de revisão viva existe e é único", LENTO, async () => {
    const { rows } = await pool.query(`
      SELECT indexdef FROM pg_indexes
       WHERE schemaname='public' AND indexname='uq_crm_quotes_revisao_viva'`);
    expect(rows).toHaveLength(1);
    expect(rows[0].indexdef).toContain("UNIQUE");
  });
});

// ---------------------------------------------------------------------------
describe("isolamento por empresa, RLS e ACL", () => {
  beforeEach(async () => { await palco(true); }, 120_000);

  it("🔴 lead de outra empresa: recusado", LENTO, async () => {
    const { rows } = await pool.query(
      "INSERT INTO public.crm_leads (company_id,name) VALUES ($1,'Da B') RETURNING id", [OUTRA]);
    await expect(criar(pool, { leadId: rows[0].id })).rejects.toThrow();
  });

  it("🔴 cliente de outra empresa: recusado", LENTO, async () => {
    await expect(criar(pool, { leadId: null, clientId: CLIENTE_B })).rejects.toThrow();
  });

  it("RLS está activa nas duas tabelas", LENTO, async () => {
    const { rows } = await pool.query(`
      SELECT c.relname, c.relrowsecurity FROM pg_class c
        JOIN pg_namespace n ON n.oid=c.relnamespace
       WHERE n.nspname='public' AND c.relname IN ('crm_quotes','crm_quote_items')
       ORDER BY c.relname`);
    expect(rows.map((r) => [r.relname, r.relrowsecurity]))
      .toEqual([["crm_quote_items", true], ["crm_quotes", true]]);
  });

  it("🔴 a gestora da outra empresa não vê estes orçamentos", LENTO, async () => {
    await criar(pool);
    const c = await ligacao();
    try {
      await c.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [GESTORA_OUTRA]);
      await c.query("SET ROLE authenticated");
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_quotes");
      expect(rows[0].n).toBe(0);
    } finally { await c.end(); }
  });

  it("🔴 uma colaboradora não vê orçamentos", LENTO, async () => {
    await criar(pool);
    const c = await ligacao();
    try {
      await c.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [COLAB]);
      await c.query("SET ROLE authenticated");
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_quotes");
      expect(rows[0].n).toBe(0);
    } finally { await c.end(); }
  });

  it("a gestora da empresa vê os seus", LENTO, async () => {
    await criar(pool);
    const c = await ligacao();
    try {
      await c.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [GESTORA]);
      await c.query("SET ROLE authenticated");
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_quotes");
      expect(rows[0].n).toBe(1);
    } finally { await c.end(); }
  });

  it("ACL: authenticated só lê, service_role escreve, anon e PUBLIC nada", LENTO, async () => {
    for (const t of ["crm_quotes", "crm_quote_items"]) {
      const { rows } = await pool.query(
        `SELECT
           has_table_privilege('authenticated', $1, 'SELECT') AS auth_select,
           has_table_privilege('authenticated', $1, 'INSERT') AS auth_insert,
           has_table_privilege('service_role',  $1, 'INSERT') AS sr_insert,
           has_table_privilege('service_role',  $1, 'DELETE') AS sr_delete,
           has_table_privilege('anon',          $1, 'SELECT') AS anon_select`,
        [`public.${t}`]);
      expect(rows[0].auth_select, `${t}: authenticated devia ler`).toBe(true);
      expect(rows[0].auth_insert, `${t}: authenticated NÃO escreve`).toBe(false);
      expect(rows[0].sr_insert).toBe(true);
      expect(rows[0].sr_delete).toBe(true);
      expect(rows[0].anon_select, `${t}: anon não chega`).toBe(false);

      const { rows: pub } = await pool.query(
        `SELECT coalesce(string_agg(DISTINCT privilege_type, ','), 'NONE') AS p
           FROM information_schema.role_table_grants
          WHERE table_schema='public' AND table_name=$1 AND grantee='PUBLIC'`, [t]);
      expect(pub[0].p).toBe("NONE");
    }
  });

  it("🔴 as três RPC: assinatura exacta, SECURITY INVOKER, sem EXECUTE para PUBLIC", LENTO, async () => {
    // 🔴 Com NOMES, e não só tipos. As Server Actions chamam estas RPC por
    //    parâmetro nomeado: trocar `p_lead_id` por `p_leadid` não muda a
    //    assinatura por tipos e parte todas as chamadas em runtime.
    const esperadas: Record<string, string> = {
      create_crm_quote_with_items:
        "p_company_id uuid, p_lead_id uuid, p_client_id uuid, p_visit_id uuid, "
        + "p_prefix text, p_year integer, p_issue_date date, p_valid_until date, "
        + "p_pricing_kind text, p_discount_pct numeric, p_apply_vat boolean, "
        + "p_vat_rate numeric, p_proposed_frequency text, p_proposed_weekdays jsonb, "
        + "p_payment_terms text, p_notes text, p_internal_notes text, p_actor uuid, "
        + "p_items jsonb",
      revise_crm_quote:
        "p_company_id uuid, p_quote_id uuid, p_actor uuid, p_issue_date date, "
        + "p_valid_until date, p_discount_pct numeric, p_apply_vat boolean, "
        + "p_vat_rate numeric, p_notes text, p_items jsonb",
      set_crm_quote_status:
        "p_company_id uuid, p_quote_id uuid, p_actor uuid, p_status text, p_reason text",
    };

    for (const [nome, args] of Object.entries(esperadas)) {
      const { rows } = await pool.query(
        `SELECT pg_get_function_identity_arguments(p.oid) AS args,
                p.prosecdef AS definer,
                has_function_privilege('public', p.oid, 'EXECUTE') AS pub_exec,
                has_function_privilege('service_role', p.oid, 'EXECUTE') AS sr_exec
           FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
          WHERE n.nspname='public' AND p.proname=$1`, [nome]);

      expect(rows, `${nome} não existe (ou está duplicada)`).toHaveLength(1);
      expect(rows[0].args, `${nome}: assinatura mudou`).toBe(args);
      expect(rows[0].definer, `${nome} tem de ser SECURITY INVOKER`).toBe(false);
      expect(rows[0].pub_exec, `${nome}: PUBLIC não pode executar`).toBe(false);
      expect(rows[0].sr_exec, `${nome}: service_role tem de executar`).toBe(true);
    }
  });
});

// ---------------------------------------------------------------------------
describe("rollback", () => {
  const linhaLedger = async (): Promise<number> => {
    const { rows } = await pool.query(
      "SELECT count(*)::int n FROM public._migrations WHERE name=$1", [NOME_103]);
    return rows[0].n as number;
  };

  it("ROLLBACK_EMPTY: sem documentos e com prefixo intacto — desfaz tudo", LENTO, async () => {
    await palco(true);
    expect(await linhaLedger()).toBe(1);

    await pool.query(lerSql(ROLLBACK_103));

    const { rows } = await pool.query(`
      SELECT to_regclass('public.crm_quotes') AS q,
             to_regclass('public.crm_quote_items') AS i,
             to_regclass('public.crm_visits') AS v,
             to_regprocedure('public.crm_quotes_proveniencia_imutavel()') AS trg`);
    expect(rows[0].q).toBeNull();
    expect(rows[0].i).toBeNull();
    // 🔴 A 102 não vai atrás.
    expect(rows[0].v).toBe("crm_visits");
    expect(rows[0].trg).toBeNull();
    expect(await linhaLedger()).toBe(0);
  });

  it("🔴 ROLLBACK_WITH_DATA: um orçamento — RECUSADO, e nada se perde", LENTO, async () => {
    await palco(true);
    const q = await criar(pool);

    await expect(pool.query(lerSql(ROLLBACK_103))).rejects.toThrow(/ROLLBACK_RECUSADO/);

    const { rows } = await pool.query(
      "SELECT quote_number FROM public.crm_quotes WHERE id=$1", [q.id]);
    expect(rows).toHaveLength(1);
    expect(rows[0].quote_number).toBe("ORC2026/001");

    const { rows: itens } = await pool.query(
      "SELECT count(*)::int n FROM public.crm_quote_items WHERE quote_id=$1", [q.id]);
    expect(itens[0].n).toBeGreaterThan(0);

    expect(await linhaLedger(), "ledger intacto").toBe(1);
  });

  it("🔴 ROLLBACK_CONFIG_CHANGED: prefixo configurado — RECUSADO", LENTO, async () => {
    await palco(true);
    // Sem documentos nenhuns: só a configuração é que mudou.
    await pool.query("UPDATE public.company_settings SET quote_prefix='PROP' WHERE company_id=$1",
      [EMPRESA]);

    await expect(pool.query(lerSql(ROLLBACK_103))).rejects.toThrow(/ROLLBACK_CONFIG_ALTERADA/);

    const { rows } = await pool.query("SELECT to_regclass('public.crm_quotes') AS q");
    expect(rows[0].q).toBe("crm_quotes");
    expect(await linhaLedger(), "ledger intacto").toBe(1);

    const { rows: cfg } = await pool.query(
      "SELECT quote_prefix FROM public.company_settings WHERE company_id=$1", [EMPRESA]);
    expect(cfg[0].quote_prefix, "configuração preservada").toBe("PROP");
  });

  // -------------------------------------------------------------------------
  // 🔴 ROLLBACK_CONFIG_GUARD_ATOMIC.
  //
  //    Verificar o prefixo e desfazer a 103 são duas coisas; sem lock, cabe
  //    uma escrita entre elas:
  //
  //      T1 lê quote_prefix = 'ORC'  →  T2 grava 'PROP'  →  T1 desfaz a 103
  //
  //    T1 decidiu com informação velha: desfez sobre uma configuração que
  //    entretanto passou a existir. O `LOCK TABLE company_settings IN SHARE
  //    MODE` antes da leitura fecha a janela — o `UPDATE` de T2 espera.
  // -------------------------------------------------------------------------
  it("🔴 ROLLBACK_CONFIG_GUARD_ATOMIC: o prefixo não muda entre a guarda e o DROP", LENTO, async () => {
    await palco(true);

    const desfazedor = await ligacao();
    const utilizador = await ligacao();
    let resultadoUpdate: string | null = null;

    try {
      await desfazedor.query("BEGIN");

      // O rollback corre inteiro dentro da transação: pega no SHARE de
      // company_settings, conta, e larga as tabelas. Ainda não commitou.
      await desfazedor.query(lerSql(ROLLBACK_103));

      // Só agora o utilizador tenta configurar o prefixo. Fica à espera do
      // lock — não consegue entrar entre a guarda e o DROP.
      const pendente = utilizador.query(
        "UPDATE public.company_settings SET quote_prefix='PROP' WHERE company_id=$1",
        [EMPRESA],
      ).then(() => "entrou").catch((e: Error) => e.message);

      await new Promise((r) => setTimeout(r, 800));

      // A prova: enquanto o rollback segura o lock, o UPDATE não passou.
      const aindaPendente = await Promise.race([
        pendente,
        new Promise<string>((r) => setTimeout(() => r("ainda a espera"), 400)),
      ]);
      expect(aindaPendente, "o UPDATE entrou no meio do rollback").toBe("ainda a espera");

      await desfazedor.query("COMMIT");
      resultadoUpdate = await pendente;
    } finally {
      await desfazedor.end().catch(() => { /* já fechada */ });
      await utilizador.end().catch(() => { /* já fechada */ });
    }

    // Depois do commit o UPDATE segue — a 103 já foi desfeita com a leitura
    // que era verdade no momento da decisão.
    expect(resultadoUpdate).toBe("entrou");

    const { rows } = await pool.query(`
      SELECT to_regclass('public.crm_quotes') AS q,
             (SELECT quote_prefix FROM public.company_settings WHERE company_id=$1) AS prefixo`,
      [EMPRESA]);
    expect(rows[0].q).toBeNull();
    expect(rows[0].prefixo).toBe("PROP");
    expect(await linhaLedger()).toBe(0);
  });

  it("🔴 tabela alheia não é apagada por este rollback", LENTO, async () => {
    await palco(false);
    await pool.query("CREATE TABLE public.crm_quotes (id uuid PRIMARY KEY)");
    await expect(pool.query(lerSql(ROLLBACK_103))).rejects.toThrow(/TABELA_ALIENADA/);
    const { rows } = await pool.query("SELECT to_regclass('public.crm_quotes') AS q");
    expect(rows[0].q).toBe("crm_quotes");
  });

  it("🔴 ledger sem efeito não é arrumado em silêncio", LENTO, async () => {
    await palco(true);
    await pool.query("DROP TABLE public.crm_quote_items; DROP TABLE public.crm_quotes;");
    await expect(pool.query(lerSql(ROLLBACK_103)))
      .rejects.toThrow(/ROLLBACK_LEDGER_WITHOUT_EFFECT/);
    expect(await linhaLedger()).toBe(1);
  });

  it("🔴 checksum divergente: não desfaz o que não conhece", LENTO, async () => {
    await palco(true);
    await pool.query("UPDATE public._migrations SET checksum=$1 WHERE name=$2",
      ["0".repeat(64), NOME_103]);
    await expect(pool.query(lerSql(ROLLBACK_103)))
      .rejects.toThrow(/ROLLBACK_CHECKSUM_DIVERGENTE/);
  });

  it("sem tabela nem linha: no-op idempotente", LENTO, async () => {
    await palco(true);
    await pool.query(lerSql(ROLLBACK_103));
    await pool.query(lerSql(ROLLBACK_103));
    expect(await linhaLedger()).toBe(0);
  });

  it("depois do rollback, a 103 volta a aplicar-se com o prefixo já presente", LENTO, async () => {
    await palco(true);
    await pool.query(lerSql(ROLLBACK_103));

    // A coluna ficou — é a decisão documentada. Reaplicar tem de funcionar.
    const { rows: antes } = await pool.query(`
      SELECT count(*)::int n FROM information_schema.columns
       WHERE table_schema='public' AND table_name='company_settings' AND column_name='quote_prefix'`);
    expect(antes[0].n).toBe(1);

    await pool.query(lerSql(M_103));
    const { rows } = await pool.query("SELECT to_regclass('public.crm_quotes') AS q");
    expect(rows[0].q).toBe("crm_quotes");
  });
});
