// ============================================================================
// 103a — a ACL das RPC de orçamentos, lida por dentro
// ============================================================================
//
// 🔴 O defeito, e porque é que a pós-validação da 103 não o viu.
//
//    A 103 fez `REVOKE ALL ... FROM PUBLIC` e deu-se por satisfeita. Mas os
//    DEFAULT PRIVILEGES do schema dão `EXECUTE` NOMINAL a `anon`,
//    `authenticated` e `service_role` a cada `CREATE FUNCTION`, e revogar do
//    PUBLIC não lhes toca:
//
//        proacl = postgres=X | anon=X | authenticated=X | service_role=X
//
//    A verificação que deixou isto passar usava
//    `has_function_privilege('public', ...)`, que responde sobre o PUBLIC
//    implícito — e diz «não» enquanto `anon` tem um grant nominal a dizer
//    «sim». Por isso esta suite lê a ACL por `aclexplode`, nome a nome.
//
// O palco monta a cadeia real até à 103 e mede DUAS vezes: antes do hotfix
// (para provar que o defeito existe) e depois (para provar que fechou). Um
// ensaio que só medisse o depois não distinguiria uma correcção de uma
// migration que não faz nada.
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";

const CONTAINER = `crm103a-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const CLIENTE_A = "c1111111-1111-4111-8111-111111111111";

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_102 = "supabase/migrations/102_crm_visitas_comerciais.sql";
const M_103 = "supabase/migrations/103_crm_orcamentos.sql";
const M_103A = "supabase/migrations/103a_crm_rpc_acl_hardening.sql";
const ROLLBACK_103A = "supabase/migrations/rollback/103a_crm_rpc_acl_hardening.down.sql";

const NOME_102 = "102_crm_visitas_comerciais.sql";
const NOME_103 = "103_crm_orcamentos.sql";
const NOME_103A = "103a_crm_rpc_acl_hardening.sql";

/** As assinaturas exactas — é por elas que a migration identifica as RPC. */
const RPCS = [
  "public.create_crm_quote_with_items(uuid, uuid, uuid, uuid, text, integer, date, date, text, numeric, boolean, numeric, text, jsonb, text, text, text, uuid, jsonb)",
  "public.revise_crm_quote(uuid, uuid, uuid, date, date, numeric, boolean, numeric, text, jsonb)",
  "public.set_crm_quote_status(uuid, uuid, uuid, text, text)",
] as const;

let container: PostgresContainer;
let pool: pg.Pool;
let leadA = "";

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

const checksumLf = (ficheiro: string): string =>
  createHash("sha256")
    .update(lerSql(`supabase/migrations/${ficheiro}`).split("\r\n").join("\n").split("\r").join("\n"))
    .digest("hex");

/**
 * Quem tem EXECUTE, lido por dentro da ACL.
 *
 * 🔴 `aclexplode`, e não `has_function_privilege`. É esta a diferença que
 *    deixou o defeito passar despercebido.
 */
async function quemExecuta(assinatura: string): Promise<string[]> {
  const { rows } = await pool.query(
    `SELECT coalesce(g.rolname, 'PUBLIC') AS grantee
       FROM pg_proc p
       CROSS JOIN LATERAL aclexplode(p.proacl) a
       LEFT JOIN pg_roles g ON g.oid = a.grantee
      WHERE p.oid = $1::regprocedure AND a.privilege_type = 'EXECUTE'
      ORDER BY grantee`,
    [assinatura],
  );
  return rows.map((r) => r.grantee as string);
}

async function searchPathDe(assinatura: string): Promise<string | null> {
  const { rows } = await pool.query(
    `SELECT (SELECT cfg FROM unnest(coalesce(p.proconfig, '{}')) cfg
              WHERE cfg LIKE 'search_path=%') AS sp
       FROM pg_proc p WHERE p.oid = $1::regprocedure`,
    [assinatura],
  );
  return (rows[0]?.sp as string | null) ?? null;
}

/** A cadeia real até à 103, com o ledger que os portões exigem. */
async function palco(aplicar103a: boolean): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);

  // 🔴 É ESTA linha que cria o defeito. São os DEFAULT PRIVILEGES reais do
  //    schema em produção: cada CREATE FUNCTION nasce com grants nominais.
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);

  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await pool.query(lerSql(M_101B));

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public._migrations (
      name text PRIMARY KEY, checksum text, applied_at timestamptz NOT NULL DEFAULT now())`);
  for (const n of ["101_crm_leads.sql", "101a_crm_rpc_acl_hardening.sql", "101b_identity_reconciliation.sql"]) {
    await pool.query("INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)", [n, checksumLf(n)]);
  }

  await pool.query(lerSql(M_102));
  await pool.query("INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)",
    [NOME_102, checksumLf(NOME_102)]);

  await semear();

  await pool.query(lerSql(M_103));
  await pool.query("INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)",
    [NOME_103, checksumLf(NOME_103)]);

  if (aplicar103a) {
    await pool.query(lerSql(M_103A));
    await pool.query("INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)",
      [NOME_103A, checksumLf(NOME_103A)]);
  }
}

async function semear(): Promise<void> {
  await pool.query("INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a')", [EMPRESA]);
  await pool.query("INSERT INTO public.company_settings (company_id) VALUES ($1)", [EMPRESA]);
  await pool.query("INSERT INTO auth.users (id,email) VALUES ($1,'g@a.pt')", [GESTORA]);
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id)
     VALUES ($1,$2,'Gestora A','gestor','ativo',$1)`, [GESTORA, EMPRESA]);
  await pool.query("INSERT INTO public.clients (id,company_id,name) VALUES ($1,$2,'Cliente A')",
    [CLIENTE_A, EMPRESA]);
  const { rows } = await pool.query(
    "INSERT INTO public.crm_leads (company_id, name) VALUES ($1,'Condomínio Alfa') RETURNING id", [EMPRESA]);
  leadA = rows[0].id as string;
}

const ITENS = JSON.stringify([
  { description: "Limpeza de escadas", quantity: 1, unit: "servico", unit_price: 100 },
]);

beforeAll(async () => {
  container = await startPostgresContainer({ name: CONTAINER, database: "crm103a", memory: "512m" });
  pool = new pg.Pool({ ...container.connection, max: 6 });
}, 180_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechado */ });
  container?.stop();
});

// ---------------------------------------------------------------------------
// 🔴 O DEFEITO EXISTE. Sem este bloco, a 103a podia não fazer nada e a suite
//    ficava verde na mesma.
// ---------------------------------------------------------------------------
describe("antes do hotfix: a ACL está aberta", () => {
  beforeEach(async () => { await palco(false); }, 120_000);

  it.each(RPCS)("🔴 anon e authenticated têm EXECUTE nominal em %s", LENTO, async (rpc) => {
    const quem = await quemExecuta(rpc);
    expect(quem, "o defeito que a 103a existe para fechar").toEqual(
      expect.arrayContaining(["anon", "authenticated"]),
    );
  });

  it("🔴 e o REVOKE FROM PUBLIC da 103 não chegou lá", LENTO, async () => {
    // PUBLIC fora — a 103 fez isso. Os nominais é que ficaram.
    for (const rpc of RPCS) {
      const quem = await quemExecuta(rpc);
      expect(quem).not.toContain("PUBLIC");
      expect(quem).toContain("anon");
    }
  });

  it("o search_path não está fixo", LENTO, async () => {
    for (const rpc of RPCS) expect(await searchPathDe(rpc)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
describe("depois do hotfix: fechada, e só para service_role", () => {
  beforeEach(async () => { await palco(true); }, 120_000);

  it.each(RPCS)("🔴 %s: EXECUTE só para service_role", LENTO, async (rpc) => {
    const quem = await quemExecuta(rpc);
    expect(quem).not.toContain("PUBLIC");
    expect(quem).not.toContain("anon");
    expect(quem).not.toContain("authenticated");
    expect(quem).toContain("service_role");
  });

  it.each(RPCS)("%s: search_path fixo com pg_catalog", LENTO, async (rpc) => {
    expect(await searchPathDe(rpc)).toBe("search_path=pg_catalog, public");
  });

  it.each(RPCS)("%s: continua SECURITY INVOKER e com a assinatura exacta", LENTO, async (rpc) => {
    const { rows } = await pool.query(
      `SELECT p.prosecdef, pg_get_function_identity_arguments(p.oid) AS args
         FROM pg_proc p WHERE p.oid = $1::regprocedure`, [rpc]);
    expect(rows[0].prosecdef, "não pode virar SECURITY DEFINER").toBe(false);
    // A assinatura que o regprocedure resolveu é, por construção, a pedida.
    expect(rows[0].args).toBeTruthy();
  });

  // 🔴 Fechar a porta a `anon` não pode ter fechado a porta à aplicação.
  it("🔴 service_role continua a conseguir invocar as três RPC", LENTO, async () => {
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("SET ROLE service_role");

      const { rows: criado } = await c.query(
        `SELECT * FROM public.create_crm_quote_with_items(
           $1,$2,NULL,NULL,'ORC',2026,CURRENT_DATE,CURRENT_DATE + 30,
           'pontual',0,true,23,NULL,NULL,NULL,NULL,NULL,$3,$4::jsonb)`,
        [EMPRESA, leadA, GESTORA, ITENS]);
      expect(criado[0].quote_number).toBe("ORC2026/001");

      await c.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)",
        [EMPRESA, criado[0].quote_id, GESTORA]);

      const { rows: revisto } = await c.query(
        `SELECT * FROM public.revise_crm_quote(
           $1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
        [EMPRESA, criado[0].quote_id, GESTORA, ITENS]);
      expect(revisto[0].quote_number).toBe("ORC2026/001-R1");
    } finally { await c.end(); }
  });

  it("🔴 anon deixa de poder sequer chamar", LENTO, async () => {
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("SET ROLE anon");
      await expect(
        c.query(`SELECT * FROM public.create_crm_quote_with_items(
          $1,$2,NULL,NULL,'ORC',2026,CURRENT_DATE,CURRENT_DATE + 30,
          'pontual',0,true,23,NULL,NULL,NULL,NULL,NULL,$3,$4::jsonb)`,
        [EMPRESA, leadA, GESTORA, ITENS]),
      ).rejects.toThrow(/permission denied/i);
    } finally { await c.end(); }
  });

  it("a 103 e a sua linha de ledger ficaram intactas", LENTO, async () => {
    const { rows } = await pool.query(
      "SELECT checksum FROM public._migrations WHERE name=$1", [NOME_103]);
    expect(rows[0].checksum).toBe(checksumLf(NOME_103));

    const { rows: t } = await pool.query(`
      SELECT to_regclass('public.crm_quotes') AS q, to_regclass('public.crm_quote_items') AS i`);
    expect(t[0].q).toBe("crm_quotes");
    expect(t[0].i).toBe("crm_quote_items");
  });
});

// ---------------------------------------------------------------------------
describe("proveniência e precondições da 103a", () => {
  it("🔴 sem a 103 no ledger, não corre", LENTO, async () => {
    await palco(false);
    await pool.query("DELETE FROM public._migrations WHERE name=$1", [NOME_103]);
    await expect(pool.query(lerSql(M_103A))).rejects.toThrow(/PRECONDITION_FAILED/);
  });

  it("🔴 com outro checksum da 103, não corre", LENTO, async () => {
    await palco(false);
    await pool.query("UPDATE public._migrations SET checksum=$1 WHERE name=$2",
      ["0".repeat(64), NOME_103]);
    await expect(pool.query(lerSql(M_103A))).rejects.toThrow(/CHECKSUM_MISMATCH_103/);
  });

  it("🔴 JA_APLICADA: não corre duas vezes", LENTO, async () => {
    await palco(true);
    await expect(pool.query(lerSql(M_103A))).rejects.toThrow(/JA_APLICADA/);
  });

  it("🔴 EFFECT_WITHOUT_LEDGER: fechada à mão, sem linha", LENTO, async () => {
    await palco(false);
    await pool.query(lerSql(M_103A)); // aplica o efeito, sem registar
    await expect(pool.query(lerSql(M_103A))).rejects.toThrow(/EFFECT_WITHOUT_LEDGER/);
  });

  it("🔴 LEDGER_WITHOUT_EFFECT: linha presente, endurecimento desfeito", LENTO, async () => {
    await palco(true);
    await pool.query(`GRANT EXECUTE ON FUNCTION ${RPCS[0]} TO anon`);
    await expect(pool.query(lerSql(M_103A))).rejects.toThrow(/LEDGER_WITHOUT_EFFECT/);
  });

  it("sem tabela de ledger, não corre", LENTO, async () => {
    await palco(false);
    await pool.query("DROP TABLE public._migrations");
    await expect(pool.query(lerSql(M_103A))).rejects.toThrow(/LEDGER_AUSENTE/);
  });
});

// ---------------------------------------------------------------------------
// 🔴 O rollback reabre uma porta. Tem de custar mais do que um enter.
// ---------------------------------------------------------------------------
describe("rollback — reabrir exige dizê-lo", () => {
  it("🔴 sem confirmação explícita, recusa", LENTO, async () => {
    await palco(true);
    await expect(pool.query(lerSql(ROLLBACK_103A)))
      .rejects.toThrow(/ROLLBACK_NAO_CONFIRMADO/);

    // E nada mudou.
    expect(await quemExecuta(RPCS[0])).not.toContain("anon");
  });

  it("com confirmação, repõe o estado anterior e apaga a linha", LENTO, async () => {
    await palco(true);
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("BEGIN");
      await c.query("SET LOCAL crm.reabrir_acl_103a = 'confirmo'");
      await c.query(lerSql(ROLLBACK_103A));
      await c.query("COMMIT");
    } finally { await c.end(); }

    for (const rpc of RPCS) {
      expect(await quemExecuta(rpc)).toEqual(expect.arrayContaining(["anon", "authenticated"]));
      expect(await searchPathDe(rpc)).toBeNull();
    }
    const { rows } = await pool.query(
      "SELECT count(*)::int n FROM public._migrations WHERE name=$1", [NOME_103A]);
    expect(rows[0].n).toBe(0);
  });

  it("🔴 o rollback não toca em dados nem em tabelas", LENTO, async () => {
    await palco(true);
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("BEGIN");
      await c.query("SET LOCAL crm.reabrir_acl_103a = 'confirmo'");
      await c.query(lerSql(ROLLBACK_103A));
      await c.query("COMMIT");
    } finally { await c.end(); }

    const { rows } = await pool.query(`
      SELECT to_regclass('public.crm_quotes') AS q,
             to_regclass('public.crm_quote_items') AS i,
             (SELECT count(*)::int FROM public._migrations WHERE name=$1) AS ledger103,
             (SELECT count(*)::int FROM information_schema.columns
               WHERE table_schema='public' AND table_name='company_settings'
                 AND column_name='quote_prefix') AS prefixo`, [NOME_103]);
    expect(rows[0].q).toBe("crm_quotes");
    expect(rows[0].i).toBe("crm_quote_items");
    expect(rows[0].ledger103, "a linha da 103 não é desta migration").toBe(1);
    expect(rows[0].prefixo).toBe(1);
  });

  it("🔴 sem linha de ledger da 103a, o rollback recusa", LENTO, async () => {
    await palco(false);
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("BEGIN");
      await c.query("SET LOCAL crm.reabrir_acl_103a = 'confirmo'");
      await expect(c.query(lerSql(ROLLBACK_103A)))
        .rejects.toThrow(/LEDGER_WITHOUT_ENTRY/);
      await c.query("ROLLBACK");
    } finally { await c.end(); }
  });
});
