// ============================================================================
// 104 — a conversão de uma lead, contra Postgres real
// ============================================================================
//
// 🔴 O palco é a cadeia como está EM PRODUÇÃO hoje:
//
//        baseline canónico + 101 + 101a + 101b + 102 + 103 + 103a  →  104
//
//    A 103a entrou no ledger a 21/09. A 104 depende das duas: converte a
//    partir de um orçamento aceite, e o orçamento é da 103.
//
// ---------------------------------------------------------------------------
// O que só Postgres real responde
// ---------------------------------------------------------------------------
//
//   · duas conversões simultâneas da mesma lead criam UM cliente e UM local;
//   · uma recusa não deixa vestígio nenhum — nem cliente, nem local, nem
//     linha de timeline, nem lead tocada;
//   · a FK composta de três colunas recusa mesmo um par (cliente, local) que
//     as duas FKs da 101 aceitariam;
//   · a ACL e o `search_path` ficam como a 103a ensinou, desde o primeiro dia.
//
// Nenhuma destas se prova com mocks.
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";

const CONTAINER = `crm104-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const OUTRA = "22222222-2222-4222-8222-222222222222";
const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const GESTORA_OUTRA = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const CLIENTE_A = "c1111111-1111-4111-8111-111111111111";
const CLIENTE_B = "c2222222-2222-4222-8222-222222222222";

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_102 = "supabase/migrations/102_crm_visitas_comerciais.sql";
const M_103 = "supabase/migrations/103_crm_orcamentos.sql";
const M_103A = "supabase/migrations/103a_crm_rpc_acl_hardening.sql";
const M_104 = "supabase/migrations/104_crm_conversao_lead.sql";
const ROLLBACK_104 = "supabase/migrations/rollback/104_crm_conversao_lead.down.sql";

const NOME_102 = "102_crm_visitas_comerciais.sql";
const NOME_103 = "103_crm_orcamentos.sql";
const NOME_103A = "103a_crm_rpc_acl_hardening.sql";
const NOME_104 = "104_crm_conversao_lead.sql";

/** A cadeia que a 104 exige ver antes de si. */
const CADEIA = [
  "101_crm_leads.sql",
  "101a_crm_rpc_acl_hardening.sql",
  "101b_identity_reconciliation.sql",
] as const;

const ANO = 2026;

let container: PostgresContainer;
let pool: pg.Pool;
let leadA = "";

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

const checksumLf = (ficheiro: string): string =>
  createHash("sha256")
    .update(lerSql(`supabase/migrations/${ficheiro}`).split("\r\n").join("\n").split("\r").join("\n"))
    .digest("hex");

async function registarNoLedger(nome: string): Promise<void> {
  await pool.query(
    `INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)
     ON CONFLICT (name) DO UPDATE SET checksum = EXCLUDED.checksum`,
    [nome, checksumLf(nome)],
  );
}

/**
 * A cadeia real até à 103a. `aplicar104` fecha o palco com a migration em prova.
 *
 * 🔴 A linha de ledger de cada migration entra DEPOIS de ela correr — é o que
 *    o runner faz, e escrever antes daria `LEDGER_WITHOUT_EFFECT` ao portão
 *    seguinte.
 */
async function palco(aplicar104 = true): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);
  // 🔴 O default privilege que obriga a 104 a revogar `anon`/`authenticated`
  //    explicitamente. Sem isto no palco, a ACL passaria por acidente.
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);

  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await pool.query(lerSql(M_101B));

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public._migrations (
      name text PRIMARY KEY, checksum text, applied_at timestamptz NOT NULL DEFAULT now())`);
  for (const nome of CADEIA) await registarNoLedger(nome);

  await pool.query(lerSql(M_102));
  await registarNoLedger(NOME_102);

  await semear();

  await pool.query(lerSql(M_103));
  await registarNoLedger(NOME_103);
  await pool.query(lerSql(M_103A));
  await registarNoLedger(NOME_103A);

  if (aplicar104) {
    await pool.query(lerSql(M_104));
    await registarNoLedger(NOME_104);
  }
}

async function semear(): Promise<void> {
  await pool.query("INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a'),($2,'B','b')",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO public.company_settings (company_id) VALUES ($1),($2)",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO auth.users (id,email) VALUES ($1,'g@a.pt'),($2,'g@b.pt')",
    [GESTORA, GESTORA_OUTRA]);
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id) VALUES
      ($1,$2,'Gestora A','gestor','ativo',$1),
      ($3,$4,'Gestora B','gestor','ativo',$3)`,
    [GESTORA, EMPRESA, GESTORA_OUTRA, OUTRA],
  );
  await pool.query(
    "INSERT INTO public.clients (id,company_id,name) VALUES ($1,$2,'Cliente A'), ($3,$4,'Cliente B')",
    [CLIENTE_A, EMPRESA, CLIENTE_B, OUTRA],
  );
}

/** Uma lead com tudo preenchido, para se poder verificar o que é copiado. */
async function novaLead(over: Record<string, unknown> = {}): Promise<string> {
  const campos = {
    name: "Condomínio Alfa",
    lead_type: "empresa",
    email: "geral@alfa.pt",
    phone: "912345678",
    nif: "500123456",
    address: "Rua da Lead 1, Lisboa",
    lat: 38.7223,
    lng: -9.1393,
    service_type: "manutencao",
    ...over,
  };
  const { rows } = await pool.query(
    `INSERT INTO public.crm_leads
       (company_id, name, lead_type, email, phone, nif, address, lat, lng, service_type)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,
    [
      (over.company_id as string) ?? EMPRESA,
      campos.name, campos.lead_type, campos.email, campos.phone, campos.nif,
      campos.address, campos.lat, campos.lng, campos.service_type,
    ],
  );
  return rows[0].id as string;
}

async function novaVisita(leadId: string, address: string | null, over: {
  empresa?: string; lat?: number | null; lng?: number | null;
} = {}): Promise<string> {
  const { rows } = await pool.query(
    `INSERT INTO public.crm_visits (company_id, lead_id, scheduled_start, scheduled_end, address, lat, lng)
     VALUES ($1,$2, now(), now() + interval '1 hour', $3, $4, $5) RETURNING id`,
    [over.empresa ?? EMPRESA, leadId, address, over.lat ?? 41.1, over.lng ?? -8.6],
  );
  return rows[0].id as string;
}

/** Cria um orçamento pela RPC da 103 e deixa-o no estado pedido. */
async function novoOrcamento(leadId: string, opts: {
  visitId?: string | null; estado?: string; empresa?: string;
} = {}): Promise<{ id: string; numero: string }> {
  const empresa = opts.empresa ?? EMPRESA;
  const { rows } = await pool.query(
    `SELECT * FROM public.create_crm_quote_with_items(
       $1,$2,NULL,$3,'ORC',$4,CURRENT_DATE,CURRENT_DATE + 30,
       'pontual',0,true,23,NULL,NULL,NULL,NULL,NULL,$5,$6::jsonb)`,
    [
      empresa, leadId, opts.visitId ?? null, ANO,
      empresa === EMPRESA ? GESTORA : GESTORA_OUTRA,
      JSON.stringify([{ description: "Limpeza", quantity: 1, unit: "servico", unit_price: 100 }]),
    ],
  );
  const id = rows[0].quote_id as string;
  const numero = rows[0].quote_number as string;

  const estado = opts.estado ?? "aceite";
  const actor = empresa === EMPRESA ? GESTORA : GESTORA_OUTRA;
  if (estado !== "rascunho") {
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)", [empresa, id, actor]);
    if (estado !== "enviado") {
      await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,$4,NULL)", [empresa, id, actor, estado]);
    }
  }
  return { id, numero };
}

async function converter(
  leadId: string,
  quoteId: string | null,
  over: { empresa?: string; actor?: string } = {},
): Promise<{ client_id: string; location_id: string; ja_convertida: boolean }> {
  const { rows } = await pool.query(
    "SELECT * FROM public.convert_crm_lead_atomic($1,$2,$3,$4)",
    [over.empresa ?? EMPRESA, leadId, over.actor ?? GESTORA, quoteId],
  );
  return rows[0];
}

/** Fotografia do que uma recusa não pode ter mudado. */
async function fotografia(leadId: string, quoteId: string) {
  const { rows: c } = await pool.query("SELECT count(*)::int AS n FROM public.clients");
  const { rows: l } = await pool.query("SELECT count(*)::int AS n FROM public.locations");
  const { rows: i } = await pool.query("SELECT count(*)::int AS n FROM public.crm_lead_interactions");
  const { rows: lead } = await pool.query(
    "SELECT stage, won_at, converted_client_id, converted_location_id FROM public.crm_leads WHERE id = $1",
    [leadId]);
  const { rows: q } = await pool.query(
    "SELECT lead_id, client_id, status, source_lead_id FROM public.crm_quotes WHERE id = $1",
    [quoteId]);
  return { clients: c[0].n, locations: l[0].n, interactions: i[0].n, lead: lead[0], quote: q[0] };
}

async function ligacao(): Promise<pg.Client> {
  const c = new pg.Client({ ...container.connection });
  await c.connect();
  return c;
}

beforeAll(async () => {
  container = await startPostgresContainer({ name: CONTAINER, database: "crm104", memory: "512m" });
  pool = new pg.Pool({ ...container.connection, max: 8 });
  await palco();
}, 240_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechado */ });
  container?.stop();
});

beforeEach(async () => {
  await limpar();
  leadA = await novaLead();
});

/**
 * Esvazia o palco pela ordem em que as FKs permitem.
 *
 * 🔴 Sem `UPDATE crm_leads SET converted_client_id = NULL`. Uma lead em
 *    `ganho` não pode ficar sem cliente: `crm_leads_ganho_exige_conversao`
 *    recusa-o, e com razão. A lead APAGA-SE; é isso que liberta o
 *    `ON DELETE RESTRICT` das FKs para `clients` e `locations`.
 */
async function limpar(): Promise<void> {
  await pool.query("DELETE FROM public.crm_lead_interactions");
  await pool.query("DELETE FROM public.crm_quote_items");
  await pool.query("DELETE FROM public.crm_quotes");
  await pool.query("DELETE FROM public.crm_visits");
  await pool.query("DELETE FROM public.crm_leads");
  await pool.query("DELETE FROM public.locations");
  await pool.query("DELETE FROM public.clients WHERE id NOT IN ($1,$2)", [CLIENTE_A, CLIENTE_B]);
}

// ───────────────────────────────────────────────────────────────────────────
describe("1-3. conversão nominal", () => {
  it("cria cliente e local, e fecha a lead", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const r = await converter(leadA, q.id);

    expect(r.ja_convertida).toBe(false);
    expect(r.client_id).toBeTruthy();
    expect(r.location_id).toBeTruthy();

    const { rows: cliente } = await pool.query(
      "SELECT name, nif, email, phone, address, type, status, company_id FROM public.clients WHERE id = $1",
      [r.client_id]);
    expect(cliente[0]).toMatchObject({
      name: "Condomínio Alfa",
      nif: "500123456",
      email: "geral@alfa.pt",
      phone: "912345678",
      type: "empresa",
      status: "ativo",
      company_id: EMPRESA,
    });

    const { rows: local } = await pool.query(
      "SELECT name, address, lat, lng, service_type, active, client_id, company_id, hourly_rate FROM public.locations WHERE id = $1",
      [r.location_id]);
    expect(local[0].name).toBe("Condomínio Alfa");
    expect(local[0].address).toBe("Rua da Lead 1, Lisboa");
    expect(local[0].service_type).toBe("manutencao");
    expect(local[0].active).toBe(true);
    expect(local[0].client_id).toBe(r.client_id);
    expect(local[0].company_id).toBe(EMPRESA);
    // 🔴 Preço operacional NÃO inferido: é decisão de quem faz o contrato.
    expect(local[0].hourly_rate).toBeNull();

    const { rows: lead } = await pool.query(
      "SELECT stage, won_at, converted_client_id, converted_location_id, lost_at, lost_reason FROM public.crm_leads WHERE id = $1",
      [leadA]);
    expect(lead[0].stage).toBe("ganho");
    expect(lead[0].won_at).not.toBeNull();
    expect(lead[0].converted_client_id).toBe(r.client_id);
    expect(lead[0].converted_location_id).toBe(r.location_id);
    expect(lead[0].lost_at).toBeNull();
    expect(lead[0].lost_reason).toBeNull();
  });

  it("sem service_type na lead, o local cai no default", LENTO, async () => {
    const lead = await novaLead({ service_type: null });
    const q = await novoOrcamento(lead);
    const r = await converter(lead, q.id);

    const { rows } = await pool.query(
      "SELECT service_type FROM public.locations WHERE id = $1", [r.location_id]);
    expect(rows[0].service_type).toBe("limpeza_regular");
  });

  it("uma lead individual gera um cliente individual", LENTO, async () => {
    const lead = await novaLead({ lead_type: "individual" });
    const q = await novoOrcamento(lead);
    const r = await converter(lead, q.id);

    const { rows } = await pool.query("SELECT type FROM public.clients WHERE id = $1", [r.client_id]);
    expect(rows[0].type).toBe("individual");
  });

  it("uma lead que tinha sido dada como perdida fica coerente ao ganhar", LENTO, async () => {
    const lead = await novaLead();
    await pool.query(
      `UPDATE public.crm_leads
          SET stage = 'perdido', lost_at = now(), lost_reason = 'preco',
              lost_reason_notes = 'achou caro'
        WHERE id = $1`, [lead]);

    const q = await novoOrcamento(lead);
    await converter(lead, q.id);

    const { rows } = await pool.query(
      "SELECT stage, lost_at, lost_reason, lost_reason_notes FROM public.crm_leads WHERE id = $1",
      [lead]);
    expect(rows[0].stage).toBe("ganho");
    expect(rows[0].lost_at).toBeNull();
    expect(rows[0].lost_reason).toBeNull();
    expect(rows[0].lost_reason_notes).toBeNull();
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("4-6. de onde vem a morada", () => {
  it("🔴 visita com morada ganha à lead — e as coordenadas vão com ela", LENTO, async () => {
    const visita = await novaVisita(leadA, "Rua da Visita 99, Porto", { lat: 41.15, lng: -8.61 });
    const q = await novoOrcamento(leadA, { visitId: visita });
    const r = await converter(leadA, q.id);

    const { rows } = await pool.query(
      "SELECT address, lat, lng FROM public.locations WHERE id = $1", [r.location_id]);
    expect(rows[0].address).toBe("Rua da Visita 99, Porto");
    // 🔴 A fonte é uma UNIDADE: morada da visita com coordenadas da visita.
    //    Misturar punha o alfinete do mapa noutro sítio que não o endereço.
    expect(Number(rows[0].lat)).toBeCloseTo(41.15, 4);
    expect(Number(rows[0].lng)).toBeCloseTo(-8.61, 4);
  });

  it("visita sem morada: cai na lead, inteira", LENTO, async () => {
    const visita = await novaVisita(leadA, null);
    const q = await novoOrcamento(leadA, { visitId: visita });
    const r = await converter(leadA, q.id);

    const { rows } = await pool.query(
      "SELECT address, lat, lng FROM public.locations WHERE id = $1", [r.location_id]);
    expect(rows[0].address).toBe("Rua da Lead 1, Lisboa");
    expect(Number(rows[0].lat)).toBeCloseTo(38.7223, 4);
    expect(Number(rows[0].lng)).toBeCloseTo(-9.1393, 4);
  });

  it("visita com morada em branco conta como sem morada", LENTO, async () => {
    const visita = await novaVisita(leadA, "   ");
    const q = await novoOrcamento(leadA, { visitId: visita });
    const r = await converter(leadA, q.id);

    const { rows } = await pool.query(
      "SELECT address FROM public.locations WHERE id = $1", [r.location_id]);
    expect(rows[0].address).toBe("Rua da Lead 1, Lisboa");
  });

  it("orçamento sem visita: usa a lead", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const r = await converter(leadA, q.id);
    const { rows } = await pool.query(
      "SELECT address FROM public.locations WHERE id = $1", [r.location_id]);
    expect(rows[0].address).toBe("Rua da Lead 1, Lisboa");
  });

  it("🔴 sem morada em lado nenhum: recusa, e zero vestígios", LENTO, async () => {
    const lead = await novaLead({ address: null });
    const q = await novoOrcamento(lead);
    const antes = await fotografia(lead, q.id);

    await expect(converter(lead, q.id)).rejects.toThrow(/CONVERSION_ADDRESS_REQUIRED/);

    expect(await fotografia(lead, q.id)).toEqual(antes);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("7-12. o que a RPC recusa, sempre sem vestígios", () => {
  const casos: Array<{
    nome: string;
    erro: RegExp;
    montar: () => Promise<{ lead: string; quote: string | null; over?: { actor?: string; empresa?: string } }>;
  }> = [
    {
      nome: "7. orçamento em rascunho",
      erro: /QUOTE_NOT_ACCEPTED/,
      montar: async () => ({ lead: leadA, quote: (await novoOrcamento(leadA, { estado: "rascunho" })).id }),
    },
    {
      nome: "7b. orçamento enviado mas não aceite",
      erro: /QUOTE_NOT_ACCEPTED/,
      montar: async () => ({ lead: leadA, quote: (await novoOrcamento(leadA, { estado: "enviado" })).id }),
    },
    {
      nome: "7c. orçamento recusado",
      erro: /QUOTE_NOT_ACCEPTED/,
      montar: async () => ({ lead: leadA, quote: (await novoOrcamento(leadA, { estado: "recusado" })).id }),
    },
    {
      nome: "8. orçamento de OUTRA lead",
      erro: /QUOTE_LEAD_MISMATCH/,
      montar: async () => {
        const outraLead = await novaLead({ name: "Beta" });
        return { lead: leadA, quote: (await novoOrcamento(outraLead)).id };
      },
    },
    {
      nome: "9. orçamento de outra empresa",
      erro: /QUOTE_NOT_FOUND/,
      montar: async () => {
        const leadOutra = await novaLead({ company_id: OUTRA, name: "Gama" });
        return { lead: leadA, quote: (await novoOrcamento(leadOutra, { empresa: OUTRA })).id };
      },
    },
    {
      nome: "12. actor de outra empresa",
      erro: /ACTOR_NOT_IN_COMPANY/,
      montar: async () => ({
        lead: leadA,
        quote: (await novoOrcamento(leadA)).id,
        over: { actor: GESTORA_OUTRA },
      }),
    },
    {
      nome: "sem orçamento nenhum",
      erro: /CONVERSION_QUOTE_REQUIRED/,
      montar: async () => ({ lead: leadA, quote: null }),
    },
  ];

  for (const caso of casos) {
    it(`🔴 ${caso.nome}: recusa e ZERO_SIDE_EFFECTS`, LENTO, async () => {
      const { lead, quote, over } = await caso.montar();
      const antes = quote ? await fotografia(lead, quote) : null;
      const { rows: cAntes } = await pool.query("SELECT count(*)::int AS n FROM public.clients");

      await expect(converter(lead, quote, over)).rejects.toThrow(caso.erro);

      if (antes) expect(await fotografia(lead, quote!)).toEqual(antes);
      const { rows: cDepois } = await pool.query("SELECT count(*)::int AS n FROM public.clients");
      expect(cDepois[0].n).toBe(cAntes[0].n);
    });
  }

  it("🔴 10. uma revisão histórica não converte", LENTO, async () => {
    const q = await novoOrcamento(leadA, { estado: "enviado" });
    await pool.query(
      `SELECT public.revise_crm_quote($1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, q.id, GESTORA,
        JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 90 }])],
    );

    const antes = await fotografia(leadA, q.id);
    await expect(converter(leadA, q.id)).rejects.toThrow(/QUOTE_ALREADY_SUPERSEDED/);
    expect(await fotografia(leadA, q.id)).toEqual(antes);
  });

  it("🔴 11. orçamento já endereçado a um cliente", LENTO, async () => {
    // Estado que só existe depois de uma conversão: o orçamento tem
    // `client_id` e `lead_id` a NULL. Convertê-lo outra vez a partir de outra
    // lead seria criar um segundo cliente para o mesmo documento.
    const q = await novoOrcamento(leadA);
    await converter(leadA, q.id);

    const outraLead = await novaLead({ name: "Delta" });
    const antes = await fotografia(outraLead, q.id);

    await expect(converter(outraLead, q.id)).rejects.toThrow(/QUOTE_LEAD_MISMATCH/);
    expect(await fotografia(outraLead, q.id)).toEqual(antes);
  });

  it("lead inexistente", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await expect(
      converter("99999999-9999-4999-8999-999999999999", q.id),
    ).rejects.toThrow(/LEAD_NOT_FOUND/);
  });

  it("lead de outra empresa não se converte pela empresa errada", LENTO, async () => {
    const leadOutra = await novaLead({ company_id: OUTRA, name: "Épsilon" });
    const q = await novoOrcamento(leadOutra, { empresa: OUTRA });
    await expect(converter(leadOutra, q.id)).rejects.toThrow(/LEAD_NOT_FOUND/);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("13. concorrência", () => {
  it("🔴 duas conversões simultâneas: UM cliente e UM local", LENTO, async () => {
    const q = await novoOrcamento(leadA);

    const c1 = await ligacao();
    const c2 = await ligacao();

    try {
      await c1.query("BEGIN");
      await c2.query("BEGIN");

      const p1 = c1.query("SELECT * FROM public.convert_crm_lead_atomic($1,$2,$3,$4)",
        [EMPRESA, leadA, GESTORA, q.id]);
      // Dá tempo a que a primeira pegue no `FOR UPDATE` da lead.
      await new Promise((r) => setTimeout(r, 120));
      const p2 = c2.query("SELECT * FROM public.convert_crm_lead_atomic($1,$2,$3,$4)",
        [EMPRESA, leadA, GESTORA, q.id]);

      const r1 = await p1;
      await c1.query("COMMIT");

      const r2 = await p2.catch((err: Error) => err);
      await c2.query("COMMIT").catch(() => c2.query("ROLLBACK"));

      // 🔴 A segunda ou espera e vê a lead já convertida (idempotente), ou
      //    falha — o que NÃO pode é criar um segundo par.
      if (r2 instanceof Error) {
        expect(r2.message).toMatch(/QUOTE_RECIPIENT_MISMATCH|CONVERSION_STATE_DIVERGED|QUOTE_LEAD_MISMATCH/);
      } else {
        expect(r2.rows[0].ja_convertida).toBe(true);
        expect(r2.rows[0].client_id).toBe(r1.rows[0].client_id);
        expect(r2.rows[0].location_id).toBe(r1.rows[0].location_id);
      }

      const { rows: clientes } = await pool.query(
        "SELECT count(*)::int AS n FROM public.clients WHERE name = 'Condomínio Alfa'");
      const { rows: locais } = await pool.query("SELECT count(*)::int AS n FROM public.locations");
      expect(clientes[0].n).toBe(1);
      expect(locais[0].n).toBe(1);
    } finally {
      await c1.end().catch(() => {});
      await c2.end().catch(() => {});
    }
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("14. idempotência", () => {
  it("repetir devolve os mesmos ids e não cria nada", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const primeira = await converter(leadA, q.id);

    const { rows: antesC } = await pool.query("SELECT count(*)::int AS n FROM public.clients");
    const { rows: antesL } = await pool.query("SELECT count(*)::int AS n FROM public.locations");
    const { rows: antesI } = await pool.query("SELECT count(*)::int AS n FROM public.crm_lead_interactions");

    const segunda = await converter(leadA, q.id);

    expect(segunda.ja_convertida).toBe(true);
    expect(segunda.client_id).toBe(primeira.client_id);
    expect(segunda.location_id).toBe(primeira.location_id);

    const { rows: depoisC } = await pool.query("SELECT count(*)::int AS n FROM public.clients");
    const { rows: depoisL } = await pool.query("SELECT count(*)::int AS n FROM public.locations");
    const { rows: depoisI } = await pool.query("SELECT count(*)::int AS n FROM public.crm_lead_interactions");
    expect(depoisC[0].n).toBe(antesC[0].n);
    expect(depoisL[0].n).toBe(antesL[0].n);
    // 🔴 Nem uma segunda linha de timeline: a conversão aconteceu uma vez.
    expect(depoisI[0].n).toBe(antesI[0].n);
  });

  it("🔴 estado divergente NÃO se repara sozinho", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const r = await converter(leadA, q.id);

    // Um local de OUTRO cliente, forjado directamente na base. A FK nova
    // impede-o em `crm_leads`, por isso a divergência é montada no orçamento:
    // a lead diz convertida, mas o documento aponta para outro cliente.
    await pool.query("UPDATE public.crm_quotes SET client_id = $1 WHERE id = $2", [CLIENTE_A, q.id]);

    await expect(converter(leadA, q.id)).rejects.toThrow(/CONVERSION_STATE_DIVERGED/);

    // E nada foi «corrigido» pelo caminho.
    const { rows } = await pool.query(
      "SELECT client_id FROM public.crm_quotes WHERE id = $1", [q.id]);
    expect(rows[0].client_id).toBe(CLIENTE_A);
    expect(r.client_id).not.toBe(CLIENTE_A);
  });

  it("repetir com um orçamento que não é desta lead é recusado", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await converter(leadA, q.id);

    const outraLead = await novaLead({ name: "Zeta" });
    const outroQ = await novoOrcamento(outraLead);

    await expect(converter(leadA, outroQ.id)).rejects.toThrow(/QUOTE_LEAD_MISMATCH/);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("15. a invariante cliente ↔ local", () => {
  it("🔴 a FK recusa um par que as duas FKs da 101 aceitariam", LENTO, async () => {
    // Dois clientes da MESMA empresa, cada um com o seu local. As FKs da 101
    // aceitam qualquer combinação; a da 104 exige o par.
    const q = await novoOrcamento(leadA);
    const r = await converter(leadA, q.id);

    const { rows: outro } = await pool.query(
      "INSERT INTO public.clients (company_id, name) VALUES ($1,'Outro') RETURNING id", [EMPRESA]);
    const { rows: localOutro } = await pool.query(
      `INSERT INTO public.locations (company_id, client_id, name, address)
       VALUES ($1,$2,'Local do outro','Rua X') RETURNING id`,
      [EMPRESA, outro[0].id]);

    await expect(
      pool.query("UPDATE public.crm_leads SET converted_location_id = $1 WHERE id = $2",
        [localOutro[0].id, leadA]),
    ).rejects.toThrow(/crm_leads_conversao_par_coerente|violates foreign key/i);

    // O par original continua intacto.
    const { rows: lead } = await pool.query(
      "SELECT converted_client_id, converted_location_id FROM public.crm_leads WHERE id = $1", [leadA]);
    expect(lead[0].converted_client_id).toBe(r.client_id);
    expect(lead[0].converted_location_id).toBe(r.location_id);
  });

  it("a chave candidata existe e é única", LENTO, async () => {
    const { rows } = await pool.query(`
      SELECT indisunique FROM pg_index
       WHERE indexrelid = 'public.locations_id_client_company_unique'::regclass`);
    expect(rows[0].indisunique).toBe(true);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("16-18. o que acontece ao orçamento", () => {
  it("🔴 só a quote viva muda de destinatário; a proveniência sobrevive", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const r = await converter(leadA, q.id);

    const { rows } = await pool.query(
      "SELECT lead_id, client_id, source_lead_id, status, accepted_at FROM public.crm_quotes WHERE id = $1",
      [q.id]);
    expect(rows[0].lead_id).toBeNull();
    expect(rows[0].client_id).toBe(r.client_id);
    // 🔴 É isto que mantém a cadeia navegável depois de `lead_id` ficar NULL.
    expect(rows[0].source_lead_id).toBe(leadA);
    expect(rows[0].status).toBe("aceite");
    expect(rows[0].accepted_at).not.toBeNull();
  });

  it("🔴 18. as revisões históricas não são reescritas", LENTO, async () => {
    // R0 enviada, revista para R1, R1 aceite, e converte-se pela R1.
    const r0 = await novoOrcamento(leadA, { estado: "enviado" });
    const { rows: rev } = await pool.query(
      `SELECT * FROM public.revise_crm_quote($1,$2,$3,CURRENT_DATE,CURRENT_DATE + 30,0,true,23,NULL,$4::jsonb)`,
      [EMPRESA, r0.id, GESTORA,
        JSON.stringify([{ description: "A", quantity: 1, unit: "servico", unit_price: 90 }])],
    );
    const r1 = rev[0].quote_id as string;
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'enviado',NULL)", [EMPRESA, r1, GESTORA]);
    await pool.query("SELECT public.set_crm_quote_status($1,$2,$3,'aceite',NULL)", [EMPRESA, r1, GESTORA]);

    const r = await converter(leadA, r1);

    const { rows: historica } = await pool.query(
      "SELECT lead_id, client_id, status, revision FROM public.crm_quotes WHERE id = $1", [r0.id]);
    // A R0 continua endereçada à lead: é a história de quando era assim.
    expect(historica[0].lead_id).toBe(leadA);
    expect(historica[0].client_id).toBeNull();
    expect(historica[0].status).toBe("enviado");

    const { rows: viva } = await pool.query(
      "SELECT lead_id, client_id FROM public.crm_quotes WHERE id = $1", [r1]);
    expect(viva[0].lead_id).toBeNull();
    expect(viva[0].client_id).toBe(r.client_id);
  });

  it("converted_contract_id e converted_service_id ficam NULL", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await converter(leadA, q.id);
    const { rows } = await pool.query(
      "SELECT converted_contract_id, converted_service_id FROM public.crm_quotes WHERE id = $1", [q.id]);
    expect(rows[0].converted_contract_id).toBeNull();
    expect(rows[0].converted_service_id).toBeNull();
  });

  it("a timeline é escrita, com o número do orçamento", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await converter(leadA, q.id);

    const { rows } = await pool.query(
      "SELECT kind, summary, author_id FROM public.crm_lead_interactions WHERE lead_id = $1", [leadA]);
    expect(rows).toHaveLength(1);
    expect(rows[0].kind).toBe("sistema");
    expect(rows[0].summary).toContain(q.numero);
    expect(rows[0].author_id).toBe(GESTORA);
  });

  it("🔴 se a timeline falhar, a conversão inteira reverte", LENTO, async () => {
    // A timeline aqui NÃO é best-effort: sem a linha que explica a conversão,
    // ninguém sabe de onde veio o cliente. Simula-se a falha com um CHECK
    // temporário que recusa a linha.
    const q = await novoOrcamento(leadA);
    await pool.query(`
      ALTER TABLE public.crm_lead_interactions
        ADD CONSTRAINT tmp_recusa_tudo CHECK (kind <> 'sistema') NOT VALID`);

    try {
      const antes = await fotografia(leadA, q.id);
      await expect(converter(leadA, q.id)).rejects.toThrow();
      expect(await fotografia(leadA, q.id)).toEqual(antes);
    } finally {
      await pool.query("ALTER TABLE public.crm_lead_interactions DROP CONSTRAINT tmp_recusa_tudo");
    }
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("19-22. a fronteira com a operação e o dinheiro", () => {
  it("🔴 converter não cria contrato, serviço, factura nem movimento de caixa", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    await converter(leadA, q.id);

    for (const tabela of ["contracts", "services", "invoices", "invoice_items", "cash_flow_entries"]) {
      const { rows } = await pool.query(`SELECT count(*)::int AS n FROM public.${tabela}`);
      expect(rows[0].n, `${tabela} devia continuar vazia`).toBe(0);
    }
  });

  it("o corpo da RPC não menciona sequer essas tabelas", LENTO, async () => {
    const sql = lerSql(M_104);
    const corpo = sql.slice(sql.indexOf("CREATE OR REPLACE FUNCTION public.convert_crm_lead_atomic"));
    const codigo = corpo.split("\n").filter((l) => !l.trim().startsWith("--")).join("\n");
    for (const tabela of ["contracts", "services", "invoices", "cash_flow_entries"]) {
      expect(codigo, `a RPC menciona ${tabela}`).not.toContain(`public.${tabela}`);
    }
  });

  it("🔴 não deduplica: converter duas leads iguais dá dois clientes", LENTO, async () => {
    // Mesmo nome, mesmo NIF, mesmo email. Heurística de identidade criaria
    // uma fusão silenciosa que ninguém pediu.
    const q1 = await novoOrcamento(leadA);
    const r1 = await converter(leadA, q1.id);

    const gemea = await novaLead();
    const q2 = await novoOrcamento(gemea);
    const r2 = await converter(gemea, q2.id);

    expect(r2.client_id).not.toBe(r1.client_id);
    const { rows } = await pool.query(
      "SELECT count(*)::int AS n FROM public.clients WHERE nif = '500123456'");
    expect(rows[0].n).toBe(2);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("23-25. segurança da RPC — canónica desde o primeiro dia", () => {
  it("🔴 ACL: só o owner e service_role, sem WITH GRANT OPTION", LENTO, async () => {
    const { rows } = await pool.query(`
      SELECT
        (SELECT array_agg(DISTINCT acl.grantee::regrole::text ORDER BY acl.grantee::regrole::text)
           FROM aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) AS acl
          WHERE acl.privilege_type = 'EXECUTE') AS grantees,
        (SELECT bool_or(acl.is_grantable)
           FROM aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) AS acl
          WHERE acl.privilege_type = 'EXECUTE') AS grantable,
        p.proowner::regrole::text AS owner
        FROM pg_proc p
       WHERE p.oid = 'public.convert_crm_lead_atomic(uuid, uuid, uuid, uuid)'::regprocedure`);

    const { grantees, grantable, owner } = rows[0];
    // 🔴 O CONJUNTO, e o owner derivado — nunca escrito à mão.
    expect([...grantees].sort()).toEqual([owner, "service_role"].sort());
    expect(grantable ?? false).toBe(false);
  });

  it("🔴 anon e authenticated NÃO executam", LENTO, async () => {
    const { rows } = await pool.query(`
      SELECT has_function_privilege('anon', 'public.convert_crm_lead_atomic(uuid, uuid, uuid, uuid)', 'EXECUTE') AS anon,
             has_function_privilege('authenticated', 'public.convert_crm_lead_atomic(uuid, uuid, uuid, uuid)', 'EXECUTE') AS auth,
             has_function_privilege('service_role', 'public.convert_crm_lead_atomic(uuid, uuid, uuid, uuid)', 'EXECUTE') AS srv`);
    expect(rows[0].anon).toBe(false);
    expect(rows[0].auth).toBe(false);
    expect(rows[0].srv).toBe(true);
  });

  // 🔴 FAIL CLOSED: a migration recusa-se a ficar aplicada com a segurança
  //    errada. Não basta o REVOKE estar escrito — se alguém o alterar, o
  //    pós-estado tem de parar a aplicação em vez de deixar passar.
  //
  //    Foi a 103 a nascer com `REVOKE ... FROM PUBLIC` sozinho que obrigou à
  //    103a. Este bloco existe para que isso não possa repetir-se em silêncio.
  const sabotagens: Array<{ nome: string; de: string; para: string }> = [
    {
      nome: "REVOKE só de PUBLIC (o defeito que originou a 103a)",
      de: "  FROM PUBLIC, anon, authenticated, service_role;",
      para: "  FROM PUBLIC;",
    },
    {
      nome: "sem search_path fixo",
      de: "SET search_path = pg_catalog, public",
      para: "",
    },
    {
      nome: "SECURITY DEFINER",
      de: "SECURITY INVOKER",
      para: "SECURITY DEFINER",
    },
    {
      nome: "GRANT a mais para authenticated",
      de: "  TO service_role;",
      para: "  TO service_role, authenticated;",
    },
  ];

  for (const s of sabotagens) {
    it(`🔴 ${s.nome}: a migration FALHA FECHADA`, LENTO, async () => {
      await palco(false);
      const sql = lerSql(M_104);
      expect(sql, `a âncora «${s.de.trim()}» já não existe no SQL`).toContain(s.de);

      await expect(pool.query(sql.replace(s.de, s.para)))
        .rejects.toThrow(/CRM_CONV_104_POSTSTATE_FAILED/);

      await palco();
      leadA = await novaLead();
    });
  }

  it("SECURITY INVOKER e search_path exacto", LENTO, async () => {
    const { rows } = await pool.query(`
      SELECT p.prosecdef, p.proconfig
        FROM pg_proc p
       WHERE p.oid = 'public.convert_crm_lead_atomic(uuid, uuid, uuid, uuid)'::regprocedure`);
    expect(rows[0].prosecdef).toBe(false);
    expect(rows[0].proconfig).toContain("search_path=pg_catalog, public");
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("26-27. proveniência, sequência e rollback", () => {
  it("🔴 JA_APLICADA: não corre duas vezes", LENTO, async () => {
    await expect(pool.query(lerSql(M_104))).rejects.toThrow(/CRM_CONV_104_JA_APLICADA/);
  });

  it("🔴 EFFECT_WITHOUT_LEDGER: efeitos sem linha de ledger", LENTO, async () => {
    await pool.query("DELETE FROM public._migrations WHERE name = $1", [NOME_104]);
    try {
      await expect(pool.query(lerSql(M_104))).rejects.toThrow(/CRM_CONV_104_EFFECT_WITHOUT_LEDGER/);
    } finally {
      await registarNoLedger(NOME_104);
    }
  });

  it("🔴 clean install sobre a cadeia real 101→103a", LENTO, async () => {
    await palco(false);
    await pool.query(lerSql(M_104));
    await registarNoLedger(NOME_104);

    const { rows } = await pool.query(`
      SELECT to_regprocedure('public.convert_crm_lead_atomic(uuid, uuid, uuid, uuid)') IS NOT NULL AS rpc,
             to_regclass('public.locations_id_client_company_unique') IS NOT NULL AS idx`);
    expect(rows[0].rpc).toBe(true);
    expect(rows[0].idx).toBe(true);

    leadA = await novaLead();
    const q = await novoOrcamento(leadA);
    const r = await converter(leadA, q.id);
    expect(r.ja_convertida).toBe(false);
  });

  it("🔴 rollback estrutural: remove os três efeitos e NÃO apaga dados", LENTO, async () => {
    const q = await novoOrcamento(leadA);
    const r = await converter(leadA, q.id);

    await pool.query(lerSql(ROLLBACK_104));

    const { rows } = await pool.query(`
      SELECT to_regprocedure('public.convert_crm_lead_atomic(uuid, uuid, uuid, uuid)') IS NULL AS sem_rpc,
             to_regclass('public.locations_id_client_company_unique') IS NULL AS sem_idx,
             NOT EXISTS (SELECT 1 FROM pg_constraint
                          WHERE conrelid = 'public.crm_leads'::regclass
                            AND conname = 'crm_leads_conversao_par_coerente') AS sem_fk,
             NOT EXISTS (SELECT 1 FROM public._migrations WHERE name = '104_crm_conversao_lead.sql') AS sem_ledger`);
    expect(rows[0]).toEqual({ sem_rpc: true, sem_idx: true, sem_fk: true, sem_ledger: true });

    // 🔴 NO_DATA_LOSS: o cliente convertido continua lá, e a lead também.
    const { rows: cliente } = await pool.query(
      "SELECT count(*)::int AS n FROM public.clients WHERE id = $1", [r.client_id]);
    expect(cliente[0].n).toBe(1);
    const { rows: lead } = await pool.query(
      "SELECT stage, converted_client_id FROM public.crm_leads WHERE id = $1", [leadA]);
    expect(lead[0].stage).toBe("ganho");
    expect(lead[0].converted_client_id).toBe(r.client_id);
    const { rows: timeline } = await pool.query(
      "SELECT count(*)::int AS n FROM public.crm_lead_interactions WHERE lead_id = $1", [leadA]);
    expect(timeline[0].n).toBe(1);

    // Repor o palco para os ensaios seguintes.
    await palco();
    leadA = await novaLead();
  });

  it("rollback sem ledger e sem efeitos é no-op", LENTO, async () => {
    await pool.query(lerSql(ROLLBACK_104));
    await expect(pool.query(lerSql(ROLLBACK_104))).resolves.toBeTruthy();
    await palco();
    leadA = await novaLead();
  });
});
