// ============================================================================
// 106 — o estado do colaborador decide na base, contra Postgres real
// ============================================================================
//
// 🔴 O palco é a cadeia de IDENTIDADE como está em produção:
//
//        baseline canónico + 101 + 101a + 101b  →  106
//
//    A 102→105 NÃO entra. São de outro domínio (CRM) e a 106 não depende
//    delas — montá-las aqui só tornaria a suite mais lenta e daria a impressão
//    falsa de que a autorização depende do funil comercial.
//
// ---------------------------------------------------------------------------
// O que só Postgres real responde
// ---------------------------------------------------------------------------
//
//   · que uma pessoa SUSPENSA com um JWT perfeitamente válido deixa de ler as
//     linhas que lia — a prova de que o token vivo deixou de bastar;
//   · que o resolver fecha as TRÊS funções de uma vez, porque as outras duas
//     delegam nele;
//   · que `can_access_service` deixou de assumir `profiles.id = auth.uid()`;
//   · que o isolamento por empresa continua intacto depois da mudança;
//   · que a migration falha fechada em cada um dos estados de proveniência.
//
// Nenhuma destas se prova lendo o SQL.
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";

const CONTAINER = `colab106-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const OUTRA = "22222222-2222-4222-8222-222222222222";

const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const ATIVA = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
const SUSPENSA = "dddddddd-dddd-4ddd-8ddd-dddddddddddd";
const INATIVA = "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee";
/** Da OUTRA empresa, activa — para o isolamento continuar a ser medido. */
const ALHEIA = "ffffffff-ffff-4fff-8fff-ffffffffffff";

const EQUIPA = "10ea0000-0000-4000-8000-000000000001";
const CLIENTE = "c1111111-1111-4111-8111-111111111111";
const LOCAL = "10cac111-1111-4111-8111-111111111111";
const SERVICO = "5e401c00-0000-4000-8000-000000000001";
/** Um serviço da outra empresa. */
const SERVICO_ALHEIO = "5e401c00-0000-4000-8000-000000000002";

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_106 = "supabase/migrations/106_colaborador_status_autorizacao.sql";
const ROLLBACK_106 = "supabase/migrations/rollback/106_colaborador_status_autorizacao.down.sql";
const NOME_106 = "106_colaborador_status_autorizacao.sql";

const CADEIA = [
  "101_crm_leads.sql",
  "101a_crm_rpc_acl_hardening.sql",
  "101b_identity_reconciliation.sql",
] as const;

const SIG_SERVICO = "public.can_access_service(uuid)";
const SIG_RESOLVER = "public.get_my_profile_id()";

/**
 * 🔴 O comentario VIVO do predecessor, lido do catalogo de producao.
 *
 *    97 caracteres e SEM acentos. O ficheiro da 101b tem um texto acentuado e
 *    mais longo — confiar nele foi exactamente o erro que o rollback desta
 *    migration cometia.
 */
const COMENTARIO_PREDECESSOR =
  "O id da pessoa autenticada, ou NULL se nao houver sessao ou a conta nao estiver ligada a ninguem.";

let container: PostgresContainer;
let pool: pg.Pool;

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

const checksumLf = (ficheiro: string): string =>
  createHash("sha256")
    .update(lerSql(`supabase/migrations/${ficheiro}`).split("\r\n").join("\n").split("\r").join("\n"))
    .digest("hex");

async function registarNoLedger(nome: string, checksum?: string): Promise<void> {
  await pool.query(
    `INSERT INTO public._migrations (name, checksum) VALUES ($1,$2)
     ON CONFLICT (name) DO UPDATE SET checksum = EXCLUDED.checksum`,
    [nome, checksum ?? checksumLf(nome)],
  );
}

/** A cadeia de identidade. `aplicar106` fecha o palco com a migration em prova. */
async function palco(aplicar106 = true): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);
  // 🔴 O default privilege do projecto: uma função nova nasce executável por
  //    anon/authenticated/service_role. É contra isto que a ACL da 106 tem de
  //    trabalhar — sem isto no palco, a ACL passaria por acidente.
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);

  // 🔴 O CHECK de `profiles.status`, que o fixture NÃO traz.
  //
  //    `production-schema-shape.sql` é gerado por introspecção e extrai
  //    tabelas, colunas, PK/FK, RLS e políticas — não esta restrição. Mas ela
  //    EXISTE em produção, lida no catálogo vivo a 2026-09-24:
  //
  //        CHECK (status = ANY (ARRAY['ativo', 'inativo', 'suspenso']))
  //
  //    Acrescentá-la aqui não é fabricar a precondição que a migration testa —
  //    é completar o palco com o que produção provadamente tem e o dump não
  //    copia. Sem ela, o ensaio do estado fora do domínio não mede nada (um
  //    UPDATE para 'arquivado' passaria) e a precondição da 106 recusaria a
  //    instalação por um motivo que produção não tem.
  await pool.query(`
    ALTER TABLE public.profiles
      ADD CONSTRAINT profiles_status_check
      CHECK (status = ANY (ARRAY['ativo'::text, 'inativo'::text, 'suspenso'::text]));
  `);

  // 🔴 A `can_access_service` REAL da 034, e não o coto do baseline.
  //
  //    `production-baseline.ts` cria-a como `SELECT true` — um coto suficiente
  //    para outras suites, e inútil para esta: mediria sempre `true` e as
  //    provas 9-11 davam verde sem tocar em lógica nenhuma.
  //
  //    O corpo abaixo é COPIADO da 034, que é quem a cria em produção — a
  //    mesma prática do `HELPERS_PARA_CRM` do harness, que copia os corpos
  //    reais das migrations que os criam em vez de inventar versões
  //    simplificadas. É a forma ANTERIOR à 106, com `p.id = auth.uid()` e sem
  //    `search_path`: é isso que a 106 tem de encontrar e corrigir.
  await pool.query(`
    CREATE OR REPLACE FUNCTION public.can_access_service(p_service_id uuid)
    RETURNS boolean
    LANGUAGE sql
    SECURITY DEFINER
    STABLE
    AS $can$
      SELECT EXISTS (
        SELECT 1
        FROM   services s
        INNER  JOIN profiles p ON p.id = auth.uid() AND p.company_id = s.company_id
        WHERE  s.id = p_service_id
        AND (
          EXISTS (
            SELECT 1 FROM team_members tm
            WHERE  tm.team_id        = s.team_id
            AND    tm.collaborator_id = auth.uid()
            AND   (tm.left_at IS NULL OR tm.left_at > NOW())
          )
          OR EXISTS (
            SELECT 1 FROM service_reinforcements sr
            WHERE  sr.service_id     = s.id
            AND    sr.collaborator_id = auth.uid()
          )
        )
      )
    $can$;
    GRANT EXECUTE ON FUNCTION public.can_access_service(uuid) TO PUBLIC;
    -- 🔴 E os três papéis do Supabase, EXPLICITAMENTE.
    --
    --    O baseline cria a função ANTES de o \`ALTER DEFAULT PRIVILEGES\` estar
    --    em vigor, e \`CREATE OR REPLACE\` preserva a ACL existente — por isso o
    --    palco ficava com \`{PUBLIC, postgres}\` enquanto produção tem
    --    \`{PUBLIC, anon, authenticated, postgres, service_role}\`, lido no
    --    catálogo vivo. Sem isto, o pré-estado da 106 recusava-se a instalar
    --    aqui por uma diferença que produção não tem.
    GRANT EXECUTE ON FUNCTION public.can_access_service(uuid) TO anon, authenticated, service_role;
  `);

  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await pool.query(lerSql(M_101B));

  // 🔴 O comentario vivo do resolver. A 101b cria-o com um texto ACENTUADO;
  //    producao tem um SEM acentos, mais curto. O palco copia o que la esta,
  //    senao o pre-estado da 106 recusava-se a instalar aqui por uma diferenca
  //    que producao nao tem.
  //
  //    `can_access_service` fica SEM comentario, como em producao.
  //    `COMMENT ON` e DDL: nao aceita $1. Dai a interpolacao — a constante nao
  //    tem plicas nem vem de fora.
  await pool.query(
    "COMMENT ON FUNCTION public.get_my_profile_id() IS '" + COMENTARIO_PREDECESSOR + "'");
  await pool.query("COMMENT ON FUNCTION public.can_access_service(uuid) IS NULL");

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public._migrations (
      name text PRIMARY KEY, checksum text, applied_at timestamptz NOT NULL DEFAULT now())`);
  for (const nome of CADEIA) await registarNoLedger(nome);

  await semear();

  if (aplicar106) {
    await pool.query(lerSql(M_106));
    await registarNoLedger(NOME_106);
  }
}

async function semear(): Promise<void> {
  await pool.query("INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a'),($2,'B','b')",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO public.company_settings (company_id) VALUES ($1),($2)",
    [EMPRESA, OUTRA]);
  await pool.query(
    `INSERT INTO auth.users (id,email) VALUES
      ($1,'g@a.pt'),($2,'a@a.pt'),($3,'s@a.pt'),($4,'i@a.pt'),($5,'x@b.pt')`,
    [GESTORA, ATIVA, SUSPENSA, INATIVA, ALHEIA],
  );
  // 🔴 `auth_user_id` preenchido: é a forma canónica da 101b, e é a que
  //    produção tem nas 29 contas ligadas.
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id) VALUES
      ($1,$2,'Gestora','gestor','ativo',$1),
      ($3,$2,'Activa','colaborador','ativo',$3),
      ($4,$2,'Suspensa','colaborador','suspenso',$4),
      ($5,$2,'Inactiva','colaborador','inativo',$5),
      ($6,$7,'Alheia','gestor','ativo',$6)`,
    [GESTORA, EMPRESA, ATIVA, SUSPENSA, INATIVA, ALHEIA, OUTRA],
  );
  await pool.query(
    "INSERT INTO public.clients (id,company_id,name) VALUES ($1,$2,'Cliente A')",
    [CLIENTE, EMPRESA]);
  await pool.query(
    `INSERT INTO public.locations (id,company_id,client_id,name,address)
     VALUES ($1,$2,$3,'Sede','Rua 1')`, [LOCAL, EMPRESA, CLIENTE]);
  await pool.query(
    "INSERT INTO public.teams (id,company_id,name) VALUES ($1,$2,'Equipa 1')",
    [EQUIPA, EMPRESA]);

  // As três na mesma equipa — a diferença entre elas é só o estado.
  for (const p of [ATIVA, SUSPENSA, INATIVA]) {
    await pool.query(
      "INSERT INTO public.team_members (team_id, collaborator_id) VALUES ($1,$2)", [EQUIPA, p]);
  }

  await pool.query(
    `INSERT INTO public.services (id, company_id, location_id, team_id, scheduled_start, scheduled_end, status, reference_number)
     VALUES ($1,$2,$3,$4, now(), now() + interval '2 hours', 'agendado', 'SRV-A-1')`,
    [SERVICO, EMPRESA, LOCAL, EQUIPA]);

  // Um serviço da OUTRA empresa, sem equipa partilhada.
  await pool.query(
    "INSERT INTO public.clients (id,company_id,name) VALUES ($1,$2,'Cliente B')",
    ["c2222222-2222-4222-8222-222222222222", OUTRA]);
  await pool.query(
    `INSERT INTO public.locations (id,company_id,client_id,name,address)
     VALUES ($1,$2,$3,'Sede B','Rua 2')`,
    ["10cab222-2222-4222-8222-222222222222", OUTRA, "c2222222-2222-4222-8222-222222222222"]);
  await pool.query(
    "INSERT INTO public.teams (id,company_id,name) VALUES ($1,$2,'Equipa B')",
    ["10ea0000-0000-4000-8000-000000000002", OUTRA]);
  await pool.query(
    `INSERT INTO public.services (id, company_id, location_id, team_id, scheduled_start, scheduled_end, status, reference_number)
     VALUES ($1,$2,$3,$4, now(), now() + interval '2 hours', 'agendado', 'SRV-B-1')`,
    [SERVICO_ALHEIO, OUTRA, "10cab222-2222-4222-8222-222222222222",
      "10ea0000-0000-4000-8000-000000000002"]);
}

/**
 * Corre uma consulta COMO uma pessoa autenticada.
 *
 * 🔴 `SET LOCAL request.jwt.claim.sub` é o que o `auth.uid()` do palco lê — a
 *    mesma forma que o PostgREST usa. É assim que se simula um TOKEN JÁ
 *    EMITIDO: o JWT é perfeitamente válido e não se sabe nada sobre o estado
 *    do perfil. Se a pessoa perder acesso, é a base a decidir, não o login.
 */
async function comoUtilizador<T>(
  authUid: string | null,
  sql: string,
  params: unknown[] = [],
  papel = "authenticated",
): Promise<T[]> {
  const c = new pg.Client({ ...container.connection });
  await c.connect();
  try {
    await c.query("BEGIN");
    await c.query(`SET LOCAL request.jwt.claim.sub = '${authUid ?? ""}'`);
    await c.query(`SET LOCAL ROLE ${papel}`);
    const { rows } = await c.query(sql, params);
    await c.query("ROLLBACK");
    return rows as T[];
  } finally {
    await c.end();
  }
}

const resolver = async (uid: string | null): Promise<string | null> => {
  const rows = await comoUtilizador<{ id: string | null }>(
    uid, "SELECT public.get_my_profile_id() AS id");
  return rows[0].id;
};

const empresaDe = async (uid: string | null): Promise<string | null> => {
  const rows = await comoUtilizador<{ c: string | null }>(
    uid, "SELECT public.get_my_company_id() AS c");
  return rows[0].c;
};

const papelDe = async (uid: string | null): Promise<string | null> => {
  const rows = await comoUtilizador<{ r: string | null }>(
    uid, "SELECT public.get_my_role() AS r");
  return rows[0].r;
};

const podeVerServico = async (uid: string | null, servico: string): Promise<boolean> => {
  const rows = await comoUtilizador<{ ok: boolean }>(
    uid, "SELECT public.can_access_service($1) AS ok", [servico]);
  return rows[0].ok;
};

beforeAll(async () => {
  container = await startPostgresContainer({ name: CONTAINER, database: "colab106", memory: "512m" });
  pool = new pg.Pool({ ...container.connection, max: 8 });
  await palco();
}, 240_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechada */ });
  container?.stop();
});

beforeEach(async () => {
  // 🔴 Repor o estado das pessoas entre ensaios: há ensaios que o mudam para
  //    medir a transição, e um estado a fugir de um ensaio para o seguinte dá
  //    verdes que não significam nada.
  await pool.query("UPDATE public.profiles SET status = 'ativo' WHERE id IN ($1,$2)", [GESTORA, ATIVA]);
  await pool.query("UPDATE public.profiles SET status = 'suspenso' WHERE id = $1", [SUSPENSA]);
  await pool.query("UPDATE public.profiles SET status = 'inativo' WHERE id = $1", [INATIVA]);
});

// ───────────────────────────────────────────────────────────────────────────
describe("1-3. o resolver exige estado activo", () => {
  it("🔴 1. ACTIVO resolve o seu profile id", LENTO, async () => {
    expect(await resolver(ATIVA)).toBe(ATIVA);
    expect(await resolver(GESTORA)).toBe(GESTORA);
  });

  it("🔴 2. SUSPENSO não resolve", LENTO, async () => {
    expect(await resolver(SUSPENSA)).toBeNull();
  });

  it("🔴 3. INATIVO não resolve", LENTO, async () => {
    expect(await resolver(INATIVA)).toBeNull();
  });

  it("sem sessão, continua a devolver NULL", LENTO, async () => {
    expect(await resolver(null)).toBeNull();
  });

  it("🔴 a transição é imediata: suspender tira o acesso à consulta seguinte", LENTO, async () => {
    // 🔴 Não há cache, não há sessão a expirar, não há nada a limpar. O token
    //    da pessoa continua válido; o que mudou foi a resposta da base.
    expect(await resolver(ATIVA)).toBe(ATIVA);
    await pool.query("UPDATE public.profiles SET status = 'suspenso' WHERE id = $1", [ATIVA]);
    expect(await resolver(ATIVA)).toBeNull();
    await pool.query("UPDATE public.profiles SET status = 'ativo' WHERE id = $1", [ATIVA]);
    expect(await resolver(ATIVA)).toBe(ATIVA);
  });

  it("🔴 um estado que o CHECK não conhece não resolve (forma FECHADA)", LENTO, async () => {
    // Não se consegue gravar um estado fora do CHECK — e é isso mesmo. O que
    // este ensaio fixa é o desenho: a regra é `= 'ativo'`, não uma lista de
    // proibidos. Um estado novo nasce SEM acesso.
    await expect(
      pool.query("UPDATE public.profiles SET status = 'arquivado' WHERE id = $1", [ATIVA]),
    ).rejects.toThrow(/profiles_status_check|violates check constraint/);

    const { rows } = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(rows[0].prosrc)).toMatch(/status\s*=\s*'ativo'/);
    expect(String(rows[0].prosrc)).not.toMatch(/status\s*(<>|!=)/);
    expect(String(rows[0].prosrc)).not.toMatch(/NOT IN|lower\(|btrim\(|trim\(/);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("4-5, 7-8. as funções que delegam herdam a regra", () => {
  it("🔴 4. admin/gestor activo continua autorizado", LENTO, async () => {
    expect(await empresaDe(GESTORA)).toBe(EMPRESA);
    expect(await papelDe(GESTORA)).toBe("gestor");
  });

  it("🔴 5. colaborador activo mantém os seus acessos", LENTO, async () => {
    expect(await empresaDe(ATIVA)).toBe(EMPRESA);
    expect(await papelDe(ATIVA)).toBe("colaborador");
    expect(await podeVerServico(ATIVA, SERVICO)).toBe(true);
  });

  it("🔴 7. get_my_company_id falha fechado quando não activo", LENTO, async () => {
    expect(await empresaDe(SUSPENSA)).toBeNull();
    expect(await empresaDe(INATIVA)).toBeNull();
  });

  it("🔴 8. get_my_role falha fechado quando não activo", LENTO, async () => {
    expect(await papelDe(SUSPENSA)).toBeNull();
    expect(await papelDe(INATIVA)).toBeNull();
  });

  it("🔴 um gestor SUSPENSO perde o papel — o papel não sobrevive à saída", LENTO, async () => {
    await pool.query("UPDATE public.profiles SET status = 'suspenso' WHERE id = $1", [GESTORA]);
    expect(await papelDe(GESTORA)).toBeNull();
    expect(await empresaDe(GESTORA)).toBeNull();
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("6. um JWT válido deixa de bastar — RLS a sério", () => {
  it("🔴 6. activo lê os clientes da empresa; suspenso não lê nada", LENTO, async () => {
    // 🔴 `clients_manage` é `company_id = get_my_company_id() AND get_my_role()
    //    IN (admin, gestor)`. É uma política REAL do fixture de produção, não
    //    uma inventada para o ensaio.
    const comoActiva = await comoUtilizador<{ id: string }>(
      GESTORA, "SELECT id FROM public.clients WHERE company_id = $1", [EMPRESA]);
    expect(comoActiva.length).toBeGreaterThan(0);

    await pool.query("UPDATE public.profiles SET status = 'suspenso' WHERE id = $1", [GESTORA]);

    const comoSuspensa = await comoUtilizador<{ id: string }>(
      GESTORA, "SELECT id FROM public.clients WHERE company_id = $1", [EMPRESA]);
    // 🔴 O token é o mesmo e continua válido. O que mudou foi a base.
    expect(comoSuspensa).toHaveLength(0);
  });

  it("🔴 a pessoa suspensa também não escreve", LENTO, async () => {
    await pool.query("UPDATE public.profiles SET status = 'suspenso' WHERE id = $1", [GESTORA]);
    await expect(
      comoUtilizador(GESTORA,
        "INSERT INTO public.clients (id, company_id, name) VALUES (gen_random_uuid(), $1, 'Novo')",
        [EMPRESA]),
    ).rejects.toThrow(/row-level security|violates/i);
  });

  it("o service_role continua a passar — é ele que corre as migrations", LENTO, async () => {
    const rows = await comoUtilizador<{ n: string }>(
      SUSPENSA, "SELECT count(*) AS n FROM public.clients", [], "service_role");
    expect(Number(rows[0].n)).toBeGreaterThan(0);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("9-11. can_access_service", () => {
  it("🔴 9. permite o caso activo legítimo", LENTO, async () => {
    expect(await podeVerServico(ATIVA, SERVICO)).toBe(true);
  });

  it("🔴 10. recusa quem não está activo", LENTO, async () => {
    expect(await podeVerServico(SUSPENSA, SERVICO)).toBe(false);
    expect(await podeVerServico(INATIVA, SERVICO)).toBe(false);
  });

  it("🔴 11. o isolamento entre empresas continua", LENTO, async () => {
    // A gestora da empresa A não vê o serviço da B, mesmo activa.
    expect(await podeVerServico(GESTORA, SERVICO_ALHEIO)).toBe(false);
    expect(await podeVerServico(ALHEIA, SERVICO)).toBe(false);
  });

  it("🔴 11-bis. o guard de EMPRESA sozinho, com a equipa a atravessar a fronteira", LENTO, async () => {
    // 🔴 Este ensaio existe porque o 11 NÃO prova o que parecia provar.
    //
    //    No 11, a gestora da empresa A não vê o serviço da B — mas isso
    //    acontecia mesmo SEM a verificação de empresa, porque ela também não
    //    pertence à equipa desse serviço. A condição de equipa escondia a de
    //    empresa, e removê-la do SQL deixava o ensaio verde. Medido por
    //    mutação.
    //
    // 🔴 O caso que a isola é desconfortável e é real: `team_members` NÃO tem
    //    restrição composta por empresa — nada no schema impede um perfil da
    //    empresa A de entrar numa equipa da empresa B. Nada, a não ser o
    //    `p.company_id = s.company_id` dentro desta função.
    await pool.query(
      "INSERT INTO public.team_members (team_id, collaborator_id) VALUES ($1,$2)",
      ["10ea0000-0000-4000-8000-000000000002", GESTORA]);

    try {
      // Está na equipa do serviço alheio, está activa — e continua a não poder
      // vê-lo, porque a empresa não é a dela.
      expect(await podeVerServico(GESTORA, SERVICO_ALHEIO)).toBe(false);
    } finally {
      await pool.query(
        "DELETE FROM public.team_members WHERE team_id = $1 AND collaborator_id = $2",
        ["10ea0000-0000-4000-8000-000000000002", GESTORA]);
    }
  });

  it("🔴 deixou de assumir profiles.id = auth.uid()", LENTO, async () => {
    // 🔴 O defeito que a 106 corrige, medido pelo comportamento.
    //
    //    Cria-se um perfil cujo `id` é DIFERENTE do `auth_user_id` — que é o
    //    que a 101b passou a permitir. Na forma antiga, `p.id = auth.uid()`
    //    não casava e a pessoa perdia acesso aos seus próprios serviços em
    //    silêncio. Com o resolver, casa.
    const perfil = "ababab00-0000-4000-8000-000000000001";
    const conta = "ababab00-0000-4000-8000-000000000002";
    await pool.query("INSERT INTO auth.users (id,email) VALUES ($1,'sep@a.pt')", [conta]);
    await pool.query(
      `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id)
       VALUES ($1,$2,'Separada','colaborador','ativo',$3)`, [perfil, EMPRESA, conta]);
    await pool.query(
      "INSERT INTO public.team_members (team_id, collaborator_id) VALUES ($1,$2)", [EQUIPA, perfil]);

    try {
      expect(await resolver(conta)).toBe(perfil);
      expect(await podeVerServico(conta, SERVICO)).toBe(true);
    } finally {
      await pool.query("DELETE FROM public.team_members WHERE collaborator_id = $1", [perfil]);
      await pool.query("DELETE FROM public.profiles WHERE id = $1", [perfil]);
      await pool.query("DELETE FROM auth.users WHERE id = $1", [conta]);
    }
  });

  it("um reforço pontual também passa pelo estado", LENTO, async () => {
    const outroServico = "5e401c00-0000-4000-8000-000000000003";
    await pool.query(
      `INSERT INTO public.services (id, company_id, location_id, scheduled_start, scheduled_end, status, reference_number)
       VALUES ($1,$2,$3, now(), now() + interval '1 hour', 'agendado', 'SRV-A-2')`,
      [outroServico, EMPRESA, LOCAL]);
    await pool.query(
      "INSERT INTO public.service_reinforcements (service_id, collaborator_id) VALUES ($1,$2)",
      [outroServico, SUSPENSA]);

    try {
      expect(await podeVerServico(SUSPENSA, outroServico)).toBe(false);
      await pool.query("UPDATE public.profiles SET status = 'ativo' WHERE id = $1", [SUSPENSA]);
      expect(await podeVerServico(SUSPENSA, outroServico)).toBe(true);
    } finally {
      await pool.query("DELETE FROM public.service_reinforcements WHERE service_id = $1", [outroServico]);
      await pool.query("DELETE FROM public.services WHERE id = $1", [outroServico]);
    }
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("12-14. a forma das funções", () => {
  it("🔴 12. search_path fixado nas duas", LENTO, async () => {
    const { rows } = await pool.query(
      `SELECT p.proname, p.proconfig
         FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname='public' AND p.proname IN ('get_my_profile_id','can_access_service')
        ORDER BY p.proname`);
    const mapa = Object.fromEntries(rows.map((r) => [r.proname, r.proconfig]));
    expect(mapa.can_access_service).toEqual(["search_path=pg_catalog, public"]);
    expect(mapa.get_my_profile_id).not.toBeNull();
  });

  it("🔴 13. ACL exacta: sem PUBLIC, sem grant option, com os três papéis", LENTO, async () => {
    for (const sig of [SIG_RESOLVER, SIG_SERVICO]) {
      const { rows } = await pool.query(
        `SELECT array_agg(DISTINCT a.grantee::regrole::text ORDER BY a.grantee::regrole::text) AS g,
                bool_or(a.is_grantable) AS grantable
           FROM pg_proc p, LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
          WHERE p.oid = to_regprocedure($1) AND a.privilege_type = 'EXECUTE'`, [sig]);
      const grantees: string[] = rows[0].g ?? [];
      expect(grantees, `${sig} ainda tem PUBLIC`).not.toContain("-");
      expect(rows[0].grantable, `${sig} com grant option`).toBe(false);
      for (const papel of ["anon", "authenticated", "service_role"]) {
        expect(grantees, `${sig} perdeu ${papel}`).toContain(papel);
      }
    }
  });

  it("🔴 14. as duas continuam SECURITY DEFINER", LENTO, async () => {
    // 🔴 `can_access_service` TEM de continuar DEFINER: é chamada de dentro de
    //    políticas sobre `services` e precisa de ler `team_members` sem que a
    //    RLS dessas tabelas a volte a filtrar — o que daria recursão.
    const { rows } = await pool.query(
      `SELECT p.proname, p.prosecdef
         FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname='public' AND p.proname IN ('get_my_profile_id','can_access_service')`);
    for (const r of rows) expect(r.prosecdef, `${r.proname}`).toBe(true);
  });

  it("🔴 anon não executa sem sessão, mas também não rebenta", LENTO, async () => {
    // Sem sessão, `auth.uid()` é NULL e o resolver devolve NULL. Um erro de
    // permissão revelaria que a função existe.
    const rows = await comoUtilizador<{ id: string | null }>(
      null, "SELECT public.get_my_profile_id() AS id", [], "anon");
    expect(rows[0].id).toBeNull();
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("15. uma sessão já emitida não contorna o estado", () => {
  it("🔴 15. o mesmo JWT, na mesma ligação, perde acesso a meio", LENTO, async () => {
    // 🔴 Esta é a diferença entre banir no Auth e decidir na base.
    //
    //    O ban impede o LOGIN seguinte. Não invalida o token que já está no
    //    browser de alguém. Aqui a mesma ligação, com o mesmo `sub`, deixa de
    //    ler assim que outra transação muda o estado — sem reautenticação,
    //    sem expirar nada.
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query(`SET request.jwt.claim.sub = '${ATIVA}'`);
      await c.query("SET ROLE authenticated");

      const antes = await c.query("SELECT public.get_my_profile_id() AS id");
      expect(antes.rows[0].id).toBe(ATIVA);

      // Outra sessão dá a saída.
      await pool.query("UPDATE public.profiles SET status = 'suspenso' WHERE id = $1", [ATIVA]);

      const depois = await c.query("SELECT public.get_my_profile_id() AS id");
      expect(depois.rows[0].id).toBeNull();
    } finally {
      await c.query("RESET ROLE").catch(() => { /* já fechada */ });
      await c.end();
    }
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("16-20. proveniência e aplicação", () => {
  it("🔴 16. aplica-se uma vez sobre a cadeia real", LENTO, async () => {
    await palco(false);
    // Antes: o resolver ainda não filtra.
    const antes = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(antes.rows[0].prosrc)).not.toMatch(/status/);

    await pool.query(lerSql(M_106));
    await registarNoLedger(NOME_106);

    const depois = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(depois.rows[0].prosrc)).toMatch(/status\s*=\s*'ativo'/);
  });

  it("🔴 17. JA_APLICADA: não corre duas vezes", LENTO, async () => {
    await expect(pool.query(lerSql(M_106))).rejects.toThrow(/COLAB_106_JA_APLICADA/);
  });

  it("🔴 18. falta a linha de ledger da 101b → DEPENDENCY_LEDGER_MISSING", LENTO, async () => {
    await palco(false);
    await pool.query("DELETE FROM public._migrations WHERE name = $1",
      ["101b_identity_reconciliation.sql"]);

    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_DEPENDENCY_LEDGER_MISSING/);

    // 🔴 Nada foi alterado: o resolver continua sem filtro.
    const { rows } = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(rows[0].prosrc)).not.toMatch(/status/);

    await palco();
  });

  it("🔴 checksum da 101b divergente → DEPENDENCY_CHECKSUM_DIVERGED", LENTO, async () => {
    await palco(false);
    await pool.query("UPDATE public._migrations SET checksum = $2 WHERE name = $1",
      ["101b_identity_reconciliation.sql", "0".repeat(64)]);

    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_DEPENDENCY_CHECKSUM_DIVERGED/);

    await palco();
  });

  it("🔴 19. efeito sem ledger → EFFECT_WITHOUT_LEDGER", LENTO, async () => {
    await pool.query("DELETE FROM public._migrations WHERE name = $1", [NOME_106]);
    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_EFFECT_WITHOUT_LEDGER/);
    await registarNoLedger(NOME_106);
  });

  it("🔴 20. ledger sem efeito → LEDGER_WITHOUT_EFFECT", LENTO, async () => {
    await palco(false);
    await registarNoLedger(NOME_106);
    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_LEDGER_WITHOUT_EFFECT/);
    await palco();
  });

  it("🔴 sem o resolver da 101b → PREESTADO_INESPERADO", LENTO, async () => {
    await palco(false);
    await pool.query(`
      CREATE OR REPLACE FUNCTION public.get_my_profile_id() RETURNS uuid
      LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public
      AS $f$ SELECT id FROM profiles WHERE id = auth.uid() LIMIT 1 $f$;`);

    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO/);

    await palco();
  });

  it("🔴 get_my_role a ler profiles por conta própria → PRECONDITION_FAILED", LENTO, async () => {
    // Se a delegação não existir, mudar só o resolver deixaria um caminho
    // aberto — e a migration estaria a prometer o que não cumpre.
    await palco(false);
    await pool.query(`
      CREATE OR REPLACE FUNCTION public.get_my_role() RETURNS text
      LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public
      AS $f$ SELECT role FROM profiles WHERE auth_user_id = auth.uid() LIMIT 1 $f$;`);

    await expect(pool.query(lerSql(M_106)))
      // 🔴 `[\s\S]*` e não a flag `/s`: `dotAll` exige ES2018 e o tsconfig
    //    deste projecto é ES2017. O compilador apanha-o, mas só depois de o
    //    ensaio já ter passado localmente.
    .rejects.toThrow(/COLAB_106_PRECONDITION_FAILED[\s\S]*get_my_role/);

    await palco();
  });

  // ─────────────────────────────────────────────────────────────────────────
  // 🔴 A/B/C — o PRÉ-ESTADO não se deixa enganar por uma palavra
  //
  //    A versão anterior deste guard aceitava o resolver se o corpo contivesse
  //    `auth_user_id`, e `can_access_service` se contivesse `auth.uid()` OU
  //    `get_my_profile_id`. Uma função alterada depois da 101b, com regra nova
  //    e a palavra lá dentro, passava — e a 106 pisava-a com CREATE OR
  //    REPLACE, apagando trabalho de outra pessoa.
  // ─────────────────────────────────────────────────────────────────────────

  it("🔴 A. resolver alterado, MAS com auth_user_id: a 106 RECUSA", LENTO, async () => {
    await palco(false);
    // Alteração material: passa a exigir também que o perfil tenha email.
    // Continua a mencionar `auth_user_id` — era isto que enganava o guard.
    await pool.query(`
      CREATE OR REPLACE FUNCTION public.get_my_profile_id() RETURNS uuid
      LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public
      AS $f$
        SELECT id FROM profiles
         WHERE auth_user_id = auth.uid() AND email IS NOT NULL
         LIMIT 1;
      $f$;`);
    const antes = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);

    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO/);

    // 🔴 A alteração de quem lá mexeu CONTINUA INTACTA.
    const depois = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(depois.rows[0].prosrc).toBe(antes.rows[0].prosrc);
    expect(String(depois.rows[0].prosrc)).toContain("email IS NOT NULL");

    await palco();
  });

  it("🔴 B. can_access_service alterada, MAS com auth.uid(): a 106 RECUSA", LENTO, async () => {
    await palco(false);
    // Alteração material: deixa de aceitar reforços pontuais.
    await pool.query(`
      CREATE OR REPLACE FUNCTION public.can_access_service(p_service_id uuid)
      RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE
      AS $f$
        SELECT EXISTS (
          SELECT 1 FROM services s
          INNER JOIN profiles p ON p.id = auth.uid() AND p.company_id = s.company_id
          WHERE s.id = p_service_id
            AND EXISTS (SELECT 1 FROM team_members tm
                         WHERE tm.team_id = s.team_id AND tm.collaborator_id = auth.uid())
        )
      $f$;`);
    const antes = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);

    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO/);

    const depois = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);
    expect(depois.rows[0].prosrc).toBe(antes.rows[0].prosrc);
    // E o resolver também não foi tocado.
    const res = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(res.rows[0].prosrc)).not.toMatch(/status/);

    await palco();
  });

  it("🔴 C. só a ACL do predecessor mudou: a 106 RECUSA", LENTO, async () => {
    // 🔴 O caso mais subtil dos três. Os corpos estão certos; alguém deu
    //    EXECUTE a um papel a mais. Sem este guard, a 106 revogava-o em
    //    silêncio no bloco da ACL — uma decisão de outra pessoa desfeita sem
    //    ninguém dar por ela.
    await palco(false);
    await pool.query("CREATE ROLE papel_extra_106 NOLOGIN");
    await pool.query(
      "GRANT EXECUTE ON FUNCTION public.get_my_profile_id() TO papel_extra_106");

    try {
      await expect(pool.query(lerSql(M_106)))
        // 🔴 `[\s\S]*` e não a flag `/s`: `dotAll` exige ES2018 e o tsconfig
        //    deste projecto é ES2017.
        .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO[\s\S]*ACL/);

      // O grant continua lá.
      const { rows } = await pool.query(`
        SELECT count(*)::int AS n
          FROM pg_proc p, LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
         WHERE p.oid = to_regprocedure($1) AND a.privilege_type='EXECUTE'
           AND a.grantee::regrole::text = 'papel_extra_106'`, [SIG_RESOLVER]);
      expect(rows[0].n).toBe(1);
    } finally {
      await pool.query(
        "REVOKE ALL ON FUNCTION public.get_my_profile_id() FROM papel_extra_106")
        .catch(() => { /* já não existe */ });
      await pool.query("DROP ROLE IF EXISTS papel_extra_106");
      await palco();
    }
  });

  // 🔴 O caso que a lista de grantees NÃO distingue.
  //
  //    `authenticated` com EXECUTE e `authenticated` com EXECUTE WITH GRANT
  //    OPTION dão exactamente os mesmos nomes em `array_agg(grantee)`. Sem ler
  //    `is_grantable`, o pré-estado dava-os por iguais — e o bloco da ACL da
  //    106 (`REVOKE ALL` + `GRANT EXECUTE`) retirava a capacidade de delegar
  //    sem o dizer a ninguém.
  const COM_GRANT_OPTION: Array<[string, string, string]> = [
    ["get_my_profile_id", "public.get_my_profile_id()", SIG_RESOLVER],
    ["can_access_service", "public.can_access_service(uuid)", SIG_SERVICO],
  ];

  for (const [nome, alvoGrant, assinatura] of COM_GRANT_OPTION) {
    it(`🔴 ${nome} com WITH GRANT OPTION no predecessor: a 106 RECUSA`, LENTO, async () => {
      await palco(false);

      const antesGrantees = await pool.query(`
        SELECT array_agg(DISTINCT a.grantee::regrole::text ORDER BY a.grantee::regrole::text) AS g
          FROM pg_proc p, LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
         WHERE p.oid = to_regprocedure($1) AND a.privilege_type='EXECUTE'`, [assinatura]);

      await pool.query(
        `GRANT EXECUTE ON FUNCTION ${alvoGrant} TO authenticated WITH GRANT OPTION`);

      // 🔴 A LISTA NÃO MUDOU — é isso que torna o caso perigoso.
      const depoisGrantees = await pool.query(`
        SELECT array_agg(DISTINCT a.grantee::regrole::text ORDER BY a.grantee::regrole::text) AS g,
               bool_or(a.is_grantable) AS grantable
          FROM pg_proc p, LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
         WHERE p.oid = to_regprocedure($1) AND a.privilege_type='EXECUTE'`, [assinatura]);
      expect(depoisGrantees.rows[0].g).toEqual(antesGrantees.rows[0].g);
      expect(depoisGrantees.rows[0].grantable).toBe(true);

      const corpoResolverAntes = await pool.query(
        "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
      const corpoServicoAntes = await pool.query(
        "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);

      await expect(pool.query(lerSql(M_106)))
        .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO/);

      // 🔴 ZERO escritas: corpos intactos, grant option intacto, ledger sem 106.
      const resolverDepois = await pool.query(
        "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
      expect(resolverDepois.rows[0].prosrc).toBe(corpoResolverAntes.rows[0].prosrc);
      expect(String(resolverDepois.rows[0].prosrc)).not.toMatch(/status/);

      const servicoDepois = await pool.query(
        "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);
      expect(servicoDepois.rows[0].prosrc).toBe(corpoServicoAntes.rows[0].prosrc);

      const aclDepois = await pool.query(`
        SELECT bool_or(a.is_grantable) AS grantable
          FROM pg_proc p, LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
         WHERE p.oid = to_regprocedure($1) AND a.privilege_type='EXECUTE'`, [assinatura]);
      expect(aclDepois.rows[0].grantable, "o grant option de outra pessoa foi retirado").toBe(true);

      const { rows: led } = await pool.query(
        "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
      expect(led[0].n).toBe(0);

      await palco();
    });
  }

  // 🔴 G/H/I/J - drift de METADADOS do predecessor
  //
  //    `CREATE OR REPLACE FUNCTION` preserva apenas o OWNER e as PERMISSOES.
  //    Todas as outras propriedades recebem os valores explicitos ou por
  //    omissao do comando novo. Um `ALTER FUNCTION ... PARALLEL SAFE` feito
  //    antes da 106 seria silenciosamente reposto a `PARALLEL UNSAFE`, sem o
  //    corpo mudar uma letra.
  //
  //    E por isso que a comparacao e de `pg_get_functiondef()` inteiro, e nao
  //    de atributos escolhidos a mao: cobre os que ainda nao imaginamos.
  const DRIFT_DDL: Array<[string, string]> = [
    ["PARALLEL SAFE", "ALTER FUNCTION public.can_access_service(uuid) PARALLEL SAFE"],
    ["STRICT", "ALTER FUNCTION public.can_access_service(uuid) STRICT"],
    ["COST 17", "ALTER FUNCTION public.can_access_service(uuid) COST 17"],
  ];

  for (const [nome, alter] of DRIFT_DDL) {
    it(`🔴 ${nome} no predecessor: a 106 RECUSA, e zero escritas`, LENTO, async () => {
      await palco(false);

      const corpoAntes = await pool.query(
        "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);
      await pool.query(alter);
      const defAntes = await pool.query(
        "SELECT pg_get_functiondef(to_regprocedure($1)) AS d", [SIG_SERVICO]);

      // 🔴 O CORPO nao mudou - e isso que torna o caso perigoso.
      const corpoDepoisAlter = await pool.query(
        "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);
      expect(corpoDepoisAlter.rows[0].prosrc).toBe(corpoAntes.rows[0].prosrc);

      await expect(pool.query(lerSql(M_106)))
        .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO/);

      // 🔴 ZERO escritas: a alteracao de quem la mexeu PERMANECE.
      const defDepois = await pool.query(
        "SELECT pg_get_functiondef(to_regprocedure($1)) AS d", [SIG_SERVICO]);
      expect(defDepois.rows[0].d).toBe(defAntes.rows[0].d);

      const resolver = await pool.query(
        "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
      expect(String(resolver.rows[0].prosrc)).not.toMatch(/status/);

      const { rows: led } = await pool.query(
        "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
      expect(led[0].n).toBe(0);

      await palco();
    });
  }

  it("🔴 J. owner diferente no predecessor: a 106 RECUSA", LENTO, async () => {
    // 🔴 O owner e a UNICA propriedade, com as permissoes, que o
    //    `CREATE OR REPLACE` preserva. Numa funcao SECURITY DEFINER e a
    //    identidade com que o corpo corre: instalar a 106 sobre uma funcao que
    //    mudou de dono seria instala-la a correr como outra pessoa.
    await palco(false);
    await pool.query("CREATE ROLE dono_teste_106 NOLOGIN");
    await pool.query("ALTER FUNCTION public.can_access_service(uuid) OWNER TO dono_teste_106");

    try {
      await expect(pool.query(lerSql(M_106)))
        .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO/);

      // O owner alterado PERMANECE.
      const { rows } = await pool.query(
        "SELECT proowner::regrole::text AS o FROM pg_proc WHERE oid = to_regprocedure($1)",
        [SIG_SERVICO]);
      expect(rows[0].o).toBe("dono_teste_106");

      const { rows: led } = await pool.query(
        "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
      expect(led[0].n).toBe(0);
    } finally {
      await pool.query("ALTER FUNCTION public.can_access_service(uuid) OWNER TO postgres")
        .catch(() => { /* o palco vai recriar */ });
      await pool.query("DROP ROLE IF EXISTS dono_teste_106");
      await palco();
    }
  });

  // 🔴 M/N - drift de COMENTARIO no predecessor
  //
  //    `pg_get_functiondef()` NAO imprime comentarios. A 106 escreve
  //    `COMMENT ON FUNCTION` nas duas, por isso o comentario faz parte do
  //    estado que ela altera — e do que tem de proteger.
  it("🔴 M. comentario do resolver alterado: a 106 RECUSA", LENTO, async () => {
    await palco(false);
    await pool.query(
      "COMMENT ON FUNCTION public.get_my_profile_id() IS 'alterado por outra pessoa'");

    const defAntes = await pool.query(
      "SELECT pg_get_functiondef(to_regprocedure($1)) AS d", [SIG_RESOLVER]);

    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO/);

    // 🔴 O comentario de quem la mexeu PERMANECE.
    const { rows } = await pool.query(
      "SELECT obj_description(to_regprocedure($1), 'pg_proc') AS c", [SIG_RESOLVER]);
    expect(rows[0].c).toBe("alterado por outra pessoa");

    // E a definicao nao foi tocada.
    const defDepois = await pool.query(
      "SELECT pg_get_functiondef(to_regprocedure($1)) AS d", [SIG_RESOLVER]);
    expect(defDepois.rows[0].d).toBe(defAntes.rows[0].d);

    const { rows: led } = await pool.query(
      "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
    expect(led[0].n).toBe(0);

    await palco();
  });

  it("🔴 N. can_access_service com comentario onde se espera NULL: a 106 RECUSA", LENTO, async () => {
    // 🔴 `IS DISTINCT FROM` e nao `<>`: com `NULL <> 'texto'` o resultado e
    //    NULL, o IF nao dispara, e a verificacao passava ao lado precisamente
    //    no caso em que ha um comentario a mais.
    await palco(false);
    await pool.query(
      "COMMENT ON FUNCTION public.can_access_service(uuid) IS 'nota de alguem'");

    await expect(pool.query(lerSql(M_106)))
      .rejects.toThrow(/COLAB_106_PREESTADO_INESPERADO/);

    const { rows } = await pool.query(
      "SELECT obj_description(to_regprocedure($1), 'pg_proc') AS c", [SIG_SERVICO]);
    expect(rows[0].c).toBe("nota de alguem");

    const res = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(res.rows[0].prosrc)).not.toMatch(/status/);

    await palco();
  });

  it("os checksums fixados na 106 são os dos ficheiros do repositório", LENTO, async () => {
    const sql = lerSql(M_106);
    const fixados = [...sql.matchAll(/\('(\d{3}[a-z]?_[a-z_]+\.sql)',\s*'([0-9a-f]{64})'\)/g)];
    expect(fixados.length).toBe(3);
    for (const [, ficheiro, checksum] of fixados) {
      expect(checksum, `checksum fixado de ${ficheiro}`).toBe(checksumLf(ficheiro));
    }
  });

  it("🔴 a 106 é ÚNICA, e a 107 é permitida", LENTO, async () => {
    // 🔴 Este ensaio já exigiu que nada viesse depois da 106 — o mesmo padrão
    //    que teve de sair da suite da 105, e pela mesma razão: a chegada
    //    legítima de uma 107 não é regressão da 106. Um guard que proíbe o
    //    futuro não é um guard, é um travão.
    //
    //    O que se prova é UNICIDADE e ausência de COLISÃO.
    const { readdirSync } = await import("node:fs");
    const numeradas = readdirSync(join(process.cwd(), "supabase/migrations"))
      .filter((m) => /^\d{3}[a-z]?_.*\.sql$/.test(m));

    // Exactamente uma migration com o número 106, e é esta.
    const cento6 = numeradas.filter((m) => m.slice(0, 3) === "106");
    expect(cento6).toEqual([NOME_106]);

    // E o rollback corresponde-lhe.
    const rollbacks = readdirSync(join(process.cwd(), "supabase/migrations/rollback"))
      .filter((m) => m.slice(0, 3) === "106");
    expect(rollbacks).toEqual(["106_colaborador_status_autorizacao.down.sql"]);

    // 🔴 Nenhum número duplicado em TODA a cadeia numerada — se alguém criar
    //    outra 106 com sufixo diferente, é aqui que aparece.
    const porNumero = new Map<string, string[]>();
    for (const m of numeradas) {
      const chave = m.slice(0, 4).replace(/_$/, "");
      porNumero.set(chave, [...(porNumero.get(chave) ?? []), m]);
    }
    const colisoes = [...porNumero.entries()].filter(([, fs]) => fs.length > 1);
    expect(colisoes, `números de migration duplicados: ${JSON.stringify(colisoes)}`).toEqual([]);
  });

  it("uma futura 107 não quebra o contrato da 106", LENTO, async () => {
    // 🔴 A prova de regressão do guard acima: simula-se a lista de ficheiros
    //    com uma 107 e verifica-se que a unicidade da 106 continua verdadeira.
    //    Sem isto, alguém poderia reintroduzir «nada depois da 106» e o ensaio
    //    continuaria verde até ao dia em que a 107 nascesse.
    const comFutura = [
      "105_crm_orcamento_editar_rascunho.sql",
      NOME_106,
      "107_qualquer_coisa_futura.sql",
    ];
    const cento6 = comFutura.filter((m) => m.slice(0, 3) === "106");
    expect(cento6).toEqual([NOME_106]);
    expect(comFutura.some((m) => Number(m.slice(0, 3)) > 106)).toBe(true);
  });
});

// ───────────────────────────────────────────────────────────────────────────
describe("21. rollback e recuperação para a frente", () => {
  it("o checksum fixado no rollback é o da 106 deste repositório", LENTO, async () => {
    const down = lerSql(ROLLBACK_106);
    const m = down.match(/CHECKSUM_106 CONSTANT text := '([0-9a-f]{64})'/);
    expect(m).not.toBeNull();
    expect(m![1]).toBe(checksumLf(NOME_106));
  });

  it("🔴 21. rollback repõe a forma anterior e NÃO toca em perfis", LENTO, async () => {
    const antes = await pool.query(
      "SELECT id, status FROM public.profiles ORDER BY id");

    await pool.query(lerSql(ROLLBACK_106));

    // O resolver voltou a ignorar o estado — e é por isso que o ficheiro avisa.
    expect(await resolver(SUSPENSA)).toBe(SUSPENSA);

    const { rows: cfg } = await pool.query(
      "SELECT proconfig FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);
    expect(cfg[0].proconfig).toBeNull();

    const { rows: led } = await pool.query(
      "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
    expect(led[0].n).toBe(0);

    // 🔴 NENHUM perfil foi tocado.
    const depois = await pool.query("SELECT id, status FROM public.profiles ORDER BY id");
    expect(depois.rows).toEqual(antes.rows);

    await palco();
  });

  it("🔴 rollback com estado PARCIAL: fail closed, e nada é alterado", LENTO, async () => {
    // Só o resolver endurecido; can_access_service reposto à mão.
    await pool.query(`
      CREATE OR REPLACE FUNCTION public.can_access_service(p_service_id uuid)
      RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE
      AS $f$ SELECT false $f$;`);

    await expect(pool.query(lerSql(ROLLBACK_106)))
      .rejects.toThrow(/COLAB_106_ROLLBACK_PARTIAL_EFFECT/);

    const { rows } = await pool.query(
      "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
    expect(rows[0].n, "a linha de ledger não se apaga num estado que não se percebe").toBe(1);

    await palco();
  });

  // ─────────────────────────────────────────────────────────────────────────
  // 🔴 D/E/F — ROLLBACK_DOES_NOT_ERASE_LATER_WORK
  //
  //    O checksum do ledger prova que a migration aplicada FOI a 106. Não
  //    prova que as funções continuam como ela as deixou. Sem os guards
  //    abaixo, este rollback substituía trabalho posterior pela forma de 2026
  //    da 034 — desfazendo a migration de outra pessoa, não a sua.
  // ─────────────────────────────────────────────────────────────────────────

  it("🔴 D. resolver alterado DEPOIS da 106: o rollback RECUSA", LENTO, async () => {
    // A alteração posterior mantém `status = 'ativo'` — era isso que fazia a
    // detecção de efeitos ver 2 de 2 e seguir em frente.
    await pool.query(`
      CREATE OR REPLACE FUNCTION public.get_my_profile_id() RETURNS uuid
      LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public
      AS $f$
        SELECT id FROM profiles
         WHERE auth_user_id = auth.uid() AND status = 'ativo' AND email IS NOT NULL
         LIMIT 1;
      $f$;`);

    await expect(pool.query(lerSql(ROLLBACK_106)))
      .rejects.toThrow(/COLAB_106_ROLLBACK_CURRENT_STATE_DIVERGED/);

    // 🔴 O trabalho posterior PERMANECE.
    const { rows } = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(rows[0].prosrc)).toContain("email IS NOT NULL");

    // E o ledger não foi tocado.
    const { rows: led } = await pool.query(
      "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
    expect(led[0].n).toBe(1);

    await palco();
  });

  it("🔴 E. can_access_service alterada DEPOIS da 106: o rollback RECUSA", LENTO, async () => {
    // Mantém `get_my_profile_id()` e mantém `search_path` — passa pela
    // detecção de efeitos antiga, e muda uma regra material: deixa de aceitar
    // reforços pontuais.
    await pool.query(`
      CREATE OR REPLACE FUNCTION public.can_access_service(p_service_id uuid)
      RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE
      SET search_path = pg_catalog, public
      AS $f$
        SELECT EXISTS (
          SELECT 1 FROM public.services s
          JOIN public.profiles p ON p.id = public.get_my_profile_id()
           AND p.company_id = s.company_id
          WHERE s.id = p_service_id
            AND EXISTS (SELECT 1 FROM public.team_members tm
                         WHERE tm.team_id = s.team_id AND tm.collaborator_id = p.id)
        )
      $f$;`);

    await expect(pool.query(lerSql(ROLLBACK_106)))
      .rejects.toThrow(/COLAB_106_ROLLBACK_CURRENT_STATE_DIVERGED/);

    const { rows } = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);
    expect(String(rows[0].prosrc)).not.toContain("service_reinforcements");
    // O resolver também não foi reposto.
    const res = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(res.rows[0].prosrc)).toMatch(/status = 'ativo'/);

    await palco();
  });

  it("🔴 F. só a ACL mudou depois da 106: o rollback RECUSA antes de repor", LENTO, async () => {
    await pool.query("CREATE ROLE papel_extra_rb106 NOLOGIN");
    await pool.query(
      "GRANT EXECUTE ON FUNCTION public.can_access_service(uuid) TO papel_extra_rb106");

    try {
      await expect(pool.query(lerSql(ROLLBACK_106)))
        .rejects.toThrow(/COLAB_106_ROLLBACK_CURRENT_STATE_DIVERGED/);

      // Os corpos continuam os da 106 — nada foi reposto.
      const { rows } = await pool.query(
        "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
      expect(String(rows[0].prosrc)).toMatch(/status = 'ativo'/);

      const { rows: led } = await pool.query(
        "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
      expect(led[0].n).toBe(1);
    } finally {
      await pool.query(
        "REVOKE ALL ON FUNCTION public.can_access_service(uuid) FROM papel_extra_rb106")
        .catch(() => { /* já não existe */ });
      await pool.query("DROP ROLE IF EXISTS papel_extra_rb106");
      await palco();
    }
  });

  it("🔴 K. metadado auxiliar alterado DEPOIS da 106: o rollback RECUSA", LENTO, async () => {
    // Corpo, search_path e ACL intactos. So mudou `COST`. A versao anterior do
    // guard nao media isto, e o `CREATE OR REPLACE` do rollback repunha o
    // default - apagando uma decisao de outra pessoa.
    await pool.query("ALTER FUNCTION public.can_access_service(uuid) COST 17");

    await expect(pool.query(lerSql(ROLLBACK_106)))
      .rejects.toThrow(/COLAB_106_ROLLBACK_CURRENT_STATE_DIVERGED/);

    const { rows } = await pool.query(
      "SELECT procost FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_SERVICO]);
    expect(Number(rows[0].procost)).toBe(17);

    // E o resolver continua endurecido: nada foi reposto.
    const res = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(res.rows[0].prosrc)).toMatch(/status = 'ativo'/);

    await palco();
  });

  it("🔴 L. owner alterado DEPOIS da 106: o rollback RECUSA", LENTO, async () => {
    await pool.query("CREATE ROLE dono_teste_rb106 NOLOGIN");
    await pool.query("ALTER FUNCTION public.get_my_profile_id() OWNER TO dono_teste_rb106");

    try {
      await expect(pool.query(lerSql(ROLLBACK_106)))
        .rejects.toThrow(/COLAB_106_ROLLBACK_CURRENT_STATE_DIVERGED/);

      const { rows } = await pool.query(
        "SELECT proowner::regrole::text AS o FROM pg_proc WHERE oid = to_regprocedure($1)",
        [SIG_RESOLVER]);
      expect(rows[0].o).toBe("dono_teste_rb106");

      const { rows: led } = await pool.query(
        "SELECT count(*)::int AS n FROM public._migrations WHERE name = $1", [NOME_106]);
      expect(led[0].n).toBe(1);
    } finally {
      await pool.query("ALTER FUNCTION public.get_my_profile_id() OWNER TO postgres")
        .catch(() => { /* o palco vai recriar */ });
      await pool.query("DROP ROLE IF EXISTS dono_teste_rb106");
      await palco();
    }
  });

  it("🔴 O. comentario alterado DEPOIS da 106: o rollback RECUSA", LENTO, async () => {
    await pool.query(
      "COMMENT ON FUNCTION public.can_access_service(uuid) IS 'nota posterior'");

    await expect(pool.query(lerSql(ROLLBACK_106)))
      .rejects.toThrow(/COLAB_106_ROLLBACK_CURRENT_STATE_DIVERGED/);

    const { rows } = await pool.query(
      "SELECT obj_description(to_regprocedure($1), 'pg_proc') AS c", [SIG_SERVICO]);
    expect(rows[0].c).toBe("nota posterior");

    // E nada foi reposto.
    const res = await pool.query(
      "SELECT prosrc FROM pg_proc WHERE oid = to_regprocedure($1)", [SIG_RESOLVER]);
    expect(String(res.rows[0].prosrc)).toMatch(/status = 'ativo'/);

    await palco();
  });

  it("🔴 P. rollback restaura os comentarios do PREDECESSOR VIVO", LENTO, async () => {
    // 🔴 O defeito que isto fecha: o rollback escrevia um comentario
    //    ACENTUADO, copiado do ficheiro da 101b, e nem sequer tocava no de
    //    `can_access_service` — que ficava a dizer que passa pelo resolver
    //    enquanto o corpo voltava a ser o de 2026 da 034. Comentario e
    //    implementacao a contradizerem-se.
    const antes106 = await pool.query(`
      SELECT obj_description(to_regprocedure($1), 'pg_proc') AS resolver,
             obj_description(to_regprocedure($2), 'pg_proc') AS servico`,
      [SIG_RESOLVER, SIG_SERVICO]);
    expect(antes106.rows[0].resolver).toContain("Desde a 106");
    expect(antes106.rows[0].servico).not.toBeNull();

    await pool.query(lerSql(ROLLBACK_106));

    const { rows } = await pool.query(`
      SELECT obj_description(to_regprocedure($1), 'pg_proc') AS resolver,
             obj_description(to_regprocedure($2), 'pg_proc') AS servico`,
      [SIG_RESOLVER, SIG_SERVICO]);

    expect(rows[0].resolver).toBe(COMENTARIO_PREDECESSOR);
    expect(rows[0].servico).toBeNull();

    await palco();
  });

  it("🔴 rollback com checksum divergente: nada é alterado", LENTO, async () => {
    await pool.query("UPDATE public._migrations SET checksum = $2 WHERE name = $1",
      [NOME_106, "f".repeat(64)]);

    await expect(pool.query(lerSql(ROLLBACK_106)))
      .rejects.toThrow(/COLAB_106_ROLLBACK_CHECKSUM_DIVERGENTE/);

    // O resolver continua endurecido.
    expect(await resolver(SUSPENSA)).toBeNull();
    await registarNoLedger(NOME_106);
  });

  it("🔴 rollback com efeitos e SEM ledger: ALIENADO", LENTO, async () => {
    await pool.query("DELETE FROM public._migrations WHERE name = $1", [NOME_106]);
    await expect(pool.query(lerSql(ROLLBACK_106)))
      .rejects.toThrow(/COLAB_106_ROLLBACK_ALIENADO/);
    expect(await resolver(SUSPENSA)).toBeNull();
    await registarNoLedger(NOME_106);
  });

  it("rollback sem ledger e sem efeitos é no-op", LENTO, async () => {
    await palco(false);
    await expect(pool.query(lerSql(ROLLBACK_106))).resolves.toBeDefined();
    await palco();
  });

  it("🔴 forward recovery: rollback e voltar a aplicar", LENTO, async () => {
    await pool.query(lerSql(ROLLBACK_106));
    expect(await resolver(SUSPENSA)).toBe(SUSPENSA);

    await pool.query(lerSql(M_106));
    await registarNoLedger(NOME_106);

    expect(await resolver(SUSPENSA)).toBeNull();
    expect(await resolver(ATIVA)).toBe(ATIVA);
    expect(await podeVerServico(ATIVA, SERVICO)).toBe(true);
  });
});
