// ============================================================================
// Visitas — o runtime contra a base a sério
// ============================================================================
//
// 🔴 O que esta suite existe para apanhar.
//
//    O runtime de visitas veio de uma branch ampla onde tinha três defeitos
//    que nenhum teste de código puro apanha, porque nenhum deles é um erro de
//    sintaxe nem de tipos:
//
//      1. o formulário só sabia marcar visitas a LEADS, e mandava
//         `clientId: null` fixo — metade do modelo da 102 por usar;
//
//      2. fechar uma visita lia o estado e só depois gravava, sem prender o
//         que tinha lido: dois gestores a fechar a mesma visita ao mesmo
//         tempo, e a segunda escrita ganhava em silêncio;
//
//      3. o painel de desfecho abria em modo de escrita para visitas já
//         fechadas — reescrever história sem rasto.
//
//    O (2) é o que obriga a Postgres real: com mocks, duas «transações»
//    concorrentes são duas chamadas em fila, e o defeito passa a verde.
//
// O palco é a cadeia como está em produção HOJE: 101 → 101a → 101b → 102.
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { startPostgresContainer, type PostgresContainer } from "./helpers/pg-container";
import { baselineCompleto } from "./helpers/production-baseline";
import { MIGRATIONS_CRM, migrationCrm } from "./helpers/crm-pg-harness";
import { VISIT_CLOSING_STATUSES, VISIT_OPEN_STATUS } from "@/lib/crm/visits";

const CONTAINER = `crmvis-${process.pid}`;
const LENTO = { timeout: 120_000 };

const EMPRESA = "11111111-1111-4111-8111-111111111111";
const OUTRA = "22222222-2222-4222-8222-222222222222";
const GESTORA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const GESTORA_OUTRA = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const COLAB = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
const CLIENTE_A = "c1111111-1111-4111-8111-111111111111";
const CLIENTE_B = "c2222222-2222-4222-8222-222222222222";

const M_101B = "supabase/migrations/101b_identity_reconciliation.sql";
const M_102 = "supabase/migrations/102_crm_visitas_comerciais.sql";

const CADEIA = [
  "101_crm_leads.sql",
  "101a_crm_rpc_acl_hardening.sql",
  "101b_identity_reconciliation.sql",
] as const;

let container: PostgresContainer;
let pool: pg.Pool;
let leadA = "";

const lerSql = (rel: string) => readFileSync(join(process.cwd(), rel), "utf8");

const checksumLf = (ficheiro: string): string =>
  createHash("sha256")
    .update(lerSql(`supabase/migrations/${ficheiro}`).split("\r\n").join("\n").split("\r").join("\n"))
    .digest("hex");

/** A cadeia real, com o ledger que o portão de proveniência da 102 exige. */
async function palco(): Promise<void> {
  await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;");
  await pool.query("DROP SCHEMA IF EXISTS auth CASCADE;");
  await pool.query(baselineCompleto());
  await pool.query("ALTER ROLE service_role BYPASSRLS;");
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS clients_id_company_unique ON public.clients (id, company_id);
    ALTER TABLE public.data_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    CREATE OR REPLACE FUNCTION public.update_updated_at() RETURNS TRIGGER AS $upd$
      BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $upd$ LANGUAGE plpgsql;
    CREATE OR REPLACE FUNCTION public.fn_capture_history() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $h$
      BEGIN RETURN COALESCE(NEW, OLD); END; $h$;
  `);
  await pool.query(`
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
  `);
  for (const m of MIGRATIONS_CRM) await pool.query(migrationCrm(m));
  await pool.query(lerSql(M_101B));

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public._migrations (
      name text PRIMARY KEY, checksum text, applied_at timestamptz NOT NULL DEFAULT now())`);
  for (const nome of CADEIA) {
    await pool.query(
      "INSERT INTO public._migrations (name, checksum) VALUES ($1,$2) ON CONFLICT (name) DO NOTHING",
      [nome, checksumLf(nome)],
    );
  }

  await semear();
  await pool.query(lerSql(M_102));
}

async function semear(): Promise<void> {
  await pool.query("INSERT INTO public.companies (id,name,slug) VALUES ($1,'A','a'),($2,'B','b')",
    [EMPRESA, OUTRA]);
  await pool.query("INSERT INTO auth.users (id,email) VALUES ($1,'g@a.pt'),($2,'g@b.pt'),($3,'c@a.pt')",
    [GESTORA, GESTORA_OUTRA, COLAB]);
  await pool.query(
    `INSERT INTO public.profiles (id, company_id, full_name, role, status, auth_user_id) VALUES
      ($1,$2,'Gestora A','gestor','ativo',$1),
      ($3,$4,'Gestora B','gestor','ativo',$3),
      ($5,$2,'Colaboradora','colaborador','ativo',$5)`,
    [GESTORA, EMPRESA, GESTORA_OUTRA, OUTRA, COLAB],
  );
  await pool.query(
    "INSERT INTO public.clients (id,company_id,name) VALUES ($1,$2,'Cliente A'), ($3,$4,'Cliente B')",
    [CLIENTE_A, EMPRESA, CLIENTE_B, OUTRA],
  );
  const { rows } = await pool.query(
    "INSERT INTO public.crm_leads (company_id, name) VALUES ($1,'Condomínio Alfa') RETURNING id",
    [EMPRESA],
  );
  leadA = rows[0].id as string;
}

/** Marca uma visita como a Server Action marca: por `service_role`. */
async function marcar(over: Record<string, unknown> = {}): Promise<string> {
  const inicio = new Date();
  const campos: Record<string, unknown> = {
    company_id: EMPRESA,
    lead_id: leadA,
    client_id: null,
    scheduled_start: inicio.toISOString(),
    scheduled_end: new Date(inicio.getTime() + 3_600_000).toISOString(),
    created_by: GESTORA,
    ...over,
  };
  const colunas = Object.keys(campos);
  const marcas = colunas.map((_, i) => `$${i + 1}`).join(", ");
  const { rows } = await pool.query(
    `INSERT INTO public.crm_visits (${colunas.join(", ")}) VALUES (${marcas}) RETURNING id`,
    Object.values(campos),
  );
  return rows[0].id as string;
}

/**
 * O UPDATE que a action faz — com a guarda de concorrência no próprio comando.
 * Devolve a linha afectada, ou `null` se não afectou nenhuma.
 */
async function fechar(
  c: pg.Pool | pg.Client,
  visitId: string,
  destino: string,
): Promise<string | null> {
  const agora = new Date().toISOString();
  const { rows } = await c.query(
    `UPDATE public.crm_visits
        SET status = $3,
            completed_at = CASE WHEN $3 = 'realizada' THEN $4::timestamptz ELSE NULL END,
            cancelled_at = CASE WHEN $3 = 'cancelada' THEN $4::timestamptz ELSE NULL END
      WHERE company_id = $1 AND id = $2 AND status = $5
      RETURNING id`,
    [EMPRESA, visitId, destino, agora, VISIT_OPEN_STATUS],
  );
  return rows.length > 0 ? (rows[0].id as string) : null;
}

beforeAll(async () => {
  container = await startPostgresContainer({ name: CONTAINER, database: "crmvis", memory: "512m" });
  pool = new pg.Pool({ ...container.connection, max: 6 });
}, 180_000);

afterAll(async () => {
  await pool?.end().catch(() => { /* já fechado */ });
  container?.stop();
});

beforeEach(async () => { await palco(); }, 120_000);

// ---------------------------------------------------------------------------
describe("a quem se vai — lead OU cliente", () => {
  it("só lead: aceite", LENTO, async () => {
    expect(await marcar({ lead_id: leadA, client_id: null })).toBeTruthy();
  });

  it("🔴 só cliente: aceite — era a metade do modelo que o formulário não usava", LENTO, async () => {
    expect(await marcar({ lead_id: null, client_id: CLIENTE_A })).toBeTruthy();
  });

  it("🔴 lead E cliente: recusado", LENTO, async () => {
    await expect(marcar({ lead_id: leadA, client_id: CLIENTE_A }))
      .rejects.toThrow(/crm_visits_um_destinatario/);
  });

  it("🔴 nem lead nem cliente: recusado", LENTO, async () => {
    await expect(marcar({ lead_id: null, client_id: null }))
      .rejects.toThrow(/crm_visits_um_destinatario/);
  });

  it("a janela tem de fazer sentido", LENTO, async () => {
    const agora = new Date();
    await expect(marcar({
      scheduled_start: agora.toISOString(),
      scheduled_end: new Date(agora.getTime() - 60_000).toISOString(),
    })).rejects.toThrow(/crm_visits_janela_valida/);
  });
});

// ---------------------------------------------------------------------------
describe("isolamento por empresa", () => {
  it("🔴 cliente de outra empresa: recusado pela FK composta", LENTO, async () => {
    await expect(marcar({ lead_id: null, client_id: CLIENTE_B })).rejects.toThrow();
  });

  it("🔴 responsável de outra empresa: recusado", LENTO, async () => {
    await expect(marcar({ assigned_to: GESTORA_OUTRA })).rejects.toThrow();
  });

  it("🔴 a gestora da outra empresa não vê estas visitas", LENTO, async () => {
    await marcar();
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [GESTORA_OUTRA]);
      await c.query("SET ROLE authenticated");
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_visits");
      expect(rows[0].n).toBe(0);
    } finally { await c.end(); }
  });

  it("🔴 uma colaboradora não vê a agenda comercial", LENTO, async () => {
    await marcar();
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [COLAB]);
      await c.query("SET ROLE authenticated");
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_visits");
      expect(rows[0].n).toBe(0);
    } finally { await c.end(); }
  });

  it("a gestora da empresa vê as suas", LENTO, async () => {
    await marcar();
    const c = new pg.Client({ ...container.connection });
    await c.connect();
    try {
      await c.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [GESTORA]);
      await c.query("SET ROLE authenticated");
      const { rows } = await c.query("SELECT count(*)::int n FROM public.crm_visits");
      expect(rows[0].n).toBe(1);
    } finally { await c.end(); }
  });
});

// ---------------------------------------------------------------------------
describe("ciclo de vida — fechar é de ida", () => {
  for (const destino of VISIT_CLOSING_STATUSES) {
    it(`agendada → ${destino}`, LENTO, async () => {
      const v = await marcar();
      expect(await fechar(pool, v, destino)).toBe(v);
      const { rows } = await pool.query("SELECT status FROM public.crm_visits WHERE id=$1", [v]);
      expect(rows[0].status).toBe(destino);
    });
  }

  it("🔴 uma visita já fechada não volta a ser fechada", LENTO, async () => {
    const v = await marcar();
    expect(await fechar(pool, v, "realizada")).toBe(v);

    // Segunda tentativa: zero linhas. A action traduz isto em CONFLICT.
    expect(await fechar(pool, v, "cancelada")).toBeNull();

    const { rows } = await pool.query(
      "SELECT status, completed_at, cancelled_at FROM public.crm_visits WHERE id=$1", [v]);
    expect(rows[0].status).toBe("realizada");
    expect(rows[0].completed_at).not.toBeNull();
    expect(rows[0].cancelled_at).toBeNull();
  });

  // -------------------------------------------------------------------------
  // 🔴 A CORRIDA. Sem a condição `status = 'agendada'` dentro do UPDATE, os
  //    dois ganham e o último a escrever apaga o desfecho do primeiro.
  // -------------------------------------------------------------------------
  it("🔴 dois gestores a fechar ao mesmo tempo: só um ganha", LENTO, async () => {
    const v = await marcar();

    const a = new pg.Client({ ...container.connection });
    const b = new pg.Client({ ...container.connection });
    await a.connect();
    await b.connect();

    try {
      await a.query("BEGIN");
      await b.query("BEGIN");

      // A fecha como realizada e segura o lock de linha, sem commitar.
      const ganhouA = await fechar(a, v, "realizada");
      expect(ganhouA).toBe(v);

      // B tenta fechar como cancelada: fica à espera do lock de A.
      const tentativaB = fechar(b, v, "cancelada");
      await new Promise((r) => setTimeout(r, 800));

      await a.query("COMMIT");

      // Ao acordar, B relê a linha já com `realizada` e a condição falha.
      expect(await tentativaB).toBeNull();
      await b.query("COMMIT");
    } finally {
      await a.end().catch(() => { /* já fechada */ });
      await b.end().catch(() => { /* já fechada */ });
    }

    const { rows } = await pool.query(
      "SELECT status, cancelled_at FROM public.crm_visits WHERE id=$1", [v]);
    expect(rows[0].status).toBe("realizada");
    expect(rows[0].cancelled_at).toBeNull();
  });

  it("um desfecho sem data é recusado pela base", LENTO, async () => {
    const v = await marcar();
    await expect(
      pool.query("UPDATE public.crm_visits SET status='realizada' WHERE id=$1", [v]),
    ).rejects.toThrow(/crm_visits_realizada_tem_data/);
  });
});

// ---------------------------------------------------------------------------
describe("a fronteira com a operação", () => {
  it("🔴 marcar e fechar visitas não cria serviços, contratos nem locais", LENTO, async () => {
    const v = await marcar();
    await fechar(pool, v, "realizada");
    await marcar({ lead_id: null, client_id: CLIENTE_A });

    for (const t of ["services", "contracts", "locations", "invoices", "cash_flow_entries"]) {
      const { rows } = await pool.query(`SELECT count(*)::int n FROM public.${t}`);
      expect(rows[0].n, `${t} devia continuar vazia`).toBe(0);
    }
  });
});
