-- ============================================================================
-- 064 — Atomicidade de domínio, revisão, idempotência e outbox
-- ============================================================================

ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;
ALTER TABLE public.team_members ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;
ALTER TABLE public.invoice_items ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;

ALTER TABLE public.services ADD COLUMN IF NOT EXISTS override_fields text[] NOT NULL DEFAULT '{}';

CREATE OR REPLACE FUNCTION public.fn_increment_revision()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.revision := COALESCE(OLD.revision, 0) + 1;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_clients_revision ON public.clients;
CREATE TRIGGER trg_clients_revision BEFORE UPDATE ON public.clients
  FOR EACH ROW EXECUTE FUNCTION public.fn_increment_revision();

DROP TRIGGER IF EXISTS trg_locations_revision ON public.locations;
CREATE TRIGGER trg_locations_revision BEFORE UPDATE ON public.locations
  FOR EACH ROW EXECUTE FUNCTION public.fn_increment_revision();

DROP TRIGGER IF EXISTS trg_contracts_revision ON public.contracts;
CREATE TRIGGER trg_contracts_revision BEFORE UPDATE ON public.contracts
  FOR EACH ROW EXECUTE FUNCTION public.fn_increment_revision();

DROP TRIGGER IF EXISTS trg_services_revision ON public.services;
CREATE TRIGGER trg_services_revision BEFORE UPDATE ON public.services
  FOR EACH ROW EXECUTE FUNCTION public.fn_increment_revision();

DROP TRIGGER IF EXISTS trg_teams_revision ON public.teams;
CREATE TRIGGER trg_teams_revision BEFORE UPDATE ON public.teams
  FOR EACH ROW EXECUTE FUNCTION public.fn_increment_revision();

DROP TRIGGER IF EXISTS trg_team_members_revision ON public.team_members;
CREATE TRIGGER trg_team_members_revision BEFORE UPDATE ON public.team_members
  FOR EACH ROW EXECUTE FUNCTION public.fn_increment_revision();

DROP TRIGGER IF EXISTS trg_invoices_revision ON public.invoices;
CREATE TRIGGER trg_invoices_revision BEFORE UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.fn_increment_revision();

DROP TRIGGER IF EXISTS trg_invoice_items_revision ON public.invoice_items;
CREATE TRIGGER trg_invoice_items_revision BEFORE UPDATE ON public.invoice_items
  FOR EACH ROW EXECUTE FUNCTION public.fn_increment_revision();

CREATE TABLE IF NOT EXISTS public.domain_mutations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  mutation_id uuid NOT NULL,
  domain text NOT NULL,
  status text NOT NULL CHECK (status IN ('completed')),
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(company_id, mutation_id)
);

CREATE TABLE IF NOT EXISTS public.company_change_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  mutation_id uuid NOT NULL,
  domain text NOT NULL,
  event_type text NOT NULL,
  entity_ids uuid[] NOT NULL DEFAULT '{}',
  scopes text[] NOT NULL DEFAULT '{}',
  affected_range tstzrange,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  delivered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(company_id, sequence),
  UNIQUE(company_id, mutation_id, domain, event_type)
);

CREATE INDEX IF NOT EXISTS idx_company_change_events_pending
  ON public.company_change_events(company_id, sequence)
  WHERE delivered_at IS NULL;

ALTER TABLE public.domain_mutations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_change_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service role domain mutations" ON public.domain_mutations;
CREATE POLICY "service role domain mutations" ON public.domain_mutations
  FOR ALL USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "managers see company change events" ON public.company_change_events;
CREATE POLICY "managers see company change events" ON public.company_change_events
  FOR SELECT USING (
    company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid())
    AND (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'gestor')
  );

CREATE OR REPLACE FUNCTION public.record_company_change_event(
  p_company_id uuid,
  p_mutation_id uuid,
  p_domain text,
  p_event_type text,
  p_entity_ids uuid[],
  p_scopes text[],
  p_affected_range tstzrange DEFAULT NULL,
  p_payload jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event public.company_change_events;
BEGIN
  INSERT INTO public.company_change_events (
    company_id, mutation_id, domain, event_type, entity_ids, scopes, affected_range, payload
  )
  VALUES (
    p_company_id,
    p_mutation_id,
    p_domain,
    p_event_type,
    COALESCE(p_entity_ids, '{}'),
    COALESCE(p_scopes, '{}'),
    p_affected_range,
    COALESCE(p_payload, '{}'::jsonb)
  )
  ON CONFLICT (company_id, mutation_id, domain, event_type)
  DO UPDATE SET payload = EXCLUDED.payload
  RETURNING * INTO v_event;

  RETURN jsonb_build_object(
    'event_id', v_event.id,
    'sequence', v_event.sequence
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.set_invoice_status_atomic(
  p_invoice_id uuid,
  p_company_id uuid,
  p_actor uuid,
  p_status text,
  p_payment_method text DEFAULT NULL,
  p_mutation_id uuid DEFAULT gen_random_uuid(),
  p_expected_revision integer DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing jsonb;
  v_inv record;
  v_client_name text;
  v_cash_id uuid;
  v_event jsonb;
  v_result jsonb;
BEGIN
  SELECT result INTO v_existing
  FROM public.domain_mutations
  WHERE company_id = p_company_id AND mutation_id = p_mutation_id;
  IF FOUND THEN
    RETURN v_existing;
  END IF;

  IF p_status NOT IN ('rascunho', 'pendente', 'pago', 'vencido', 'cancelado') THEN
    RAISE EXCEPTION 'Estado de fatura inválido: %', p_status;
  END IF;

  IF p_actor IS NOT NULL THEN
    PERFORM set_config('app.actor_id', p_actor::text, true);
  END IF;

  SELECT id, company_id, client_id, invoice_number, total, status, paid_at, revision
    INTO v_inv
  FROM public.invoices
  WHERE id = p_invoice_id AND company_id = p_company_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fatura não encontrada.';
  END IF;

  IF p_expected_revision IS NOT NULL AND v_inv.revision <> p_expected_revision THEN
    RAISE EXCEPTION 'Conflito de revisão. Atual: %, esperado: %', v_inv.revision, p_expected_revision;
  END IF;

  UPDATE public.invoices
     SET status = p_status,
         paid_at = CASE WHEN p_status = 'pago' THEN COALESCE(v_inv.paid_at, now()) ELSE NULL END,
         payment_method = CASE WHEN p_status = 'pago' THEN p_payment_method ELSE NULL END
   WHERE id = p_invoice_id AND company_id = p_company_id
   RETURNING revision INTO v_inv.revision;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nada foi gravado na fatura.';
  END IF;

  IF p_status = 'pago' AND COALESCE(v_inv.total, 0) > 0 THEN
    SELECT name INTO v_client_name FROM public.clients WHERE id = v_inv.client_id;
    INSERT INTO public.cash_flow_entries (
      company_id, type, amount, description, category, date, reference_id, reference_type, status
    )
    VALUES (
      p_company_id,
      'entrada',
      v_inv.total,
      'Fatura ' || v_inv.invoice_number || ' - ' || COALESCE(v_client_name, 'Cliente'),
      'faturacao',
      (now() AT TIME ZONE 'Europe/Lisbon')::date,
      p_invoice_id,
      'invoice',
      'confirmado'
    )
    ON CONFLICT (company_id, reference_type, reference_id)
    WHERE reference_type IS NOT NULL AND reference_id IS NOT NULL
    DO UPDATE SET
      amount = EXCLUDED.amount,
      description = EXCLUDED.description,
      date = EXCLUDED.date,
      status = EXCLUDED.status
    RETURNING id INTO v_cash_id;
  ELSE
    DELETE FROM public.cash_flow_entries
     WHERE company_id = p_company_id
       AND reference_type = 'invoice'
       AND reference_id = p_invoice_id
     RETURNING id INTO v_cash_id;
  END IF;

  v_event := public.record_company_change_event(
    p_company_id,
    p_mutation_id,
    'billing',
    'invoice_status_changed',
    ARRAY[p_invoice_id],
    ARRAY['cobrancas', 'financeiro'],
    NULL,
    jsonb_build_object('invoice_id', p_invoice_id, 'status', p_status, 'cash_flow_entry_id', v_cash_id)
  );

  v_result := jsonb_build_object(
    'ok', true,
    'invoice_id', p_invoice_id,
    'status', p_status,
    'revision', v_inv.revision,
    'cash_flow_entry_id', v_cash_id,
    'event', v_event
  );

  INSERT INTO public.domain_mutations(company_id, mutation_id, domain, status, result)
  VALUES (p_company_id, p_mutation_id, 'billing', 'completed', v_result);

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_client_atomic(
  p_client_id uuid,
  p_company_id uuid,
  p_actor uuid,
  p_mutation_id uuid DEFAULT gen_random_uuid(),
  p_expected_revision integer DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing jsonb;
  v_client record;
  v_location_ids uuid[];
  v_deleted_services integer := 0;
  v_deleted_contracts integer := 0;
  v_deleted_invoices integer := 0;
  v_event jsonb;
  v_result jsonb;
BEGIN
  SELECT result INTO v_existing
  FROM public.domain_mutations
  WHERE company_id = p_company_id AND mutation_id = p_mutation_id;
  IF FOUND THEN
    RETURN v_existing;
  END IF;

  IF p_actor IS NOT NULL THEN
    PERFORM set_config('app.actor_id', p_actor::text, true);
  END IF;

  SELECT id, name, revision INTO v_client
  FROM public.clients
  WHERE id = p_client_id AND company_id = p_company_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Cliente inválido.';
  END IF;

  IF p_expected_revision IS NOT NULL AND v_client.revision <> p_expected_revision THEN
    RAISE EXCEPTION 'Conflito de revisão. Atual: %, esperado: %', v_client.revision, p_expected_revision;
  END IF;

  PERFORM 1
  FROM public.locations
  WHERE client_id = p_client_id AND company_id = p_company_id
  FOR UPDATE;

  SELECT COALESCE(array_agg(id), '{}') INTO v_location_ids
  FROM public.locations
  WHERE client_id = p_client_id AND company_id = p_company_id;

  IF array_length(v_location_ids, 1) IS NOT NULL THEN
    DELETE FROM public.services
     WHERE company_id = p_company_id AND location_id = ANY(v_location_ids);
    GET DIAGNOSTICS v_deleted_services = ROW_COUNT;

    DELETE FROM public.contracts
     WHERE company_id = p_company_id AND location_id = ANY(v_location_ids);
    GET DIAGNOSTICS v_deleted_contracts = ROW_COUNT;
  END IF;

  DELETE FROM public.cash_flow_entries cf
   USING public.invoices i
   WHERE i.id = cf.reference_id
     AND cf.reference_type = 'invoice'
     AND i.company_id = p_company_id
     AND i.client_id = p_client_id;

  DELETE FROM public.invoices
   WHERE company_id = p_company_id AND client_id = p_client_id;
  GET DIAGNOSTICS v_deleted_invoices = ROW_COUNT;

  DELETE FROM public.clients
   WHERE id = p_client_id AND company_id = p_company_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nada foi eliminado.';
  END IF;

  v_event := public.record_company_change_event(
    p_company_id,
    p_mutation_id,
    'clients',
    'client_deleted',
    ARRAY[p_client_id],
    ARRAY['clientes', 'calendario', 'contratos', 'cobrancas'],
    NULL,
    jsonb_build_object(
      'client_id', p_client_id,
      'deleted_services', v_deleted_services,
      'deleted_contracts', v_deleted_contracts,
      'deleted_invoices', v_deleted_invoices
    )
  );

  v_result := jsonb_build_object(
    'ok', true,
    'client_id', p_client_id,
    'deleted_services', v_deleted_services,
    'deleted_contracts', v_deleted_contracts,
    'deleted_invoices', v_deleted_invoices,
    'event', v_event
  );

  INSERT INTO public.domain_mutations(company_id, mutation_id, domain, status, result)
  VALUES (p_company_id, p_mutation_id, 'clients', 'completed', v_result);

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.record_company_change_event(uuid, uuid, text, text, uuid[], text[], tstzrange, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_invoice_status_atomic(uuid, uuid, uuid, text, text, uuid, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_client_atomic(uuid, uuid, uuid, uuid, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_invoice_status_atomic(uuid, uuid, uuid, text, text, uuid, integer) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.delete_client_atomic(uuid, uuid, uuid, uuid, integer) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_company_change_event(uuid, uuid, text, text, uuid[], text[], tstzrange, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_invoice_status_atomic(uuid, uuid, uuid, text, text, uuid, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_client_atomic(uuid, uuid, uuid, uuid, integer) TO service_role;
